import type { ModuleDetail } from "./types";

/* Module pages: ministries, service-planning, groups, learning, onboarding, camps — their catalogue group is the `group` field below. */
export const activitiesModules: ModuleDetail[] = [
  {
    id: "ministries",
    group: "serving",
    related: ["service-planning", "people", "groups", "telegram-bot"],
    copy: {
      ua: {
        seoTitle: "Служіння — модуль «Моя Церква»",
        seoDescription: "Команди, ролі, графіки, підтвердження участі та явка кожного служіння церкви. Служителі бачать свій графік у телефоні, лідер — хто підтвердив.",
        title: "Кожне служіння має команду, ролі й графік",
        lead: "Модуль «Служіння» збирає кожну команду церкви — прославлення, звук, зустріч гостей, дитяче — в одному місці: хто в складі, хто за що відповідає, хто служить цієї неділі й хто вже підтвердив.",
        highlights: [
          "Склад і ролі кожної команди",
          "Графік служінь на місяць уперед",
          "Підтвердження участі одним натисканням",
          "Явка та навантаження служителів",
        ],
        features: [
          { icon: "HeartHandshake", title: "Команди й ролі", text: "Прославлення, звук, зустріч гостей, дитяче — у кожної команди свій склад, лідер і ролі: вокал, клавіші, звукорежисер." },
          { icon: "CalendarCheck", title: "Графік на місяць", text: "Ставте служителів у графік на тижні вперед. Хто в якій ролі — видно й лідеру, і кожному служителю в телефоні." },
          { icon: "CheckCircle2", title: "Підтвердження й заміни", text: "Служитель підтверджує участь одним натисканням або просить заміну — лідер одразу бачить дірки в графіку." },
          { icon: "BellRing", title: "Нагадування самі", text: "Бот нагадає за день і за годину до служіння. Лідеру не треба писати в чат «хто завтра на звуці?»." },
          { icon: "Gauge", title: "Навантаження", text: "Хто служить чотири неділі поспіль, а хто жодної — видно на одному екрані. Розподіляйте, поки люди не вигоріли." },
          { icon: "History", title: "Історія та передача", text: "Склад, графіки й явка зберігаються в системі. Лідер пішов — наступний бачить усе з першого дня." },
        ],
        steps: [
          { title: "Створіть команди", text: "Додайте служіння церкви й ролі в кожному: від вокалу до паркування. Людей підтягуйте з бази — без повторного вводу." },
          { title: "Складіть графік", text: "Поставте служителів на найближчі неділі або скопіюйте графік минулого місяця. Система покаже накладки з іншими служіннями." },
          { title: "Збирайте підтвердження", text: "Служителі отримують графік у боті й підтверджують участь. Хто мовчить — лідер бачить і нагадує." },
          { title: "Дивіться явку", text: "Після служіння лідер відмічає, хто був. Навантаження й пропуски накопичуються в історії людини." },
        ],
        audience: [
          { role: "pastor", text: "Бачить усі служіння церкви: скільки людей служить, де не вистачає рук, які команди перевантажені." },
          { role: "leader", text: "Веде свою команду: склад, ролі, графік на місяць і підтвердження — без нагадувань у чаті." },
          { role: "volunteer", text: "Бачить свій графік у телефоні, підтверджує участь одним натисканням або просить заміну." },
        ],
        faq: [
          { q: "Чи може одна людина бути в кількох служіннях?", a: "Так. Людина може співати в прославленні й раз на місяць стояти на зустрічі гостей. Система покаже накладку, якщо обидва служіння випадуть на одну неділю." },
          { q: "Як служителі дізнаються про графік?", a: "Через Telegram-бот або застосунок: коли лідер публікує графік, кожен отримує свої дати й підтверджує участь. Хто не підтвердив — бот нагадує сам." },
          { q: "Що робити, якщо служитель не може прийти?", a: "Він натискає «попросити заміну», лідер бачить це в графіку й обирає з вільних людей команди. Історія замін зберігається." },
          { q: "Чи бачить лідер прославлення склад дитячого служіння?", a: "Ні, якщо ви не дали такий доступ. Кожен лідер бачить лише свої команди, пастор — усі." },
        ],
        mock: {
          kind: "table",
          title: "Графік команд · 21 квітня",
          subtitle: "6 служінь · 4 з 6 підтвердили",
          columns: ["Служитель", "Служіння", "Роль"],
          rows: [
            { cells: ["Олена Ковальчук", "Прославлення", "Вокал"], badge: { label: "Підтвердила", tone: "green" } },
            { cells: ["Дмитро Лис", "Звук", "Пульт"], badge: { label: "Очікує", tone: "amber" } },
            { cells: ["Наталя Рудь", "Дитяче", "Вчитель 6–9"], badge: { label: "Підтвердила", tone: "green" } },
            { cells: ["Василь Панченко", "Зустріч гостей", "Вхід"], badge: { label: "Підтвердив", tone: "green" } },
            { cells: ["Андрій Мельник", "Прославлення", "Кахон"], badge: { label: "Просить заміну", tone: "red" } },
            { cells: ["Ірина Шевчук", "Кафе", "Бариста"], badge: { label: "Підтвердила", tone: "green" } },
          ],
        },
      },
      en: {
        seoTitle: "Ministries — MyChurch module",
        seoDescription: "Teams, roles, rotas, confirmations and attendance for every ministry in the church. Volunteers see their rota on their phone, leaders see who has confirmed.",
        title: "Every ministry with a team, roles and a rota",
        lead: "The Ministries module brings every team in the church — worship, sound, welcome, kids — into one place: who is on the team, who owns which role, who serves this Sunday and who has already confirmed.",
        highlights: [
          "Members and roles for every team",
          "Rota a month ahead",
          "One-tap confirmations",
          "Attendance and volunteer workload",
        ],
        features: [
          { icon: "HeartHandshake", title: "Teams and roles", text: "Worship, sound, welcome, kids — each team has its own members, leader and roles: vocals, keys, sound engineer." },
          { icon: "CalendarCheck", title: "Rota a month ahead", text: "Put volunteers on the rota weeks in advance. Who serves in which role is visible to the leader and to every volunteer on their phone." },
          { icon: "CheckCircle2", title: "Confirmations and cover", text: "A volunteer confirms with one tap or asks for cover — the leader sees gaps in the rota straight away." },
          { icon: "BellRing", title: "Reminders on their own", text: "The bot reminds a day and an hour before the service. No leader has to ask \"who's on sound tomorrow?\" in a chat." },
          { icon: "Gauge", title: "Workload", text: "Who has served four Sundays in a row and who hasn't served at all — on one screen. Spread the load before people burn out." },
          { icon: "History", title: "History and handover", text: "Members, rotas and attendance stay in the system. A leader leaves — the next one sees everything from day one." },
        ],
        steps: [
          { title: "Create the teams", text: "Add the church's ministries and the roles in each, from vocals to car park. Pull people in from the database — no retyping." },
          { title: "Build the rota", text: "Put volunteers on the coming Sundays or copy last month's rota. The system flags clashes with other ministries." },
          { title: "Collect confirmations", text: "Volunteers get the rota in the bot and confirm. Whoever stays silent is visible to the leader, who sends a reminder." },
          { title: "Track attendance", text: "After the service the leader marks who was there. Workload and absences build up in each person's history." },
        ],
        audience: [
          { role: "pastor", text: "Sees every ministry in the church: how many people serve, where hands are short, which teams are overloaded." },
          { role: "leader", text: "Runs their own team: members, roles, a month's rota and confirmations — without chasing people in a chat." },
          { role: "volunteer", text: "Sees their rota on their phone, confirms with one tap or asks for cover." },
        ],
        faq: [
          { q: "Can one person be in several ministries?", a: "Yes. Someone can sing in worship and stand on the welcome team once a month. The system flags a clash if both fall on the same Sunday." },
          { q: "How do volunteers find out about the rota?", a: "Through the Telegram bot or the app: when the leader publishes the rota, everyone gets their dates and confirms. The bot chases anyone who hasn't." },
          { q: "What if a volunteer can't make it?", a: "They tap \"ask for cover\", the leader sees it on the rota and picks from the team's free people. The cover history is kept." },
          { q: "Can the worship leader see the kids' team?", a: "Not unless you grant that access. Each leader sees only their own teams; the pastor sees all of them." },
        ],
        mock: {
          kind: "table",
          title: "Team rota · Sun 21 April",
          subtitle: "6 ministries · 4 of 6 confirmed",
          columns: ["Volunteer", "Ministry", "Role"],
          rows: [
            { cells: ["Olena Kovalchuk", "Worship", "Vocals"], badge: { label: "Confirmed", tone: "green" } },
            { cells: ["Dmytro Lys", "Sound", "Desk"], badge: { label: "Pending", tone: "amber" } },
            { cells: ["Natalia Rud", "Kids", "Teacher 6–9"], badge: { label: "Confirmed", tone: "green" } },
            { cells: ["Vasyl Panchenko", "Welcome", "Door"], badge: { label: "Confirmed", tone: "green" } },
            { cells: ["Andrii Melnyk", "Worship", "Cajón"], badge: { label: "Needs cover", tone: "red" } },
            { cells: ["Iryna Shevchuk", "Café", "Barista"], badge: { label: "Confirmed", tone: "green" } },
          ],
        },
      },
    },
  },
  {
    id: "service-planning",
    group: "serving",
    related: ["ministries", "calendar", "templates", "knowledge"],
    copy: {
      ua: {
        seoTitle: "Планування служіння — модуль «Моя Церква»",
        seoDescription: "Порядок служіння з таймінгом, команда, матеріали до кожного блоку й підтвердження участі. План за шаблоном за 5 хвилин, нагадування служителям — самі.",
        title: "Порядок служіння, команда й таймінг — в одному плані",
        lead: "Модуль «Планування служіння» — це порядок, команда й матеріали кожного служіння в одному місці. Служителі бачать свої блоки, пастор — повну картину, і ніхто не питає «а о котрій я?».",
        highlights: [
          "Порядок служіння з таймінгом до хвилини",
          "Потреба на служіння: закриті й відкриті позиції",
          "Матеріали до кожного блоку",
          "Шаблони для регулярних служінь",
        ],
        features: [
          { icon: "ListChecks", title: "Порядок служіння", text: "Привітання, прославлення, оголошення, проповідь — блок за блоком, з відповідальним і тривалістю. Змінили порядок — усі бачать одразу." },
          { icon: "Timer", title: "Таймінг до хвилини", text: "Кожен блок має час початку й тривалість. Проповідь затягнулась на десять хвилин — план перерахує решту сам." },
          { icon: "UserCheck", title: "Потреба на служіння", text: "Скільки людей і на які позиції треба цього разу: двоє на звук, четверо на вокал, троє на зустріч гостей. Команда підтягується з графіка служінь, закриті позиції зелені, відкриті видно одразу." },
          { icon: "FileText", title: "Матеріали до блоку", text: "Ноти, слова пісень, слайди, текст оголошень — прикріплені до блоку. Служитель відкриває їх у телефоні, а не шукає в чаті." },
          { icon: "LayoutTemplate", title: "Шаблони служінь", text: "Недільне, молодіжне, молитовне — збережіть шаблон і наступного тижня заповніть лише імена та пісні." },
          { icon: "BellRing", title: "Нагадування самі", text: "За день до служіння бот нагадає кожному його роль і час, за годину — ще раз." },
        ],
        steps: [
          { title: "Оберіть шаблон", text: "Недільне служіння, молодіжне, молитовне — візьміть готовий шаблон або створіть свій з блоками й типовим таймінгом." },
          { title: "Заповніть блоки", text: "Призначте відповідальних, додайте пісні, текст оголошень і матеріали. План складається за п'ять хвилин, а не за вечір." },
          { title: "Опублікуйте команді", text: "Служителі отримують план у боті, підтверджують участь і бачать свої блоки. Пастор бачить, хто ще не відповів." },
          { title: "Проведіть за планом", text: "У неділю план відкритий у ведучого й звукорежисера. Після служіння він лишається в історії — разом з явкою команди." },
        ],
        audience: [
          { role: "pastor", text: "Бачить план кожного служіння наперед, коригує порядок і знає, що команда зібрана." },
          { role: "leader", text: "Складає порядок служіння за шаблоном, розставляє людей і збирає підтвердження без дзвінків." },
          { role: "volunteer", text: "Бачить свій блок, час виходу й матеріали в телефоні — і підтверджує участь одним натисканням." },
        ],
        faq: [
          { q: "Ми вже плануємо служіння в Google Документі. Навіщо змінювати?", a: "Документ не знає, хто підтвердив участь, і не нагадує служителям. У «Моїй Церкві» план пов'язаний з людьми: команда бачить свої блоки, підтверджує, отримує нагадування, а історія служінь накопичується сама." },
          { q: "Чи можна планувати кілька служінь на одну неділю?", a: "Так: ранкове й вечірнє або служіння на різних кемпусах — кожне зі своїм порядком і командою. Система попередить, якщо одна людина стоїть у двох планах одночасно." },
          { q: "Що бачить звукорежисер, а що ведучий?", a: "Один і той самий план, але кожен бачить підсвіченими свої блоки. Матеріали до блоку доступні всім, хто в команді цього служіння." },
          { q: "Чи можна змінити план у неділю вранці?", a: "Так. Змінили порядок або тривалість — оновлений план одразу в усіх на телефонах, а бот повідомить тих, кого зміна стосується." },
        ],
        mock: {
          kind: "timeline",
          title: "Недільне служіння",
          subtitle: "21 квітня · 10:00 · команда зібрана",
          items: [
            { time: "10:00", title: "Привітання", who: "Андрій Мельник", done: true },
            { time: "10:05", title: "Прославлення · 4 пісні", who: "Олена Ковальчук", done: true },
            { time: "10:35", title: "Оголошення", who: "Марія Іщенко" },
            { time: "10:45", title: "Проповідь", who: "Пастор Іван" },
            { time: "11:30", title: "Молитва і завершення", who: "Андрій Мельник" },
          ],
        },
        pipeline: {
          title: "Шлях плану служіння",
          text: "Приклад недільного служіння. Кожен етап — стан плану; перехід далі відкриває наступні дії.",
          stages: [
            { title: "Чернетка", tone: "neutral", text: "Ведучий бере шаблон недільного служіння — блоки й типовий таймінг уже на місці.", auto: "Підставляє дату, час початку й команду з графіка служінь." },
            { title: "Наповнення", tone: "brand", text: "До блоків додані пісні, текст оголошень, тема проповіді, ноти та слайди.", auto: "Перераховує час решти блоків, коли змінюється тривалість попереднього." },
            { title: "Опубліковано", tone: "amber", text: "План відкритий команді. Кожен бачить свої блоки й підтверджує участь.", auto: "Надсилає план у бот і показує ведучому, хто ще не відповів." },
            { title: "У неділю", tone: "violet", text: "План відкритий у ведучого та звукорежисера. Зміни в порядку видно всім одразу.", auto: "Нагадує кожному служителю за годину до його блоку." },
            { title: "В архіві", tone: "green", text: "Після служіння план лишається разом з явкою команди й матеріалами.", auto: "Записує пісні в історію, щоб було видно, коли їх співали востаннє." },
          ],
        },
        benefits: {
          title: "Що дає план служіння",
          text: "Приклад: церква з двома служіннями на тиждень і командою на 30 служителів. Порівнюємо з планом у документі й нагадуваннями в чаті.",
          items: [
            { value: "5 хв", label: "на план недільного служіння", text: "Шаблон уже має блоки, тривалість і потребу на служіння — лишається підставити пісні, тему проповіді та імена." },
            { value: "0", label: "питань «а о котрій я?»", text: "Кожен служитель бачить свій блок, час виходу й матеріали в боті. Питати нема про що." },
            { value: "94%", label: "підтверджень до суботи", text: "Запит іде одразу після публікації плану, нагадування — за день. Ведучий бачить, хто ще мовчить." },
            { value: "±2 хв", label: "відхилення від таймінгу", text: "Блоки перераховуються на ходу, тому служіння завершується тоді, коли на нього розраховують батьки з дітьми." },
          ],
        },
      },
      en: {
        seoTitle: "Service planning — MyChurch module",
        seoDescription: "Order of service with timing, the team, materials for every block and confirmations. A plan from a template in 5 minutes, reminders sent automatically.",
        title: "Order of service, team and timing in one plan",
        lead: "The Service Planning module is the running order, the team and the materials for every service in one place. Volunteers see their blocks, the pastor sees the whole picture — and nobody asks \"what time am I on?\".",
        highlights: [
          "Order of service timed to the minute",
          "Staffing needs: filled and open positions",
          "Materials attached to every block",
          "Templates for recurring services",
        ],
        features: [
          { icon: "ListChecks", title: "Order of service", text: "Welcome, worship, announcements, sermon — block by block, each with an owner and a duration. Change the order and everyone sees it at once." },
          { icon: "Timer", title: "Timed to the minute", text: "Every block has a start time and a duration. The sermon runs ten minutes over — the plan recalculates the rest itself." },
          { icon: "UserCheck", title: "Staffing needs", text: "How many people and which positions this service needs: two on sound, four on vocals, three on the door. The team comes in from the ministry rota, filled positions turn green and open ones stand out." },
          { icon: "FileText", title: "Materials on every block", text: "Sheet music, lyrics, slides, the announcement text — attached to the block. A volunteer opens them on their phone instead of digging through a chat." },
          { icon: "LayoutTemplate", title: "Service templates", text: "Sunday, youth, prayer meeting — save a template and next week fill in only the names and the songs." },
          { icon: "BellRing", title: "Reminders on their own", text: "A day before the service the bot reminds everyone of their role and time, and again an hour before." },
        ],
        steps: [
          { title: "Pick a template", text: "Sunday service, youth night, prayer meeting — take a ready template or build your own with blocks and typical timing." },
          { title: "Fill in the blocks", text: "Assign owners, add songs, the announcement text and materials. The plan takes five minutes, not an evening." },
          { title: "Publish to the team", text: "Volunteers get the plan in the bot, confirm and see their blocks. The pastor sees who hasn't answered yet." },
          { title: "Run it on Sunday", text: "The plan is open for the host and the sound engineer. Afterwards it stays in history, together with the team's attendance." },
        ],
        audience: [
          { role: "pastor", text: "Sees every service plan ahead of time, adjusts the order and knows the team is in place." },
          { role: "leader", text: "Builds the order of service from a template, places people and collects confirmations without phone calls." },
          { role: "volunteer", text: "Sees their block, their cue time and the materials on their phone — and confirms with one tap." },
        ],
        faq: [
          { q: "We already plan services in a Google Doc. Why change?", a: "A document doesn't know who has confirmed and doesn't remind anyone. In MyChurch the plan is linked to people: the team sees their blocks, confirms, gets reminders, and the history of services builds up on its own." },
          { q: "Can we plan several services on one Sunday?", a: "Yes: morning and evening, or services on different campuses — each with its own running order and team. The system warns if one person is in two plans at the same time." },
          { q: "What does the sound engineer see, and what does the host see?", a: "The same plan, but each sees their own blocks highlighted. Materials on a block are available to everyone on that service's team." },
          { q: "Can the plan change on Sunday morning?", a: "Yes. Change the order or a duration and the updated plan is on everyone's phone at once; the bot notifies the people the change affects." },
        ],
        mock: {
          kind: "timeline",
          title: "Sunday service",
          subtitle: "21 April · 10:00 · team confirmed",
          items: [
            { time: "10:00", title: "Welcome", who: "Andrii Melnyk", done: true },
            { time: "10:05", title: "Worship · 4 songs", who: "Olena Kovalchuk", done: true },
            { time: "10:35", title: "Announcements", who: "Maria Ishchenko" },
            { time: "10:45", title: "Sermon", who: "Pastor Ivan" },
            { time: "11:30", title: "Prayer and closing", who: "Andrii Melnyk" },
          ],
        },
        pipeline: {
          title: "A service plan's path",
          text: "Example of a Sunday service. Each stage is a state of the plan; moving on opens the next actions.",
          stages: [
            { title: "Draft", tone: "neutral", text: "The host takes the Sunday template — the blocks and the usual timing are already there.", auto: "Fills in the date, the start time and the team from the ministry rota." },
            { title: "Filling in", tone: "brand", text: "Songs, the announcement text, the sermon topic, sheet music and slides are added to the blocks.", auto: "Recalculates the remaining blocks whenever an earlier duration changes." },
            { title: "Published", tone: "amber", text: "The plan is open to the team. Everyone sees their blocks and confirms.", auto: "Sends the plan to the bot and shows the host who hasn't answered yet." },
            { title: "On Sunday", tone: "violet", text: "The plan is open for the host and the sound engineer. Changes in the order are visible to everyone at once.", auto: "Reminds each volunteer an hour before their block." },
            { title: "Archived", tone: "green", text: "After the service the plan stays, together with the team's attendance and the materials.", auto: "Logs the songs so you can see when each was last sung." },
          ],
        },
        benefits: {
          title: "What a real plan changes",
          text: "Example: a church with two services a week and a team of 30 volunteers. Compared with a plan in a document and reminders in a chat.",
          items: [
            { value: "5 min", label: "to plan a Sunday service", text: "The template already carries the blocks, the durations and the staffing needs — you add the songs, the sermon topic and the names." },
            { value: "0", label: "questions like what time am I on", text: "Every volunteer sees their block, their cue time and the materials in the bot. There is nothing left to ask." },
            { value: "94%", label: "confirmed by Saturday", text: "The request goes out as soon as the plan is published, the reminder a day later. The host sees who is still silent." },
            { value: "±2 min", label: "drift from the timing", text: "Blocks recalculate as you go, so the service ends when the parents with kids expect it to." },
          ],
        },
      },
    },
  },
  {
    id: "groups",
    group: "serving",
    related: ["people", "onboarding", "analytics", "telegram-bot"],
    copy: {
      ua: {
        seoTitle: "Малі групи — модуль «Моя Церква»",
        seoDescription: "Склад, лідери, розклад зустрічей і явка малих груп. Лідер відмічає з телефону, пастор бачить, які групи ростуть і хто пропустив три зустрічі поспіль.",
        title: "Кожна група живе далі — навіть коли лідер змінюється",
        lead: "Модуль «Малі групи» — це склад, лідери, розклад зустрічей і явка кожної групи в одному місці. Лідер відмічає з телефону, пастор бачить, які групи ростуть, а які згасають.",
        highlights: [
          "Склад, лідер і помічник кожної групи",
          "Явка за хвилину після зустрічі",
          "Хто пропустив три зустрічі — підсвічено",
          "Передача групи з усією історією",
        ],
        features: [
          { icon: "Users", title: "Склад і ролі", text: "Лідер, помічник, учасники, гості групи — хто є хто, видно одразу. Людина переходить в іншу групу — історія йде з нею." },
          { icon: "ClipboardCheck", title: "Явка за хвилину", text: "Після зустрічі лідер відмічає присутніх у телефоні. Явка потрапляє в картку людини й у звіт пастора без зведення таблиць." },
          { icon: "AlertTriangle", title: "Хто пропадає", text: "Три зустрічі поспіль без людини — вона підсвічена в лідера. Дзвінок робиться тоді, коли ще не пізно." },
          { icon: "MapPin", title: "Групи на карті", text: "Район, день, час, формат — новенький з Виноградаря отримує пропозицію групи поруч, а не «десь на Лівому березі»." },
          { icon: "MessageCircle", title: "Повідомлення групі", text: "Нагадування про зустріч, зміна місця, молитовна потреба — Telegram, Viber або SMS усій групі за два кліки." },
          { icon: "History", title: "Передача групи", text: "Лідер іде у відпустку чи передає групу — новий бачить склад, явку й нотатки з першого дня. Нічого не збирається заново." },
        ],
        steps: [
          { title: "Створіть групи", text: "Назва, лідер, помічник, район, день і час зустрічі. Учасників додайте з бази людей — по одному або цілим списком." },
          { title: "Відмічайте явку", text: "Лідер після кожної зустрічі відмічає присутніх з телефону. Хвилина — і дані в системі." },
          { title: "Реагуйте на сигнали", text: "Система підсвічує тих, хто пропускає, і групи, що не збирались місяць. Пастор і лідер бачать це раніше, ніж людина зникне." },
          { title: "Дивіться динаміку", text: "Які групи ростуть, які згасають, де потрібен ще один лідер — по місяцях, без таблиць." },
        ],
        audience: [
          { role: "pastor", text: "Бачить усі групи церкви: скільки людей у групах, яка явка, які групи ростуть і де лідеру потрібна допомога." },
          { role: "leader", text: "Веде свою групу: склад, зустрічі, явка й люди, яким треба подзвонити — без доступу до чужих груп." },
          { role: "member", text: "Бачить свою групу, лідера, наступну зустріч і отримує нагадування — без пошуків у чатах." },
        ],
        faq: [
          { q: "Чи бачить лідер групи дані інших груп?", a: "Ні. Лідер бачить лише свою групу: склад, явку, нотатки. Куратор напрямку або пастор бачать усі групи свого рівня." },
          { q: "Як лідер відмічає явку, якщо він не любить застосунки?", a: "Через Telegram-бот: після зустрічі бот надсилає список учасників, лідер натискає на тих, хто був. Це займає менше хвилини." },
          { q: "Що робити, коли група розростається і її треба ділити?", a: "Створіть нову групу й перенесіть частину учасників — їхня історія явки й нотатки переїдуть разом з ними. Стара група залишиться в архіві з повною історією." },
          { q: "Чи можна вести групи без явки, лише склад?", a: "Так. Явка — окрема функція, її можна ввімкнути пізніше, коли лідери звикнуть до системи. Склад і розклад працюють одразу." },
        ],
        mock: {
          kind: "list",
          title: "Малі групи",
          subtitle: "23 групи · 312 учасників · явка 84%",
          items: [
            { title: "Домашня група", sub: "Олена Ковальчук · чт, 19:00 · 18 осіб", meta: "92%", badge: { label: "Росте", tone: "green" } },
            { title: "Група «Центр»", sub: "Наталя Рудь · ср, 19:30 · 14 осіб", meta: "88%" },
            { title: "Молодіжна група", sub: "Дмитро Лис · сб, 17:00 · 24 особи", meta: "79%", badge: { label: "2 пропустили", tone: "amber" } },
            { title: "Група «Лівий берег»", sub: "Василь Панченко · вт, 19:00 · 11 осіб", meta: "61%", badge: { label: "Потребує уваги", tone: "red" } },
            { title: "Сімейна група №2", sub: "Андрій Мельник · пт, 19:00 · 16 осіб", meta: "90%" },
          ],
          footer: "Фільтр: усі · за районом · без лідера",
        },
      },
      en: {
        seoTitle: "Small groups — MyChurch module",
        seoDescription: "Members, leaders, meetings and attendance for small groups. Leaders mark attendance from a phone; the pastor sees which groups grow and who has stopped coming.",
        title: "Every group carries on, even when the leader changes",
        lead: "The Small Groups module holds the members, leaders, meeting schedule and attendance of every group in one place. The leader marks attendance from a phone; the pastor sees which groups are growing and which are fading.",
        highlights: [
          "Members, leader and assistant for every group",
          "Attendance a minute after the meeting",
          "Three missed meetings — highlighted",
          "Handover with the full history",
        ],
        features: [
          { icon: "Users", title: "Members and roles", text: "Leader, assistant, members, group guests — who is who is clear at once. Someone moves to another group and their history goes with them." },
          { icon: "ClipboardCheck", title: "Attendance in a minute", text: "After the meeting the leader ticks who was there on their phone. Attendance lands in the person's profile and the pastor's report — no spreadsheets to merge." },
          { icon: "AlertTriangle", title: "Who is drifting", text: "Three meetings in a row without someone and they're highlighted for the leader. The call happens while it still matters." },
          { icon: "MapPin", title: "Groups on a map", text: "District, day, time, format — a newcomer from Obolon is offered a group nearby, not \"somewhere on the Left Bank\"." },
          { icon: "MessageCircle", title: "Message the group", text: "A meeting reminder, a change of venue, a prayer request — Telegram, Viber or SMS to the whole group in two taps." },
          { icon: "History", title: "Group handover", text: "A leader goes on holiday or hands the group over — the new one sees members, attendance and notes from day one. Nothing is rebuilt from scratch." },
        ],
        steps: [
          { title: "Create the groups", text: "Name, leader, assistant, district, meeting day and time. Add members from the people database — one at a time or as a list." },
          { title: "Mark attendance", text: "After every meeting the leader ticks who was there from a phone. A minute, and the data is in." },
          { title: "Act on the signals", text: "The system highlights people who are missing and groups that haven't met for a month. Pastor and leader see it before the person disappears." },
          { title: "Watch the trend", text: "Which groups grow, which fade, where another leader is needed — month by month, without spreadsheets." },
        ],
        audience: [
          { role: "pastor", text: "Sees every group in the church: how many people are in groups, what attendance looks like, which groups grow and where a leader needs help." },
          { role: "leader", text: "Runs their own group: members, meetings, attendance and the people to call — with no access to other groups." },
          { role: "member", text: "Sees their group, the leader and the next meeting, and gets reminders — no digging through chats." },
        ],
        faq: [
          { q: "Can a group leader see other groups' data?", a: "No. A leader sees only their own group: members, attendance, notes. A coach or the pastor sees all the groups at their level." },
          { q: "How does a leader mark attendance if they don't like apps?", a: "Through the Telegram bot: after the meeting the bot sends the member list and the leader taps those who came. It takes under a minute." },
          { q: "What happens when a group outgrows itself and needs to split?", a: "Create a new group and move some of the members — their attendance history and notes move with them. The old group stays in the archive with its full history." },
          { q: "Can we run groups without attendance, just the members?", a: "Yes. Attendance is a separate feature you can switch on later, once leaders are used to the system. Members and the schedule work from day one." },
        ],
        mock: {
          kind: "list",
          title: "Small groups",
          subtitle: "23 groups · 312 members · 84% attendance",
          items: [
            { title: "Obolon group", sub: "Olena Kovalchuk · Thu 19:00 · 18 people", meta: "92%", badge: { label: "Growing", tone: "green" } },
            { title: "Centre group", sub: "Natalia Rud · Wed 19:30 · 14 people", meta: "88%" },
            { title: "Youth group", sub: "Dmytro Lys · Sat 17:00 · 24 people", meta: "79%", badge: { label: "2 missed", tone: "amber" } },
            { title: "Left Bank group", sub: "Vasyl Panchenko · Tue 19:00 · 11 people", meta: "61%", badge: { label: "Needs attention", tone: "red" } },
            { title: "Family group #2", sub: "Andrii Melnyk · Fri 19:00 · 16 people", meta: "90%" },
          ],
          footer: "Filter: all · by district · no leader",
        },
      },
    },
  },
  {
    id: "learning",
    group: "serving",
    related: ["onboarding", "knowledge", "people", "ministries"],
    copy: {
      ua: {
        seoTitle: "Навчання — модуль «Моя Церква»",
        seoDescription: "Курси, потоки, уроки, явка, домашні завдання й сертифікати. Прогрес кожного учасника видно в його картці — від Альфа-курсу до Школи лідерів.",
        title: "Навчання в церкві, де видно прогрес кожного",
        lead: "Модуль «Навчання» — це Альфа-курс, Основи віри, Школа лідерів і будь-які інші курси церкви: потоки, уроки, явка, домашні завдання й сертифікати. Ви бачите, хто дійшов до кінця, а хто застряг на третьому уроці.",
        highlights: [
          "Курси з уроками, потоками й розкладом",
          "Прогрес кожного учасника",
          "Явка на заняттях і домашні завдання",
          "Сертифікати після завершення",
        ],
        features: [
          { icon: "GraduationCap", title: "Курси й потоки", text: "Один курс — багато потоків: весняний Альфа-курс, осінній, потік для молоді. У кожного свій розклад, викладач і група учасників." },
          { icon: "BookOpen", title: "Уроки й матеріали", text: "Тема, конспект, відео, домашнє завдання до кожного уроку. Учасник відкриває матеріали в телефоні, викладач — план заняття." },
          { icon: "TrendingUp", title: "Прогрес кожного", text: "8 з 10 уроків, домашнє здано, тест пройдено — прогрес видно в картці людини й у списку потоку. Хто відстає — підсвічено." },
          { icon: "ClipboardCheck", title: "Явка на заняттях", text: "Викладач відмічає присутніх після уроку. Пропустив два заняття поспіль — куратор бачить і пише людині." },
          { icon: "Award", title: "Сертифікати", text: "Завершив курс — сертифікат формується сам за шаблоном церкви й додається в історію людини. Для Школи лідерів це ще й підстава для нової ролі." },
          { icon: "Route", title: "Навчальні шляхи", text: "Альфа-курс → Основи віри → Школа служіння. Система підказує людині наступний крок і запрошує на найближчий потік." },
        ],
        steps: [
          { title: "Створіть курс", text: "Назва, уроки, матеріали, домашні завдання — один раз. Далі кожен потік запускається з готової структури." },
          { title: "Запустіть потік", text: "Дати, викладач, місце. Учасники реєструються через форму або їх додає куратор з бази людей." },
          { title: "Ведіть заняття", text: "Викладач відмічає явку й перевіряє домашні. Учасники бачать свій прогрес і наступний урок у боті." },
          { title: "Випускайте", text: "Хто завершив — отримує сертифікат, а в картці з'являється відмітка. Куратор бачить, кого запросити на наступний курс." },
        ],
        audience: [
          { role: "pastor", text: "Бачить, скільки людей проходять курси, який відсоток доходить до кінця і хто готовий до служіння чи лідерства." },
          { role: "leader", text: "Веде свій потік: розклад, явка, домашні, прогрес учасників — і знає, кому написати, поки людина не зникла." },
          { role: "volunteer", text: "Бачить свої курси, наступний урок і матеріали в телефоні; здає домашнє й отримує сертифікат." },
          { role: "hr", text: "Планує навчання команди: обов'язкові курси для нових служителів, Школа лідерів, хто що пройшов." },
        ],
        faq: [
          { q: "Чи підходить модуль для Альфа-курсу?", a: "Так, це один з типових сценаріїв: 10–12 зустрічей, потік навесні й восени, реєстрація гостей через форму, явка на кожній зустрічі й запрошення в групу після завершення." },
          { q: "Чи можна вести курс онлайн?", a: "Матеріали, відео й домашні завдання доступні учасникам у застосунку та боті. Заняття можна проводити де завгодно — система веде облік, а не транслює відео." },
          { q: "Що бачить учасник курсу?", a: "Свій потік: розклад, пройдені й наступні уроки, матеріали, домашні завдання та прогрес. Дані інших учасників він не бачить." },
          { q: "Чи пов'язане навчання з картками людей?", a: "Так. Кожен пройдений курс, явка й сертифікат записуються в історію людини. Пастор відкриває картку й бачить: Альфа-курс завершила, Школа лідерів — 6 з 10 уроків." },
        ],
        mock: {
          kind: "stats",
          title: "Навчання",
          subtitle: "Весняний семестр · 5 потоків",
          kpis: [
            { label: "Учасників", value: "86", trend: "+14 за місяць" },
            { label: "Дійшли до кінця", value: "74%", trend: "+6% до осені" },
            { label: "Сертифікатів", value: "39" },
          ],
          barsTitle: "Прогрес потоків",
          bars: [
            { label: "Альфа-курс", value: 80 },
            { label: "Основи віри", value: 70 },
            { label: "Школа лідерів", value: 60 },
            { label: "Школа служіння", value: 50 },
            { label: "Хрещення", value: 90 },
            { label: "Шлюб і сім'я", value: 40 },
            { label: "Вчителі дітей", value: 65 },
          ],
        },
        pipeline: {
          title: "Шлях учасника курсу",
          text: "Приклад весняного Альфа-курсу. Етапи однакові для будь-якого курсу церкви.",
          stages: [
            { title: "Запис", tone: "neutral", text: "Людина залишила заявку через форму чи бот, або її додав куратор із бази церкви.", auto: "Підтверджує місце в потоці й надсилає дати, адресу та ім'я викладача." },
            { title: "Навчається", tone: "brand", text: "Учасник ходить на заняття, відкриває матеріали в телефоні й здає домашні.", auto: "Нагадує про заняття напередодні й оновлює прогрес після кожного уроку." },
            { title: "Відстає", tone: "amber", text: "Дві пропущені зустрічі поспіль або нездане домашнє. Куратор бачить це в списку потоку.", auto: "Ставить куратору задачу «зв'язатися» і надсилає учаснику матеріали пропущеного уроку." },
            { title: "Завершив", tone: "green", text: "Усі уроки пройдені, домашні здані — викладач закриває потік.", auto: "Формує сертифікат за шаблоном церкви й додає курс в історію людини." },
            { title: "Наступний крок", tone: "violet", text: "Після Альфа-курсу — Основи віри, мала група або служіння. Куратор бачить, кого куди запросити.", auto: "Пропонує людині найближчий потік наступного курсу її навчального шляху." },
          ],
        },
      },
      en: {
        seoTitle: "Learning — MyChurch module",
        seoDescription: "Courses, cohorts, lessons, attendance, homework and certificates. Every participant's progress shows in their profile, from Alpha to the leaders' school.",
        title: "Church learning where everyone's progress is visible",
        lead: "The Learning module runs the Alpha course, Foundations of Faith, the leaders' school and any other church course: cohorts, lessons, attendance, homework and certificates. You see who reached the end and who got stuck on lesson three.",
        highlights: [
          "Courses with lessons, cohorts and a schedule",
          "Progress for every participant",
          "Attendance and homework",
          "Certificates on completion",
        ],
        features: [
          { icon: "GraduationCap", title: "Courses and cohorts", text: "One course, many cohorts: a spring Alpha, an autumn one, a youth cohort. Each has its own schedule, teacher and participants." },
          { icon: "BookOpen", title: "Lessons and materials", text: "Topic, notes, video, homework for every lesson. A participant opens the materials on their phone, the teacher opens the lesson plan." },
          { icon: "TrendingUp", title: "Everyone's progress", text: "8 of 10 lessons, homework handed in, test passed — progress shows in the person's profile and in the cohort list. Anyone falling behind is highlighted." },
          { icon: "ClipboardCheck", title: "Class attendance", text: "The teacher ticks who was there after the lesson. Two classes missed in a row — the coordinator sees it and writes to the person." },
          { icon: "Award", title: "Certificates", text: "Finish the course and a certificate is generated from the church's template and added to the person's history. For the leaders' school it is also the basis for a new role." },
          { icon: "Route", title: "Learning paths", text: "Alpha → Foundations of Faith → School of Ministry. The system suggests the next step and invites the person to the nearest cohort." },
        ],
        steps: [
          { title: "Create the course", text: "Name, lessons, materials, homework — once. Every cohort after that starts from the ready structure." },
          { title: "Launch a cohort", text: "Dates, teacher, venue. Participants sign up through a form or the coordinator adds them from the people database." },
          { title: "Run the classes", text: "The teacher marks attendance and checks homework. Participants see their progress and the next lesson in the bot." },
          { title: "Graduate them", text: "Whoever finishes gets a certificate and a mark in their profile. The coordinator sees who to invite to the next course." },
        ],
        audience: [
          { role: "pastor", text: "Sees how many people are on courses, what share reaches the end and who is ready for ministry or leadership." },
          { role: "leader", text: "Runs their cohort: schedule, attendance, homework, participants' progress — and knows who to message before they drop out." },
          { role: "volunteer", text: "Sees their courses, the next lesson and materials on their phone; hands in homework and receives a certificate." },
          { role: "hr", text: "Plans the team's training: required courses for new volunteers, the leaders' school, who has completed what." },
        ],
        faq: [
          { q: "Does the module suit the Alpha course?", a: "Yes, it's one of the typical cases: 10–12 sessions, a spring and an autumn cohort, guest sign-up through a form, attendance at every session and a group invitation on completion." },
          { q: "Can a course run online?", a: "Materials, video and homework are available to participants in the app and the bot. Classes can happen anywhere — the system keeps the records, it doesn't stream video." },
          { q: "What does a participant see?", a: "Their cohort: the schedule, completed and upcoming lessons, materials, homework and progress. They don't see other participants' data." },
          { q: "Is learning linked to people's profiles?", a: "Yes. Every completed course, attendance record and certificate is written into the person's history. The pastor opens a profile and sees: Alpha completed, leaders' school 6 of 10 lessons." },
        ],
        mock: {
          kind: "stats",
          title: "Learning",
          subtitle: "Spring term · 5 cohorts",
          kpis: [
            { label: "Participants", value: "86", trend: "+14 this month" },
            { label: "Reached the end", value: "74%", trend: "+6% vs autumn" },
            { label: "Certificates", value: "39" },
          ],
          barsTitle: "Cohort progress",
          bars: [
            { label: "Alpha course", value: 80 },
            { label: "Foundations", value: 70 },
            { label: "Leaders' school", value: 60 },
            { label: "School of Ministry", value: 50 },
            { label: "Baptism", value: 90 },
            { label: "Marriage & family", value: 40 },
            { label: "Kids' teachers", value: 65 },
          ],
        },
        pipeline: {
          title: "A participant's path through a course",
          text: "Example of the spring Alpha course. The stages are the same for any course the church runs.",
          stages: [
            { title: "Signed up", tone: "neutral", text: "The person applied through a form or the bot, or the coordinator added them from the church database.", auto: "Confirms their place in the cohort and sends the dates, the venue and the teacher's name." },
            { title: "Studying", tone: "brand", text: "The participant comes to the classes, opens the materials on their phone and hands in homework.", auto: "Reminds about the class the day before and updates progress after every lesson." },
            { title: "Falling behind", tone: "amber", text: "Two sessions missed in a row, or homework not handed in. The coordinator sees it in the cohort list.", auto: "Creates a \"get in touch\" task for the coordinator and sends the missed lesson's materials." },
            { title: "Completed", tone: "green", text: "All lessons done and homework handed in — the teacher closes the cohort.", auto: "Generates the certificate from the church template and adds the course to the person's history." },
            { title: "Next step", tone: "violet", text: "After Alpha come Foundations of Faith, a small group or ministry. The coordinator sees who to invite where.", auto: "Offers the person the nearest cohort of the next course on their learning path." },
          ],
        },
      },
    },
  },
  {
    id: "onboarding",
    group: "people",
    related: ["people", "forms", "automations", "groups"],
    copy: {
      ua: {
        seoTitle: "Онбординг — модуль «Моя Церква»",
        seoDescription: "Шлях новенького від анкети на вході до членства: кроки, відповідальна людина, автоматичні привітання й нагадування. Хто застряг на кроці — підсвічено.",
        title: "Жоден новенький не загубиться після першої неділі",
        lead: "Модуль «Онбординг» перетворює першу неділю на шлях: анкета на вході, привітання того ж дня, відповідальна людина, запрошення в групу й на курс. Кожен крок видно, кожен пропущений крок — підсвічено.",
        highlights: [
          "Анкета за 30 секунд через QR або форму",
          "Відповідальна людина за кожним новеньким",
          "Кроки шляху під вашу церкву",
          "Автоматичні привітання й нагадування",
        ],
        features: [
          { icon: "QrCode", title: "Реєстрація за 30 секунд", text: "QR-код на вході або коротка форма на рецепції — ім'я, телефон, як дізнались про церкву. Картка людини створюється одразу зі статусом «гість»." },
          { icon: "Kanban", title: "Кроки шляху", text: "Перший візит → дзвінок → знайомство з пастором → група → Альфа-курс → членство. Кроки й порядок налаштовуєте під вашу церкву." },
          { icon: "UserCheck", title: "Відповідальна людина", text: "Кожен новенький отримує людину, яка його супроводжує: дзвонить, запрошує, знайомить. Хто за кого відповідає — видно пастору." },
          { icon: "Zap", title: "Автоматичні дотики", text: "Привітання в Telegram того ж дня, нагадування відповідальному через три дні, запрошення на найближчий Альфа-курс — за сценарієм, без ручної роботи." },
          { icon: "Flag", title: "Хто застряг", text: "Новенький два тижні на одному кроці або не прийшов удруге — підсвічений у пастора й у відповідального. Дзвінок робиться вчасно." },
          { icon: "Milestone", title: "Від гостя до члена церкви", text: "Пройшов усі кроки — статус змінюється на «член церкви» сам, а шлях лишається в історії людини." },
        ],
        steps: [
          { title: "Опишіть шлях", text: "Які кроки проходить новенький у вашій церкві й хто за кожен відповідає. Візьміть типовий шлях і підправте під себе." },
          { title: "Поставте QR на вході", text: "Роздрукуйте код або дайте форму рецепції. Кожен гість потрапляє в систему в неділю, а не в понеділок із записника." },
          { title: "Призначайте відповідальних", text: "Новенький з'явився — пастор або рецепція призначає людину, яка його поведе. Бот нагадує їй про наступний крок." },
          { title: "Дивіться воронку", text: "Скільки гостей за місяць, скільки дійшли до групи, де люди зникають. Онбординг стає процесом, а не випадковістю." },
        ],
        audience: [
          { role: "pastor", text: "Бачить усіх новеньких за місяць, на якому вони кроці й хто з них зник після першого візиту." },
          { role: "leader", text: "Отримує новеньких зі свого району в групу — з контактом, історією й нотатками від відповідального." },
          { role: "visitor", text: "Залишає контакт за 30 секунд і далі отримує привітання, запрошення й знайомство — від людей, а не від системи." },
          { role: "reception", text: "Реєструє гостя в неділю за секунди і бачить, кого з новеньких ще ніхто не взяв під опіку." },
        ],
        faq: [
          { q: "Скільки кроків має бути в онбордингу?", a: "Зазвичай 4–6: анкета, дзвінок, знайомство з пастором, група, курс, членство. Менше — і люди губляться, більше — і кроки не виконуються. Почніть з типового шляху й підправте за місяць." },
          { q: "А якщо новенький не хоче в групу?", a: "Відповідальний відмічає це в картці, і людина не отримує повторних запрошень. Шлях можна поставити на паузу й повернутись до нього через місяць." },
          { q: "Хто призначає відповідального?", a: "Пастор, рецепція або система автоматично — за районом чи віком новенького. Наприклад, гості з Виноградаря йдуть до лідера домашньої групи свого району." },
          { q: "Чи працює це без Telegram?", a: "Так. Привітання й нагадування можуть іти через SMS або Viber, а відповідальний бачить свої задачі в застосунку. Telegram лише робить це зручнішим." },
        ],
        mock: {
          kind: "board",
          title: "Онбординг",
          subtitle: "12 новеньких за місяць · 3 без руху",
          columns: [
            {
              title: "Перший візит",
              cards: [
                { title: "Марія Іщенко", sub: "Неділя · відп. Олена К.", tag: { label: "Привітання ✓", tone: "green" } },
                { title: "Ігор Ткаченко", sub: "2 дні · без відповідального", tag: { label: "Призначити", tone: "amber" } },
              ],
            },
            {
              title: "Знайомство",
              cards: [
                { title: "Дмитро Лис", sub: "Дзвінок ✓ · зустріч з пастором", tag: { label: "Крок 3 з 5", tone: "brand" } },
                { title: "Ірина Шевчук", sub: "9 днів без руху", tag: { label: "Застрягла", tone: "red" } },
              ],
            },
            {
              title: "У групі",
              cards: [
                { title: "Тетяна Бондар", sub: "Домашня група · 3 зустрічі", tag: { label: "Членство", tone: "green" } },
                { title: "Роман Гнатюк", sub: "Група «Центр» · Альфа-курс", tag: { label: "Крок 4 з 5", tone: "brand" } },
              ],
            },
          ],
        },
        pipeline: {
          title: "Шлях новенького по дошці",
          text: "Типовий шлях від першої неділі до членства. Кроки й терміни налаштовуються під вашу церкву.",
          stages: [
            { title: "Перший візит", tone: "neutral", text: "Гість сканує QR на вході й залишає ім'я, телефон і як дізнався про церкву.", auto: "Створює картку зі статусом «гість» і надсилає привітання в Telegram того ж дня." },
            { title: "Знайомство", tone: "brand", text: "Відповідальний дзвонить протягом трьох днів і знайомить гостя з пастором після служіння.", auto: "Ставить задачу відповідальному й нагадує йому, якщо дзвінка не було." },
            { title: "Без руху", tone: "amber", text: "Два тижні на тому самому кроці або людина не прийшла вдруге.", auto: "Підсвічує картку в пастора й пропонує змінити відповідального." },
            { title: "У групі", tone: "violet", text: "Новенький ходить у малу групу свого району й записаний на Альфа-курс.", auto: "Передає лідеру групи контакт і нотатки відповідального." },
            { title: "Член церкви", tone: "green", text: "Пройдені всі кроки: група, курс і розмова з пастором.", auto: "Змінює статус на «член церкви», а весь шлях лишається в історії людини." },
          ],
        },
      },
      en: {
        seoTitle: "Onboarding — MyChurch module",
        seoDescription: "A newcomer's path from the form at the door to membership: steps, a named person, automatic welcomes and reminders. Anyone who gets stuck is highlighted.",
        title: "No newcomer gets lost after their first Sunday",
        lead: "The Onboarding module turns a first Sunday into a path: a form at the door, a welcome the same day, a named person, an invitation to a group and a course. Every step is visible, every missed step is highlighted.",
        highlights: [
          "A 30-second sign-up via QR or form",
          "A named person for every newcomer",
          "Steps tailored to your church",
          "Automatic welcomes and reminders",
        ],
        features: [
          { icon: "QrCode", title: "Sign-up in 30 seconds", text: "A QR code at the door or a short form at reception — name, phone, how they heard about the church. The profile is created at once with the status \"guest\"." },
          { icon: "Kanban", title: "Steps of the path", text: "First visit → call → meeting the pastor → group → Alpha → membership. You set the steps and their order for your church." },
          { icon: "UserCheck", title: "A named person", text: "Every newcomer gets someone who walks with them: calls, invites, introduces. Who is responsible for whom is visible to the pastor." },
          { icon: "Zap", title: "Automatic touches", text: "A Telegram welcome the same day, a nudge to the responsible person after three days, an invitation to the nearest Alpha — by scenario, no manual work." },
          { icon: "Flag", title: "Who got stuck", text: "A newcomer two weeks on the same step, or who didn't come a second time — highlighted for the pastor and the responsible person. The call happens in time." },
          { icon: "Milestone", title: "From guest to member", text: "All steps completed — the status changes to \"member\" by itself, and the path stays in the person's history." },
        ],
        steps: [
          { title: "Describe the path", text: "Which steps a newcomer goes through in your church and who owns each one. Take the typical path and adjust it." },
          { title: "Put a QR at the door", text: "Print the code or give reception the form. Every guest is in the system on Sunday, not on Monday from a notebook." },
          { title: "Assign responsible people", text: "A newcomer appears — the pastor or reception assigns someone to walk with them. The bot reminds that person about the next step." },
          { title: "Watch the funnel", text: "How many guests this month, how many reached a group, where people drop off. Onboarding becomes a process, not luck." },
        ],
        audience: [
          { role: "pastor", text: "Sees every newcomer of the month, which step they are on and who disappeared after the first visit." },
          { role: "leader", text: "Receives newcomers from their district into the group — with a contact, history and notes from the responsible person." },
          { role: "visitor", text: "Leaves a contact in 30 seconds and then gets a welcome, invitations and introductions — from people, not from a system." },
          { role: "reception", text: "Registers a guest on Sunday in seconds and sees which newcomers nobody has taken on yet." },
        ],
        faq: [
          { q: "How many steps should onboarding have?", a: "Usually 4–6: form, call, meeting the pastor, group, course, membership. Fewer and people get lost; more and the steps don't get done. Start with the typical path and adjust after a month." },
          { q: "What if a newcomer doesn't want a group?", a: "The responsible person notes it in the profile and the person stops getting repeated invitations. The path can be paused and picked up again a month later." },
          { q: "Who assigns the responsible person?", a: "The pastor, reception, or the system automatically — by the newcomer's district or age. For example, guests from Obolon go to the Obolon group leader." },
          { q: "Does it work without Telegram?", a: "Yes. Welcomes and reminders can go by SMS or Viber, and the responsible person sees their tasks in the app. Telegram just makes it more convenient." },
        ],
        mock: {
          kind: "board",
          title: "Onboarding",
          subtitle: "12 newcomers this month · 3 stuck",
          columns: [
            {
              title: "First visit",
              cards: [
                { title: "Maria Ishchenko", sub: "Sunday · owner Olena K.", tag: { label: "Welcomed", tone: "green" } },
                { title: "Ihor Tkachenko", sub: "2 days · no owner yet", tag: { label: "Assign", tone: "amber" } },
              ],
            },
            {
              title: "Getting to know",
              cards: [
                { title: "Dmytro Lys", sub: "Called ✓ · meeting the pastor", tag: { label: "Step 3 of 5", tone: "brand" } },
                { title: "Iryna Shevchuk", sub: "9 days with no movement", tag: { label: "Stuck", tone: "red" } },
              ],
            },
            {
              title: "In a group",
              cards: [
                { title: "Tetiana Bondar", sub: "Obolon group · 3 meetings", tag: { label: "Membership", tone: "green" } },
                { title: "Roman Hnatiuk", sub: "Centre group · Alpha course", tag: { label: "Step 4 of 5", tone: "brand" } },
              ],
            },
          ],
        },
        pipeline: {
          title: "A newcomer's path across the board",
          text: "The typical path from a first Sunday to membership. Steps and deadlines are set up for your church.",
          stages: [
            { title: "First visit", tone: "neutral", text: "The guest scans the QR at the door and leaves a name, a phone number and how they heard about the church.", auto: "Creates a profile with the status \"guest\" and sends a Telegram welcome the same day." },
            { title: "Getting to know", tone: "brand", text: "The responsible person calls within three days and introduces the guest to the pastor after a service.", auto: "Creates the task for the responsible person and nudges them if the call hasn't happened." },
            { title: "No movement", tone: "amber", text: "Two weeks on the same step, or the person didn't come a second time.", auto: "Highlights the card for the pastor and suggests handing it to someone else." },
            { title: "In a group", tone: "violet", text: "The newcomer attends the small group in their district and is signed up for Alpha.", auto: "Passes the contact and the responsible person's notes to the group leader." },
            { title: "Member", tone: "green", text: "Every step is done: the group, the course and the conversation with the pastor.", auto: "Changes the status to \"member\", and the whole path stays in the person's history." },
          ],
        },
      },
    },
  },
  {
    id: "camps",
    group: "serving",
    related: ["events", "forms", "accounting", "family"],
    copy: {
      ua: {
        seoTitle: "Табори — модуль «Моя Церква»",
        seoDescription: "Реєстрація учасників, оплати, кімнати й загони, команда вожатих, розклад по днях і медичні дані — дитячий чи молодіжний табір в одному місці.",
        title: "Табір без хаосу — від реєстрації до заїзду",
        lead: "Модуль «Табори» збирає все, що потрібно для дитячого, підліткового чи молодіжного табору: реєстрацію учасників, згоди батьків, оплати, розподіл по кімнатах і загонах, команду вожатих і розклад по днях.",
        highlights: [
          "Реєстрація через форму або бот",
          "Хто сплатив, хто ще ні — видно одразу",
          "Кімнати, загони й команда вожатих",
          "Розклад табору по днях і відповідальні",
        ],
        features: [
          { icon: "Ticket", title: "Реєстрація учасників", text: "Форма або бот: ім'я, вік, контакт батьків, побажання щодо кімнати. Заявка одразу в списку табору, а людина — в базі церкви." },
          { icon: "Wallet", title: "Оплати й внески", text: "Хто сплатив повністю, хто частково, кому церква дала стипендію — статус біля кожного учасника. Бухгалтер бачить підсумок без окремої таблиці." },
          { icon: "Bed", title: "Кімнати та загони", text: "Розселіть учасників по кімнатах і загонах за віком, статтю чи побажаннями — перетягуванням. Список на двері кожної кімнати друкується одним кліком." },
          { icon: "Users", title: "Команда табору", text: "Вожаті, кухня, медик, водії — команда з ролями та зонами відповідальності. Кожен бачить свій загін і свої задачі." },
          { icon: "CalendarDays", title: "Розклад по днях", text: "Підйом, сніданок, тематичні блоки, вечірня програма — план кожного дня з відповідальним. Змінили час — команда бачить у боті." },
          { icon: "ShieldCheck", title: "Безпека й здоров'я", text: "Алергії, ліки, згоди батьків, екстрений контакт — у картці учасника, доступні медику й керівнику табору, а не всім." },
        ],
        steps: [
          { title: "Створіть табір", text: "Дати, місце, вікові групи, кількість місць. Форма реєстрації генерується сама — залишиться поділитись посиланням чи QR-кодом." },
          { title: "Збирайте заявки", text: "Батьки або учасники реєструються з телефону. Ви бачите список, оплати й вільні місця в реальному часі." },
          { title: "Розселіть і призначте команду", text: "Кімнати, загони, вожаті, розклад — усе в одному робочому просторі табору." },
          { title: "Проведіть і підсумуйте", text: "Відмітка приходу на заїзді, зміни в розкладі через бот, а після табору — учасники в історії людей і звіт по оплатах." },
        ],
        audience: [
          { role: "pastor", text: "Бачить табір цілком: скільки зареєстровано, скільки сплатили, чи зібрана команда — без дзвінків організатору." },
          { role: "leader", text: "Організовує табір: заявки, кімнати, загони, вожаті, розклад — в одному місці замість чатів і таблиць." },
          { role: "member", text: "Реєструє себе або дитину за кілька хвилин з телефону, бачить статус заявки й отримує нагадування перед заїздом." },
          { role: "accountant", text: "Бачить оплати по кожному учаснику й підсумок табору — узгоджено з бухгалтерією церкви." },
        ],
        faq: [
          { q: "Чи можуть батьки зареєструвати кількох дітей одразу?", a: "Так. Батьки заповнюють одну форму на всю сім'ю, а діти з модуля «Сім'я» підтягуються самі — залишається обрати, хто їде." },
          { q: "Як облікувати часткові оплати й знижки?", a: "Біля кожного учасника є статус оплати: повна, часткова, стипендія церкви. Суми та дати фіксуються, підсумок по табору видно бухгалтеру." },
          { q: "Чи можна повторити табір наступного року?", a: "Так. Скопіюйте минулорічний табір — структура, розклад, ролі команди й форма реєстрації перенесуться. Оновіть дати й відкривайте реєстрацію." },
          { q: "Що з даними про здоров'я дітей?", a: "Алергії, ліки та згоди батьків бачать лише керівник табору й медик. Після табору доступ можна закрити, а дані лишаються в архіві заїзду." },
        ],
        mock: {
          kind: "form",
          title: "Реєстрація на табір",
          subtitle: "Молодіжний табір · 14–20 липня · Карпати",
          fields: [
            { label: "Учасник", value: "Софія Мельник", type: "text" },
            { label: "Заїзд", value: "Молодіжний · 14–20 липня", type: "select" },
            { label: "Дата народження", value: "12.03.2008", type: "date" },
            { label: "Кімната з", value: "Тетяна Бондар", type: "text" },
            { label: "Алергії та ліки", value: "Немає", type: "textarea" },
            { label: "Згода батьків отримана", type: "check" },
          ],
          submit: "Зареєструвати",
        },
      },
      en: {
        seoTitle: "Camps — MyChurch module",
        seoDescription: "Participant registration, payments, rooms and squads, the leaders' team, a day-by-day schedule and medical details: a kids' or youth camp in one place.",
        title: "A camp without chaos, from sign-up to arrival",
        lead: "The Camps module holds everything a kids', teen or youth camp needs: participant registration, parental consent, payments, rooms and squads, the leaders' team and a day-by-day schedule.",
        highlights: [
          "Sign-up through a form or the bot",
          "Who has paid and who hasn't — at a glance",
          "Rooms, squads and the leaders' team",
          "Day-by-day schedule with owners",
        ],
        features: [
          { icon: "Ticket", title: "Participant registration", text: "A form or the bot: name, age, parents' contact, room preferences. The application lands in the camp list at once, and the person in the church database." },
          { icon: "Wallet", title: "Payments and fees", text: "Paid in full, paid in part, given a church bursary — a status next to every participant. The accountant sees the total without a separate spreadsheet." },
          { icon: "Bed", title: "Rooms and squads", text: "Place participants into rooms and squads by age, gender or preference — by dragging. The list for every room door prints in one click." },
          { icon: "Users", title: "Camp team", text: "Leaders, kitchen, medic, drivers — a team with roles and areas of responsibility. Everyone sees their squad and their tasks." },
          { icon: "CalendarDays", title: "Day-by-day schedule", text: "Wake-up, breakfast, themed sessions, evening programme — each day's plan with an owner. Change a time and the team sees it in the bot." },
          { icon: "ShieldCheck", title: "Safety and health", text: "Allergies, medication, parental consent, emergency contact — in the participant's record, visible to the medic and the camp director, not to everyone." },
        ],
        steps: [
          { title: "Create the camp", text: "Dates, venue, age groups, number of places. The registration form is generated for you — share the link or a QR code." },
          { title: "Collect applications", text: "Parents or participants register from a phone. You see the list, payments and free places in real time." },
          { title: "Place people and assign the team", text: "Rooms, squads, leaders, schedule — all in one camp workspace." },
          { title: "Run it and wrap up", text: "Check-in on arrival, schedule changes through the bot, and afterwards participants in people's histories and a payments report." },
        ],
        audience: [
          { role: "pastor", text: "Sees the whole camp: how many registered, how many paid, whether the team is in place — without calling the organiser." },
          { role: "leader", text: "Organises the camp: applications, rooms, squads, leaders, schedule — in one place instead of chats and spreadsheets." },
          { role: "member", text: "Registers themselves or a child in a few minutes from a phone, sees the application status and gets a reminder before departure." },
          { role: "accountant", text: "Sees payments for every participant and the camp total — reconciled with the church's accounts." },
        ],
        faq: [
          { q: "Can parents register several children at once?", a: "Yes. Parents fill in one form for the whole family, and the children come in from the Family module — they just tick who is going." },
          { q: "How do we record part payments and discounts?", a: "Every participant has a payment status: full, partial, church bursary. Amounts and dates are recorded and the camp total is visible to the accountant." },
          { q: "Can we repeat the camp next year?", a: "Yes. Copy last year's camp — the structure, schedule, team roles and registration form carry over. Update the dates and open registration." },
          { q: "What about children's health data?", a: "Allergies, medication and parental consent are visible only to the camp director and the medic. After the camp the access can be closed, and the data stays in the camp's archive." },
        ],
        mock: {
          kind: "form",
          title: "Camp registration",
          subtitle: "Youth camp · 14–20 July · Carpathians",
          fields: [
            { label: "Participant", value: "Sofia Melnyk", type: "text" },
            { label: "Session", value: "Youth · 14–20 July", type: "select" },
            { label: "Date of birth", value: "12.03.2008", type: "date" },
            { label: "Room with", value: "Tetiana Bondar", type: "text" },
            { label: "Allergies and medication", value: "None", type: "textarea" },
            { label: "Parental consent received", type: "check" },
          ],
          submit: "Register",
        },
      },
    },
  },
];
