import type { ModuleDetail } from "./types";

/* Group "ai": assistant */
export const aiModules: ModuleDetail[] = [
  {
    id: "assistant",
    group: "ai",
    related: ["analytics", "people", "automations", "telegram-bot"],
    copy: {
      ua: {
        seoTitle: "ШІ-асистенти — модуль «Моя Церква»",
        seoDescription: "ШІ-асистент «Моєї Церкви» відповідає на запитання по базі вашої церкви, помічає, хто перестав приходити, готує зведення тижня й підказує наступний крок.",
        title: "Відповіді про вашу церкву — без таблиць і фільтрів",
        lead: "ШІ-асистент працює на даних, які вже є в MyChurch: люди, явка, групи, служіння. Запитайте звичайною мовою — і отримайте не звіт, а відповідь і наступний крок.",
        highlights: [
          "Відповіді на запитання по вашій базі",
          "Сам помічає, хто перестав приходити",
          "Зведення тижня щопонеділка",
          "Дії прямо з відповіді: список, нагадування, розсилка",
        ],
        features: [
          { icon: "MessagesSquare", title: "Запитання звичайною мовою", text: "«Хто не був три тижні?», «Які групи виросли за квартал?» — без фільтрів, звітів і таблиць." },
          { icon: "Eye", title: "Помічає, хто зникає", text: "Стежить за явкою і піднімає людей, які перестали приходити, поки ще можна подзвонити." },
          { icon: "FileText", title: "Зведення тижня", text: "Щопонеділка коротко: хто новий, де впала явка, які групи ростуть і що варто зробити." },
          { icon: "Zap", title: "Дія з відповіді", text: "Надіслати список лідеру, поставити нагадування, запустити розсилку — одним натисканням." },
          { icon: "Lock", title: "Бачить лише те, що й ви", text: "Асистент відповідає в межах вашої ролі: лідер групи не дізнається про чужих людей." },
          { icon: "Smartphone", title: "У Telegram і на дашборді", text: "Запитуйте з телефону через бот церкви або з робочого столу — відповідь та сама." },
        ],
        steps: [
          { title: "Увімкніть асистента", text: "Нічого налаштовувати: він працює на даних, які вже є в системі, і поважає ваші ролі доступу." },
          { title: "Поставте перше запитання", text: "Про людей, явку, групи чи служіння. Відповідь — із вашої бази, з іменами й цифрами." },
          { title: "Підпишіться на зведення", text: "Оберіть день і хто отримує: пастор, рада, лідери. Асистент готує його сам." },
          { title: "Дійте з відповіді", text: "Список лідеру, нагадування собі, розсилка групі — прямо з чату, без переходів між модулями." },
        ],
        audience: [
          { role: "pastor", text: "Запитує про всю церкву й отримує зведення тижня без роботи з фільтрами." },
          { role: "leader", text: "Запитує про свою групу: хто пропускає, кому подзвонити, що змінилось за місяць." },
          { role: "reception", text: "Відповідає гостям одним запитанням: де яка група, коли зустріч, хто лідер." },
          { role: "hr", text: "Бачить навантаження команди: хто служить тричі на тиждень, хто давно не мав вихідного." },
        ],
        faq: [
          { q: "Чи бачить асистент дані, до яких у мене немає доступу?", a: "Ні. Він відповідає в межах вашої ролі. Лідер групи отримує відповіді лише про своїх людей, пастор — про всю церкву." },
          { q: "Куди йдуть дані церкви?", a: "Асистент працює всередині MyChurch на вашій базі. Дані не використовуються для навчання моделей і не передаються третім сторонам." },
          { q: "Чи може асистент помилятися?", a: "Він відповідає лише на основі записів у системі й показує, звідки взяв цифру. Якщо явку не відмітили — він так і скаже." },
          { q: "Чи замінює він аналітику?", a: "Ні, він доповнює: дашборди показують картину, асистент відповідає на конкретне запитання й пропонує наступний крок." },
        ],
        mock: {
          kind: "chat",
          title: "ШІ-асистент",
          subtitle: "Онлайн · працює на базі вашої церкви",
          messages: [
            { from: "user", text: "Хто з новеньких за квітень ще без групи?", time: "09:41" },
            { from: "bot", text: "П'ятеро: Дмитро Лис, Марія Іщенко та ще троє. Двоє живуть біля Виноградаря — там є група в четвер.", time: "09:41" },
            { from: "user", text: "Надішли список Наталі й нагадай мені в п'ятницю.", time: "09:42" },
            { from: "bot", text: "Надіслав Наталі Рудь у Telegram. Нагадування — п'ятниця, 10:00. Підготувати зведення тижня для ради?", time: "09:42" },
            { from: "user", text: "Так, на неділю.", time: "09:43" },
            { from: "bot", text: "Готово. Зведення прийде в неділю о 8:00: явка, новенькі, групи, які потребують уваги.", time: "09:43" },
          ],
          input: "Запитайте про вашу церкву…",
        },
        day: {
          title: "Один день із асистентом",
          text: "Понеділок після служіння. Асистент працює на тих самих даних, що й уся система, і в межах ролі того, хто питає.",
          items: [
            { time: "08:00", title: "Зведення тижня", text: "Пастор отримує в Telegram явку, новеньких і групи, які потребують уваги.", count: "1 зведення" },
            { time: "09:40", title: "Запитання про новеньких", text: "«Хто з квітневих новеньких ще без групи?» Асистент називає п'ятьох і найближчу до них групу.", count: "5 імен" },
            { time: "09:42", title: "Дія просто з чату", text: "Пастор просить надіслати список лідеру й нагадати в п'ятницю. Асистент робить обидва кроки.", count: "2 дії" },
            { time: "11:15", title: "Лідер питає про свою групу", text: "Відповідь охоплює лише її людей: хто пропускає, хто прийшов уперше. Чужих груп лідер не бачить." },
            { time: "13:00", title: "Хто перестав приходити", text: "Асистент піднімає тих, хто пропустив три неділі поспіль, і показує дати останніх відміток.", count: "6 людей" },
            { time: "15:30", title: "Навантаження команди", text: "Керівник служінь питає, хто служить тричі на тиждень, і бачить, кого варто розвантажити.", count: "3 служителі" },
            { time: "17:00", title: "Запитання з рецепції", text: "«Коли збирається група на Виноградарі і хто лідер?» — відповідь із розкладу, без дзвінка адміністратору." },
          ],
          footer: "Кожна відповідь — із записів системи: асистент показує, звідки взято цифру.",
        },
      },
      en: {
        seoTitle: "AI assistants — MyChurch module",
        seoDescription: "The MyChurch AI assistant answers questions from your church's own data, notices who has stopped coming, prepares the weekly digest and suggests the next step.",
        title: "Answers about your church, no spreadsheets or filters",
        lead: "The AI assistant runs on the data already in MyChurch: people, attendance, groups, ministries. Ask in plain language — and get an answer and a next step, not a report.",
        highlights: [
          "Answers questions from your own data",
          "Notices who has stopped coming on its own",
          "A weekly digest every Monday",
          "Acts straight from the answer: list, reminder, campaign",
        ],
        features: [
          { icon: "MessagesSquare", title: "Questions in plain language", text: "\"Who hasn't been for three weeks?\", \"Which groups grew this quarter?\" — no filters, reports or spreadsheets." },
          { icon: "Eye", title: "Notices who drifts away", text: "Watches attendance and raises the people who stopped coming while there's still time to call." },
          { icon: "FileText", title: "Weekly digest", text: "Every Monday, briefly: who's new, where attendance dropped, which groups are growing and what's worth doing." },
          { icon: "Zap", title: "Act from the answer", text: "Send the list to a leader, set a reminder, launch a campaign — in one tap." },
          { icon: "Lock", title: "Sees only what you see", text: "The assistant answers within your role: a group leader learns nothing about other people's groups." },
          { icon: "Smartphone", title: "In Telegram and on the dashboard", text: "Ask from your phone through the church bot or from your desk — the answer is the same." },
        ],
        steps: [
          { title: "Turn the assistant on", text: "Nothing to configure: it runs on the data already in the system and respects your access roles." },
          { title: "Ask your first question", text: "About people, attendance, groups or ministries. The answer comes from your database, with names and numbers." },
          { title: "Subscribe to the digest", text: "Pick the day and who receives it: the pastor, the board, the leaders. The assistant prepares it itself." },
          { title: "Act from the answer", text: "A list to a leader, a reminder for yourself, a campaign to a group — straight from the chat, no switching modules." },
        ],
        audience: [
          { role: "pastor", text: "Asks about the whole church and gets the weekly digest without touching a filter." },
          { role: "leader", text: "Asks about their own group: who's missing, who to call, what changed this month." },
          { role: "reception", text: "Answers guests with one question: where each group meets, when, and who leads it." },
          { role: "hr", text: "Sees the team's load: who serves three times a week, who hasn't had a day off in a while." },
        ],
        faq: [
          { q: "Can the assistant see data I don't have access to?", a: "No. It answers within your role. A group leader gets answers only about their own people, the pastor about the whole church." },
          { q: "Where does the church's data go?", a: "The assistant works inside MyChurch on your own database. Your data isn't used to train models and isn't passed to third parties." },
          { q: "Can the assistant get it wrong?", a: "It answers only from the records in the system and shows where each number came from. If attendance wasn't marked, it says so." },
          { q: "Does it replace analytics?", a: "No, it complements it: dashboards show the picture, the assistant answers a specific question and suggests the next step." },
        ],
        mock: {
          kind: "chat",
          title: "AI assistant",
          subtitle: "Online · runs on your church's data",
          messages: [
            { from: "user", text: "Which April newcomers still have no group?", time: "09:41" },
            { from: "bot", text: "Five: Dmytro Lys, Maria Ishchenko and three more. Two live near Obolon — there's a Thursday group there.", time: "09:41" },
            { from: "user", text: "Send the list to Natalia and remind me on Friday.", time: "09:42" },
            { from: "bot", text: "Sent to Natalia Rud in Telegram. Reminder set for Friday, 10:00. Shall I prepare the weekly digest for the board?", time: "09:42" },
            { from: "user", text: "Yes, for Sunday.", time: "09:43" },
            { from: "bot", text: "Done. The digest arrives on Sunday at 8:00: attendance, newcomers, groups that need attention.", time: "09:43" },
          ],
          input: "Ask about your church…",
        },
        day: {
          title: "One day with the assistant",
          text: "A Monday after the service. The assistant runs on the same data as the rest of the system, within the role of whoever asks.",
          items: [
            { time: "08:00", title: "Weekly digest", text: "The pastor gets attendance, newcomers and the groups that need attention in Telegram.", count: "1 digest" },
            { time: "09:40", title: "A question about newcomers", text: "\"Which April newcomers still have no group?\" The assistant names five and the nearest group.", count: "5 names" },
            { time: "09:42", title: "Action straight from the chat", text: "The pastor asks it to send the list to the leader and remind him on Friday. Both steps are done.", count: "2 actions" },
            { time: "11:15", title: "A leader asks about their group", text: "The answer covers only their people: who is missing, who came for the first time. Other groups stay hidden." },
            { time: "13:00", title: "Who has stopped coming", text: "The assistant raises everyone absent three Sundays running and shows the dates of their last check-ins.", count: "6 people" },
            { time: "15:30", title: "Team load", text: "The ministry lead asks who serves three times a week and sees who needs a break.", count: "3 volunteers" },
            { time: "17:00", title: "A question from reception", text: "\"When does the Obolon group meet and who leads it?\" — answered from the schedule, no call to the administrator." },
          ],
          footer: "Every answer comes from records in the system — the assistant shows where each number came from.",
        },
      },
    },
  },
];
