import type { ModuleDetail } from "./types";

/* Module pages: org, requests, accounting — their catalogue group is the `group` field below. */
export const hrModules: ModuleDetail[] = [
  {
    id: "org",
    group: "team",
    related: ["people", "ministries", "requests", "knowledge"],
    copy: {
      ua: {
        seoTitle: "Оргструктура — модуль «Моя Церква»",
        seoDescription: "Оргструктура церкви: відділи, служіння, ролі та підпорядкування. Хто за що відповідає, хто кому звітує, де вакансії — наочно й завжди актуально.",
        title: "Уся команда церкви — на одній схемі",
        lead: "Модуль «Оргструктура» показує церкву як команду: відділи й служіння, керівники, ролі та підпорядкування. Новий служитель за хвилину розуміє, до кого йти, а пастор бачить, де людей забагато, а де нікого.",
        highlights: [
          "Схема відділів і служінь з керівниками",
          "Ролі з описом обов'язків",
          "Вакансії та навантаження на людину",
          "Зміни з історією: хто й коли",
        ],
        features: [
          { icon: "Network", title: "Схема команди", text: "Відділи, служіння, команди й люди в них — як дерево. Розгортайте гілки, переносьте людей перетягуванням." },
          { icon: "UserCheck", title: "Ролі та обов'язки", text: "Кожна роль має опис: за що відповідає, кому звітує, який доступ у системі. Людина може мати кілька ролей." },
          { icon: "GitBranch", title: "Підпорядкування", text: "Хто кому звітує й хто кого заміщає. Запити та погодження йдуть по цій лінії автоматично." },
          { icon: "Flag", title: "Вакансії", text: "Порожня роль — відкрита позиція. Список вакансій церкви завжди актуальний і готовий до оголошення." },
          { icon: "Gauge", title: "Навантаження", text: "Скільки ролей у людини й у скількох служіннях вона одночасно. Перевантажених видно ще до вигорання." },
          { icon: "History", title: "Історія змін", text: "Хто очолював служіння торік, коли передали команду — усе збережено, нічого не губиться." },
        ],
        steps: [
          { title: "Опишіть відділи й служіння", text: "Почніть із великих блоків: прославлення, діти, малі групи, адміністрація. Додавайте команди всередині." },
          { title: "Призначте ролі людям", text: "Керівники, помічники, служителі — з бази «Люди». Одна людина може бути в кількох відділах." },
          { title: "Підтримуйте актуальність", text: "Зміни вносить HR або керівник відділу, історія зберігається. Запити на погодження одразу йдуть новому керівнику." },
        ],
        audience: [
          { role: "hr", text: "Тримає структуру актуальною, бачить вакансії й навантаження, оформлює переходи між командами." },
          { role: "pastor", text: "Бачить усю команду церкви на одній схемі: хто кого веде, де порожньо, кого варто розвантажити." },
          { role: "leader", text: "Знає склад своєї команди й ролі в ній, призначає помічників і передає служіння без втрат." },
          { role: "member", text: "Розуміє, до кого звернутись із питанням, і бачить, де в церкві потрібні люди." },
        ],
        faq: [
          { q: "У нас волонтери, а не штат. Чи потрібна оргструктура?", a: "Саме для волонтерів вона найкорисніша: ролі змінюються часто, і без схеми ніхто не знає, хто зараз відповідає за звук чи зустріч гостей." },
          { q: "Чи впливає оргструктура на доступ у системі?", a: "Так, якщо ви цього хочете. Роль може відкривати доступ до групи, служіння чи модуля, і при зміні ролі доступ оновлюється автоматично." },
          { q: "Як оргструктура пов'язана з модулем «Служіння»?", a: "Служіння — це команди зі своїм графіком і явкою. Оргструктура показує, як ці команди складаються в церкву й хто ким керує." },
          { q: "Чи можна вести структуру для кількох кемпусів?", a: "Так. Кожен кемпус має свою гілку, а загальноцерковні служіння — спільну. Керівник кемпусу бачить своє, пастор — усе." },
        ],
        mock: {
          kind: "list",
          title: "Оргструктура",
          subtitle: "46 у команді · 8 відділів · 3 вакансії",
          items: [
            { title: "Прославлення", sub: "Керівник: Олена Ковальчук", meta: "14 людей" },
            { title: "Дитяче служіння", sub: "Керівник: Наталя Рудь", meta: "11 людей", badge: { label: "1 вакансія", tone: "amber" } },
            { title: "Малі групи", sub: "Керівник: Андрій Мельник", meta: "23 лідери" },
            { title: "Зустріч гостей", sub: "Керівник: Василь Панченко", meta: "6 людей" },
            { title: "Технічна команда", sub: "Керівника не призначено", meta: "4 людей", badge: { label: "Вакансія", tone: "red" } },
            { title: "Адміністрація", sub: "Керівник: Ірина Шевчук", meta: "3 людей" },
          ],
          footer: "Перетягніть людину, щоб змінити відділ",
        },
        pipeline: {
          title: "Шлях вакансії: від порожньої ролі до служителя",
          text: "Приклад для ролі «Звукооператор» у технічній команді. Кожен етап змінює статус ролі на схемі.",
          stages: [
            { title: "Роль вільна", tone: "neutral", text: "Керівник відділу позначає роль як вакантну: обов'язки, скільки неділь на місяць, кому звітує.", auto: "Додає роль у список вакансій церкви й в оголошення бота для охочих служити." },
            { title: "Кандидат", tone: "brand", text: "HR підбирає людей із бази за дарами й інтересами. Охочі подають заявку самі.", auto: "Ставить керівнику задачу «поговорити» з терміном тиждень." },
            { title: "Стажування", tone: "amber", text: "Людина пробує служіння три-чотири неділі поруч із наставником.", auto: "Додає її в графік служіння як стажера й нагадує наставнику про зустріч." },
            { title: "Призначено", tone: "green", text: "Роль закріплена за людиною. Вакансія зникає зі схеми, з'являється ім'я.", auto: "Відкриває доступи за роллю, оновлює підпорядкування й записує зміну в історію." },
          ],
        },
        benefits: {
          title: "Що дає схема команди",
          text: "Приклад: церква на 200 людей, вісім відділів, 46 служителів. Порівнюємо зі списком у таблиці, який оновлюють раз на рік.",
          items: [
            { value: "1 екран", label: "щоб зрозуміти, хто за що відповідає", text: "Новий служитель бачить свій відділ, керівника й сусідні команди — без питань до пастора." },
            { value: "3", label: "відкриті позиції видно постійно", text: "Порожня роль на схемі — це рядок у списку вакансій і оголошення в боті, а не забута думка." },
            { value: "0", label: "втрачених доступів при зміні ролі", text: "Роль передали — доступи, підпорядкування й маршрути погоджень переїхали разом із нею." },
            { value: "2", label: "перевантажених помічено вчасно", text: "Людину в чотирьох командах одночасно видно ще до того, як вона попросить паузу." },
          ],
        },
      },
      en: {
        seoTitle: "Org structure — My Church module",
        seoDescription: "The church org chart: departments, ministries, roles and reporting lines. Who does what, who reports to whom, where the vacancies are — always current.",
        title: "The whole church team on one chart",
        lead: "The Org structure module shows the church as a team: departments and ministries, heads, roles and reporting lines. A new volunteer understands in a minute who to go to, and the pastor sees where there are too many people and where there's no one.",
        highlights: [
          "A chart of departments and ministries with their heads",
          "Roles with a description of duties",
          "Vacancies and workload per person",
          "Changes with history: who and when",
        ],
        features: [
          { icon: "Network", title: "Team chart", text: "Departments, ministries, teams and the people in them — as a tree. Expand branches, move people by drag and drop." },
          { icon: "UserCheck", title: "Roles and duties", text: "Every role has a description: what it's responsible for, who it reports to, what access it has in the system. One person can hold several roles." },
          { icon: "GitBranch", title: "Reporting lines", text: "Who reports to whom and who covers for whom. Requests and approvals follow this line automatically." },
          { icon: "Flag", title: "Vacancies", text: "An empty role is an open position. The church's list of vacancies is always current and ready to announce." },
          { icon: "Gauge", title: "Workload", text: "How many roles a person holds and how many ministries they're in at once. The overloaded are visible before burnout." },
          { icon: "History", title: "Change history", text: "Who led the ministry last year, when the team was handed over — everything is kept, nothing gets lost." },
        ],
        steps: [
          { title: "Describe departments and ministries", text: "Start with the big blocks: worship, kids, small groups, administration. Add teams inside them." },
          { title: "Assign roles to people", text: "Heads, assistants, volunteers — from the People database. One person can be in several departments." },
          { title: "Keep it current", text: "HR or a department head makes changes, history is kept. Approval requests go straight to the new head." },
        ],
        audience: [
          { role: "hr", text: "Keeps the structure current, sees vacancies and workload, and handles moves between teams." },
          { role: "pastor", text: "Sees the whole church team on one chart: who leads whom, where it's empty, who needs a lighter load." },
          { role: "leader", text: "Knows their team and the roles in it, appoints assistants and hands over a ministry without losing anything." },
          { role: "member", text: "Knows who to turn to with a question and sees where the church needs people." },
        ],
        faq: [
          { q: "We have volunteers, not staff. Do we need an org chart?", a: "That's exactly where it helps most: roles change often, and without a chart no one knows who is currently responsible for sound or welcoming guests." },
          { q: "Does the org structure affect access in the system?", a: "Yes, if you want it to. A role can grant access to a group, a ministry or a module, and when the role changes, access updates automatically." },
          { q: "How does it relate to the Ministries module?", a: "Ministries are teams with their own rota and attendance. The org structure shows how those teams fit together into the church and who leads whom." },
          { q: "Can we keep a structure for several campuses?", a: "Yes. Each campus has its own branch, and church-wide ministries share one. A campus leader sees their own, the pastor sees everything." },
        ],
        mock: {
          kind: "list",
          title: "Org structure",
          subtitle: "46 people · 8 departments · 3 vacant",
          items: [
            { title: "Worship", sub: "Head: Olena Kovalchuk", meta: "14 people" },
            { title: "Kids ministry", sub: "Head: Natalia Rud", meta: "11 people", badge: { label: "1 vacancy", tone: "amber" } },
            { title: "Small groups", sub: "Head: Andrii Melnyk", meta: "23 leaders" },
            { title: "Welcome team", sub: "Head: Vasyl Panchenko", meta: "6 people" },
            { title: "Tech team", sub: "No head assigned", meta: "4 people", badge: { label: "Vacancy", tone: "red" } },
            { title: "Administration", sub: "Head: Iryna Shevchuk", meta: "3 people" },
          ],
          footer: "Drag a person to move them to another department",
        },
        pipeline: {
          title: "A vacancy's path: from empty role to volunteer",
          text: "Example for the \"Sound engineer\" role on the tech team. Each stage changes the role's status on the chart.",
          stages: [
            { title: "Role open", tone: "neutral", text: "The department head marks the role vacant: duties, how many Sundays a month, who it reports to.", auto: "Adds the role to the church's vacancy list and to the bot's announcement for anyone willing to serve." },
            { title: "Candidate", tone: "brand", text: "HR suggests people from the database by gifts and interests. Volunteers also apply themselves.", auto: "Gives the head a \"have a chat\" task with a one-week deadline." },
            { title: "Trial", tone: "amber", text: "The person tries the ministry for three or four Sundays alongside a mentor.", auto: "Adds them to the rota as a trainee and reminds the mentor about their catch-up." },
            { title: "Appointed", tone: "green", text: "The role now belongs to that person. The vacancy disappears from the chart and a name appears.", auto: "Grants the role's access, updates the reporting line and logs the change in history." },
          ],
        },
        benefits: {
          title: "What the chart changes",
          text: "Example: a church of 200 people, eight departments, 46 volunteers. Compared with a list in a spreadsheet that gets updated once a year.",
          items: [
            { value: "1 screen", label: "to see who is responsible for what", text: "A new volunteer sees their department, their leader and the neighbouring teams — without asking the pastor." },
            { value: "3", label: "open positions always visible", text: "An empty role on the chart is a line in the vacancy list and a post in the bot, not a forgotten thought." },
            { value: "0", label: "access lost when a role moves", text: "Hand over the role and the permissions, the reporting line and the approval routes move with it." },
            { value: "2", label: "overloaded people spotted in time", text: "Someone on four teams at once shows up before they ask for a break." },
          ],
        },
      },
    },
  },
  {
    id: "requests",
    group: "team",
    related: ["org", "service-planning", "telegram-bot", "automations"],
    copy: {
      ua: {
        seoTitle: "Запити — модуль «Моя Церква»",
        seoDescription: "Відпустки, заміни на служінні, заявки на кошти чи приміщення: служитель подає з телефону, керівник погоджує в один клік, HR бачить усю чергу запитів.",
        title: "Погодження за хвилину, а не за тиждень у чатах",
        lead: "Модуль «Запити» замінює переписки «а можна мені в неділю не служити?». Служитель подає запит з телефону, він іде до потрібного керівника, той погоджує одним натисканням, а HR бачить усю картину.",
        highlights: [
          "Типи запитів під процеси вашої церкви",
          "Маршрут погодження за оргструктурою",
          "Погодити або відхилити — з Telegram",
          "Історія й статуси без переписок",
        ],
        features: [
          { icon: "Inbox", title: "Типи запитів", text: "Відпустка, заміна на служінні, кошти на подію, приміщення, техніка, довідка. Свої типи — з потрібними полями." },
          { icon: "Route", title: "Маршрут погодження", text: "Запит іде до керівника за оргструктурою, далі — до HR або бухгалтера, якщо це потрібно. Один крок або кілька." },
          { icon: "Smartphone", title: "Подати з телефону", text: "Форма на дві хвилини у вебі або в Telegram-боті. Фото документа чи рахунку — одразу до запиту." },
          { icon: "CheckCircle2", title: "Погодження в один клік", text: "Керівник отримує повідомлення й погоджує або відхиляє, не заходячи в систему. Коментар — за бажанням." },
          { icon: "RefreshCw", title: "Заміна на служінні", text: "Служитель просить заміну — система пропонує вільних людей із тієї ж команди, і графік оновлюється сам." },
          { icon: "ClipboardList", title: "Черга та історія", text: "HR бачить усі відкриті запити, хто затримує погодження й скільки днів відпустки лишилось у людини." },
        ],
        steps: [
          { title: "Оберіть типи запитів", text: "Увімкніть готові: відпустка, заміна, кошти, приміщення. Додайте свої з потрібними полями." },
          { title: "Задайте, хто погоджує", text: "Для кожного типу — маршрут: керівник, HR, бухгалтер. Підставляється з оргструктури автоматично." },
          { title: "Розкажіть команді", text: "Служителі подають запити з бота або вебу, керівники погоджують з телефону, HR бачить усе." },
        ],
        audience: [
          { role: "volunteer", text: "Просить відпустку чи заміну за дві хвилини з телефону й бачить, на якому етапі запит." },
          { role: "leader", text: "Погоджує запити своєї команди одним натисканням і бачить, хто вільний на неділю." },
          { role: "hr", text: "Бачить усі запити церкви, стежить за термінами погодження й веде облік відпусток команди." },
          { role: "pastor", text: "Погоджує лише те, що справді потребує його рішення, — решта закривається на рівні керівників." },
        ],
        faq: [
          { q: "Чи можна погодити запит, не заходячи в систему?", a: "Так. Повідомлення приходить у Telegram із кнопками «Погодити» й «Відхилити». Рішення одразу записується в систему." },
          { q: "Що буде з графіком служіння після запиту на заміну?", a: "Коли заміну погоджено, система сама оновить графік у модулі «Служіння» й повідомить обох служителів." },
          { q: "Чи можна вести облік відпусток для штатних працівників?", a: "Так. Для кожного працівника — норма днів на рік, використані й залишок. Погоджена відпустка автоматично зменшує залишок." },
          { q: "Хто бачить чужі запити?", a: "Служитель — лише свої, керівник — своєї команди, HR і пастор — усі. Запити на кошти додатково бачить бухгалтер." },
        ],
        mock: {
          kind: "board",
          title: "Запити",
          subtitle: "7 відкритих · 2 чекають на вас",
          columns: [
            {
              title: "Нові",
              cards: [
                { title: "Відпустка 14–21 жов", sub: "Олена Ковальчук · прославлення", tag: { label: "Відпустка", tone: "brand" } },
                { title: "Заміна на неділю", sub: "Дмитро Лис · звук", tag: { label: "Заміна", tone: "violet" } },
                { title: "₴3 200 на декор", sub: "Марія Іщенко · дитяче служіння", tag: { label: "Кошти", tone: "amber" } },
              ],
            },
            {
              title: "На погодженні",
              cards: [
                { title: "Кімната 2 на суботу", sub: "Наталя Рудь · чекає рецепцію", tag: { label: "Приміщення", tone: "neutral" } },
                { title: "Відпустка 1–7 лис", sub: "Андрій Мельник · чекає HR", tag: { label: "Відпустка", tone: "brand" } },
              ],
            },
            {
              title: "Погоджено",
              cards: [
                { title: "Заміна на 21 вер", sub: "Ірина Шевчук → Василь П.", tag: { label: "Заміна", tone: "green" } },
                { title: "₴1 800 на ноти", sub: "Олена Ковальчук · виплачено", tag: { label: "Кошти", tone: "green" } },
              ],
            },
          ],
        },
      },
      en: {
        seoTitle: "Requests — My Church module",
        seoDescription: "Time off, cover on a ministry, requests for funds or rooms: a volunteer submits from a phone, a leader approves in one click and HR sees the whole queue.",
        title: "Approvals in a minute, not a week of chats",
        lead: "The Requests module replaces the \"can I skip serving on Sunday?\" messages. A volunteer submits a request from their phone, it goes to the right leader, who approves with one tap, and HR sees the full picture.",
        highlights: [
          "Request types that match your church's processes",
          "Approval routes based on the org structure",
          "Approve or decline from Telegram",
          "History and statuses without chat threads",
        ],
        features: [
          { icon: "Inbox", title: "Request types", text: "Time off, cover on a ministry, funds for an event, a room, equipment, a reference letter. Your own types — with the fields you need." },
          { icon: "Route", title: "Approval route", text: "A request goes to the leader from the org structure, then to HR or the accountant if needed. One step or several." },
          { icon: "Smartphone", title: "Submit from a phone", text: "A two-minute form on the web or in the Telegram bot. A photo of a document or invoice attaches straight to the request." },
          { icon: "CheckCircle2", title: "One-click approval", text: "The leader gets a notification and approves or declines without opening the system. A comment is optional." },
          { icon: "RefreshCw", title: "Cover on a ministry", text: "A volunteer asks for cover — the system suggests free people from the same team, and the rota updates itself." },
          { icon: "ClipboardList", title: "Queue and history", text: "HR sees every open request, who is holding up an approval and how much leave a person has left." },
        ],
        steps: [
          { title: "Choose request types", text: "Turn on the ready-made ones: time off, cover, funds, rooms. Add your own with the fields you need." },
          { title: "Set who approves", text: "A route for each type: leader, HR, accountant. It's filled in from the org structure automatically." },
          { title: "Tell the team", text: "Volunteers submit requests from the bot or the web, leaders approve from their phones, HR sees everything." },
        ],
        audience: [
          { role: "volunteer", text: "Asks for time off or cover in two minutes from a phone and sees which stage the request is at." },
          { role: "leader", text: "Approves their team's requests with one tap and sees who is free on Sunday." },
          { role: "hr", text: "Sees every request in the church, keeps an eye on approval times and tracks the team's leave." },
          { role: "pastor", text: "Approves only what genuinely needs their decision — the rest is closed at leader level." },
        ],
        faq: [
          { q: "Can I approve a request without opening the system?", a: "Yes. The notification arrives in Telegram with Approve and Decline buttons. The decision is recorded in the system immediately." },
          { q: "What happens to the rota after a cover request?", a: "Once cover is approved, the system updates the rota in the Ministries module itself and notifies both volunteers." },
          { q: "Can we track leave for paid staff?", a: "Yes. Each employee has an annual allowance, days used and days remaining. An approved leave request reduces the balance automatically." },
          { q: "Who can see other people's requests?", a: "A volunteer sees only their own, a leader their team's, HR and the pastor all of them. Requests for funds are also visible to the accountant." },
        ],
        mock: {
          kind: "board",
          title: "Requests",
          subtitle: "7 open · 2 waiting for you",
          columns: [
            {
              title: "New",
              cards: [
                { title: "Leave 14–21 Oct", sub: "Olena Kovalchuk · worship", tag: { label: "Leave", tone: "brand" } },
                { title: "Cover for Sunday", sub: "Dmytro Lys · sound", tag: { label: "Cover", tone: "violet" } },
                { title: "₴3,200 for decor", sub: "Maria Ishchenko · kids ministry", tag: { label: "Funds", tone: "amber" } },
              ],
            },
            {
              title: "In review",
              cards: [
                { title: "Room 2 on Saturday", sub: "Natalia Rud · waiting for reception", tag: { label: "Room", tone: "neutral" } },
                { title: "Leave 1–7 Nov", sub: "Andrii Melnyk · waiting for HR", tag: { label: "Leave", tone: "brand" } },
              ],
            },
            {
              title: "Approved",
              cards: [
                { title: "Cover for 21 Sep", sub: "Iryna Shevchuk → Vasyl P.", tag: { label: "Cover", tone: "green" } },
                { title: "₴1,800 for sheet music", sub: "Olena Kovalchuk · paid", tag: { label: "Funds", tone: "green" } },
              ],
            },
          ],
        },
      },
    },
  },
  {
    id: "accounting",
    group: "team",
    related: ["analytics", "events", "camps", "projects"],
    copy: {
      ua: {
        seoTitle: "Бухгалтерія — модуль «Моя Церква»",
        seoDescription: "Фінанси церкви прозоро: пожертви готівкою, карткою та онлайн, витрати з погодженням, виплати команді, бюджети служінь і звіти за будь-який період.",
        title: "Кожна пожертва облікована, звіт — за хвилину",
        lead: "Модуль «Бухгалтерія» збирає всі гроші церкви в одному журналі: пожертви з неділі, онлайн-платежі, витрати служінь, виплати команді. Звіт для ради за квартал — одним натисканням, без Excel.",
        highlights: [
          "Пожертви: готівка, картка, онлайн — в одному журналі",
          "Витрати з погодженням і документами",
          "Бюджети служінь: план проти факту",
          "Звіти за місяць, квартал, рік",
        ],
        features: [
          { icon: "Banknote", title: "Журнал пожертв", text: "Недільний збір, цільові пожертви, десятини, онлайн-платежі. Кожна — з датою й призначенням, а до людини прив'язана лише за її бажанням." },
          { icon: "Receipt", title: "Витрати з документами", text: "Категорія, служіння, відповідальний, фото чека. Витрата понад ліміт — спершу погодження, потім оплата." },
          { icon: "Wallet", title: "Виплати команді", text: "Зарплати штату, компенсації служителям, оплата підрядникам — з історією та документами по кожній людині." },
          { icon: "PieChart", title: "Бюджети служінь", text: "План на рік по кожному служінню й проєкту. Факт підтягується сам, перевитрату видно заздалегідь." },
          { icon: "FileSpreadsheet", title: "Звіти та експорт", text: "Місяць, квартал, рік, окрема подія чи табір. Один клік — і PDF для ради або Excel для вашого бухгалтера." },
          { icon: "Lock", title: "Доступ та аудит", text: "Бухгалтер бачить усе, пастор — зведення, лідер — бюджет свого служіння. Кожна зміна записана: хто, коли, що." },
        ],
        steps: [
          { title: "Налаштуйте категорії", text: "Пожертви, витрати, фонди: загальний, будівельний, місії. Каси й рахунки — скільки потрібно." },
          { title: "Вносьте операції щотижня", text: "Недільний збір — після служіння, витрати — з фото чека. Онлайн-платежі й оплати за табори підтягуються самі." },
          { title: "Отримуйте звіти", text: "Рада бачить зведення щомісяця, бухгалтер вивантажує дані для офіційної звітності, лідери — свої бюджети." },
        ],
        audience: [
          { role: "accountant", text: "Веде журнал пожертв і витрат, готує виплати й вивантажує дані для офіційної звітності без подвійного вводу." },
          { role: "pastor", text: "Бачить зведення: надходження, витрати, залишок по фондах і як виконується бюджет." },
          { role: "leader", text: "Знає бюджет свого служіння, подає витрати з фото чека й бачить залишок." },
          { role: "member", text: "Бачить історію своїх пожертв і отримує квитанцію без запитів в офіс." },
        ],
        faq: [
          { q: "Чи замінює модуль офіційний бухгалтерський облік?", a: "Ні. Це управлінський облік для церкви: щоб пастор, рада й команда бачили реальну картину. Дані експортуються для вашого бухгалтера чи бухгалтерської програми у два кліки." },
          { q: "Чи можна вести пожертви анонімно?", a: "Так. Пожертву можна записати без прив'язки до людини. Прив'язка потрібна лише тоді, коли жертводавець хоче бачити історію чи отримати квитанцію." },
          { q: "Як обліковуються оплати за табори й події?", a: "Оплата, внесена в модулях «Табори» чи «Організатор подій», автоматично потрапляє в журнал із потрібною категорією — вносити двічі не треба." },
          { q: "Хто бачить фінансові дані?", a: "Ви задаєте ролі: бухгалтер — усе, пастор — зведення, лідер — бюджет свого служіння. Зарплати можна закрити від усіх, крім двох людей." },
        ],
        mock: {
          kind: "stats",
          title: "Фінанси · вересень",
          subtitle: "Надходження проти витрат",
          kpis: [
            { label: "Пожертви за місяць", value: "₴184 500", trend: "+8%" },
            { label: "Витрати", value: "₴121 300", trend: "−3%" },
            { label: "Залишок у фондах", value: "₴412 900" },
          ],
          barsTitle: "Пожертви по місяцях",
          bars: [
            { label: "Лют", value: 62 },
            { label: "Бер", value: 70 },
            { label: "Кві", value: 88 },
            { label: "Тра", value: 66 },
            { label: "Чер", value: 60 },
            { label: "Лип", value: 55 },
            { label: "Сер", value: 64 },
            { label: "Вер", value: 78 },
          ],
        },
        pipeline: {
          title: "Шлях витрати: від заявки до звіту",
          text: "Приклад для витрати служіння. Пожертви йдуть коротшим шляхом: запис у журнал — звірка — звіт.",
          stages: [
            { title: "Заявка", tone: "neutral", text: "Лідер подає витрату: сума, служіння, призначення, фото рахунку чи чека.", auto: "Показує в заявці залишок бюджету служіння на поточний рік." },
            { title: "Погодження", tone: "amber", text: "Понад ліміт — спершу керівник, потім бухгалтер. У межах ліміту — одразу до оплати.", auto: "Надсилає запит у Telegram і нагадує, якщо два дні немає відповіді." },
            { title: "Оплата", tone: "brand", text: "Бухгалтер оплачує з каси або з рахунку й прикріплює платіжний документ.", auto: "Записує операцію в журнал і зменшує залишок бюджету служіння." },
            { title: "У звіті", tone: "green", text: "Витрата стоїть у місячному звіті з категорією, служінням і документом.", auto: "Закриває місяць і формує зведення для ради — PDF або Excel." },
          ],
        },
        benefits: {
          title: "Що дає єдиний журнал",
          text: "Приклад: церква на 200 людей, три фонди, бюджети восьми служінь. Порівнюємо з обліком у кількох Excel-файлах.",
          items: [
            { value: "1 хв", label: "на звіт для ради", text: "Місяць, квартал, рік чи окремий табір — звіт формується з журналу, а не збирається руками напередодні." },
            { value: "0", label: "подвійних вводів", text: "Оплати за табори й події та онлайн-пожертви потрапляють у журнал самі — з категорією та призначенням." },
            { value: "8", label: "служінь бачать свій бюджет", text: "Лідер знає залишок до того, як витратить, тому перевитрата помічається не в грудні." },
            { value: "100%", label: "витрат із документом", text: "Фото чека — обов'язкове поле заявки. Звірка наприкінці місяця перестає бути пошуком паперів." },
          ],
        },
      },
      en: {
        seoTitle: "Accounting — My Church module",
        seoDescription: "Church finances made transparent: cash, card and online giving, expenses with approval, team payouts, ministry budgets and reports for any period — no Excel.",
        title: "Every donation recorded, every report in a minute",
        lead: "The Accounting module brings all the church's money into one ledger: Sunday offerings, online payments, ministry expenses, team payouts. A quarterly report for the board takes one click — no Excel.",
        highlights: [
          "Giving: cash, card, online — in one ledger",
          "Expenses with approval and documents",
          "Ministry budgets: plan vs. actual",
          "Reports by month, quarter, year",
        ],
        features: [
          { icon: "Banknote", title: "Giving ledger", text: "Sunday offering, designated gifts, tithes, online payments. Each with a date and purpose — and linked to a person only if they want it." },
          { icon: "Receipt", title: "Expenses with documents", text: "Category, ministry, owner, a photo of the receipt. Over the limit — approval first, payment second." },
          { icon: "Wallet", title: "Team payouts", text: "Staff salaries, volunteer reimbursements, contractor payments — with history and documents per person." },
          { icon: "PieChart", title: "Ministry budgets", text: "A yearly plan for every ministry and project. Actuals fill in on their own, overspend is visible in advance." },
          { icon: "FileSpreadsheet", title: "Reports and export", text: "Month, quarter, year, a single event or camp. One click — a PDF for the board or Excel for your accountant." },
          { icon: "Lock", title: "Access and audit", text: "The accountant sees everything, the pastor a summary, a leader their own ministry's budget. Every change is logged: who, when, what." },
        ],
        steps: [
          { title: "Set up categories", text: "Giving, expenses, funds: general, building, missions. As many cash boxes and accounts as you need." },
          { title: "Record transactions weekly", text: "The Sunday offering after the service, expenses with a receipt photo. Online payments and camp fees come in on their own." },
          { title: "Get your reports", text: "The board sees a summary every month, the accountant exports data for statutory reporting, leaders see their budgets." },
        ],
        audience: [
          { role: "accountant", text: "Keeps the giving and expense ledger, prepares payouts and exports data for statutory reporting without double entry." },
          { role: "pastor", text: "Sees the summary: income, expenses, fund balances and how the budget is tracking." },
          { role: "leader", text: "Knows their ministry's budget, submits expenses with a receipt photo and sees what's left." },
          { role: "member", text: "Sees their own giving history and gets a receipt without asking the office." },
        ],
        faq: [
          { q: "Does the module replace statutory accounting?", a: "No. It's management accounting for the church, so the pastor, board and team see the real picture. The data exports for your accountant or accounting software in two clicks." },
          { q: "Can giving be recorded anonymously?", a: "Yes. A donation can be recorded without linking it to a person. Linking is only needed when the donor wants to see their history or receive a receipt." },
          { q: "How are camp and event payments recorded?", a: "A payment made in the Camps or Event organiser modules goes into the ledger automatically with the right category — no double entry." },
          { q: "Who can see financial data?", a: "You set the roles: the accountant sees everything, the pastor a summary, a leader their own ministry's budget. Salaries can be hidden from everyone but two people." },
        ],
        mock: {
          kind: "stats",
          title: "Finance · September",
          subtitle: "Income vs. expenses",
          kpis: [
            { label: "Giving this month", value: "₴184,500", trend: "+8%" },
            { label: "Expenses", value: "₴121,300", trend: "−3%" },
            { label: "Fund balance", value: "₴412,900" },
          ],
          barsTitle: "Giving by month",
          bars: [
            { label: "Feb", value: 62 },
            { label: "Mar", value: 70 },
            { label: "Apr", value: 88 },
            { label: "May", value: 66 },
            { label: "Jun", value: 60 },
            { label: "Jul", value: 55 },
            { label: "Aug", value: 64 },
            { label: "Sep", value: 78 },
          ],
        },
        pipeline: {
          title: "An expense's path: from request to report",
          text: "Example for a ministry expense. Giving takes a shorter path: recorded in the ledger, reconciled, reported.",
          stages: [
            { title: "Request", tone: "neutral", text: "A leader submits the expense: amount, ministry, purpose, a photo of the invoice or receipt.", auto: "Shows the ministry's remaining budget for the year inside the request." },
            { title: "Approval", tone: "amber", text: "Over the limit — the head first, then the accountant. Within the limit — straight to payment.", auto: "Sends the request in Telegram and follows up if there is no answer for two days." },
            { title: "Payment", tone: "brand", text: "The accountant pays from the cash box or the bank account and attaches the payment document.", auto: "Records the transaction in the ledger and reduces the ministry's remaining budget." },
            { title: "In the report", tone: "green", text: "The expense sits in the monthly report with its category, ministry and document.", auto: "Closes the month and builds the summary for the board — PDF or Excel." },
          ],
        },
        benefits: {
          title: "What one ledger changes",
          text: "Example: a church of 200 people, three funds, budgets for eight ministries. Compared with bookkeeping spread across several spreadsheets.",
          items: [
            { value: "1 min", label: "to produce a board report", text: "A month, a quarter, a year or a single camp — the report comes out of the ledger instead of being assembled the night before." },
            { value: "0", label: "double entries", text: "Camp and event payments and online giving land in the ledger on their own, with the category and the purpose already set." },
            { value: "8", label: "ministries see their budget", text: "A leader knows the balance before spending, so an overrun is noticed long before December." },
            { value: "100%", label: "of expenses carry a document", text: "A photo of the receipt is a required field. Month-end reconciliation stops being a paper hunt." },
          ],
        },
      },
    },
  },
];
