import type { ModuleDetail } from "./types";

/* Module pages: telegram, viber, instagram, whatsapp, turbosms, notion — their catalogue group is the `group` field below. */
export const integrationsModules: ModuleDetail[] = [
  {
    id: "telegram",
    group: "integrations",
    related: ["telegram-bot", "campaigns", "automations", "groups"],
    copy: {
      ua: {
        seoTitle: "Telegram — модуль «Моя Церква»",
        seoDescription: "Telegram у «Моїй Церкві»: розсилки за групами й фільтрами, нагадування служителям, відмітка приходу за QR і статус доставки — з бази церкви, без нових застосунків.",
        title: "Повідомлення церкви доходять туди, де люди вже є",
        lead: "Telegram — це там, де ваша громада вже спілкується. Підключіть канал і бота церкви до «Моєї Церкви» — і нагадування, розсилки та відмітка приходу працюватимуть без жодної нової програми.",
        highlights: [
          "Розсилки за групами й фільтрами",
          "Нагадування служителям за день і за годину",
          "Відмітка приходу за QR або одним натисканням",
          "Звіт про доставку й прочитання",
        ],
        features: [
          { icon: "Send", title: "Розсилки з бази", text: "Оберіть сегмент — «молодіжка», «без групи», «служителі неділі» — і повідомлення піде саме їм, а не всьому чату." },
          { icon: "BellRing", title: "Нагадування без рук", text: "За день до служіння, за годину до зустрічі групи, у день народження — сценарії з автоматизацій відправляють самі." },
          { icon: "QrCode", title: "Відмітка приходу в Telegram", text: "Людина сканує QR на вході або натискає кнопку в боті — явка вже в системі, рецепція нічого не вводить." },
          { icon: "Megaphone", title: "Канал церкви", text: "Оголошення й події публікуються в канал прямо з «Моєї Церкви» — з посиланням на реєстрацію." },
          { icon: "Contact", title: "Прив'язка до картки", text: "Кожен, хто написав боту, автоматично з'єднується зі своєю карткою в базі. Номер телефону — і людина знайдена." },
          { icon: "Activity", title: "Статус доставки", text: "Бачите, кому доставлено, хто прочитав, хто заблокував бота — і кого треба дістати іншим каналом." },
        ],
        steps: [
          { title: "Підключіть бота", text: "Створіть бота через BotFather, вставте токен у налаштування — «Моя Церква» зробить решту за хвилину." },
          { title: "Запросіть людей", text: "Надішліть посилання або QR-код — людина натискає «Старт», і її картка прив'язується до Telegram." },
          { title: "Надсилайте й нагадуйте", text: "Розсилки, нагадування та відмітка приходу тепер працюють через Telegram — з бази, а не з телефона адміністратора." },
        ],
        audience: [
          { role: "leader", text: "Пише своїй групі з бази — усім або вибірково — і бачить, хто прочитав." },
          { role: "volunteer", text: "Отримує нагадування про служіння за день і підтверджує участь однією кнопкою." },
          { role: "member", text: "Дізнається про події й реєструється, не встановлюючи нових застосунків." },
          { role: "reception", text: "Відмічає прихід за QR замість списків на папері." },
        ],
        faq: [
          { q: "Чи потрібно всім переходити в один чат?", a: "Ні. Люди лишаються у своїх чатах, а повідомлення від церкви приходять від бота особисто. Загальний канал — за бажанням." },
          { q: "Чим це відрізняється від модуля «Telegram-бот»?", a: "Інтеграція з'єднує Telegram з базою: розсилки, нагадування, відмітка приходу. Модуль «Telegram-бот» — це власний бот церкви з меню: розклад, реєстрації, відповіді на запитання. Вони працюють разом." },
          { q: "Що буде, якщо людина не має Telegram?", a: "Розсилка сама піде через інший канал — SMS чи Viber, залежно від того, що вказано у картці людини." },
          { q: "Чи бачить бот особисті переписки?", a: "Ні. Бот отримує лише те, що людина пише саме йому. Доступу до чатів, груп чи контактів він не має." },
        ],
        mock: {
          kind: "chat",
          title: "Telegram · нагадування",
          subtitle: "Служителі неділі · 24 отримувачі",
          messages: [
            { from: "bot", text: "Олено, у неділю ви на прославленні о 10:00. Підтвердіть участь.", time: "Пт 18:00" },
            { from: "user", text: "Підтверджую", time: "Пт 18:04" },
            { from: "bot", text: "Дякуємо. Репетиція в суботу о 17:00, зала №2." },
            { from: "user", text: "Чи можна приїхати на 17:30?" },
            { from: "bot", text: "Передав Андрію. Нагадаю за годину до репетиції." },
          ],
          input: "Написати боту…",
        },
      },
      en: {
        seoTitle: "Telegram — My Church module",
        seoDescription: "Telegram in My Church: campaigns by group and filter, reminders for volunteers, QR check-in and delivery status — from the church database, no new apps.",
        title: "Church messages reach people where they already are",
        lead: "Telegram is where your congregation already talks. Connect the church's channel and bot to My Church, and reminders, campaigns and check-in reach people without a single new app.",
        highlights: [
          "Campaigns by group and filter",
          "Reminders for volunteers a day and an hour ahead",
          "Check-in by QR or a single tap",
          "Delivery and read reports",
        ],
        features: [
          { icon: "Send", title: "Campaigns from the database", text: "Pick a segment — \"youth\", \"no group\", \"Sunday team\" — and the message goes to them alone, not the whole chat." },
          { icon: "BellRing", title: "Hands-free reminders", text: "A day before the service, an hour before the group meets, on a birthday — automation scenarios send them on their own." },
          { icon: "QrCode", title: "Check-in in Telegram", text: "A person scans the QR at the door or taps a button in the bot — attendance is recorded, reception types nothing." },
          { icon: "Megaphone", title: "Church channel", text: "Announcements and events are posted to the channel straight from My Church — with a registration link attached." },
          { icon: "Contact", title: "Linked to the profile", text: "Everyone who writes to the bot is matched to their profile automatically. A phone number is all it takes." },
          { icon: "Activity", title: "Delivery status", text: "See who received it, who read it, who blocked the bot — and who needs reaching through another channel." },
        ],
        steps: [
          { title: "Connect the bot", text: "Create a bot via BotFather, paste the token into settings — My Church does the rest in a minute." },
          { title: "Invite people", text: "Send a link or a QR code — a person taps Start and their profile is linked to Telegram." },
          { title: "Send and remind", text: "Campaigns, reminders and check-in now run through Telegram — from the database, not the admin's phone." },
        ],
        audience: [
          { role: "leader", text: "Writes to their group from the database — everyone or a few — and sees who has read it." },
          { role: "volunteer", text: "Gets a reminder about the service a day ahead and confirms with a single button." },
          { role: "member", text: "Hears about events and registers without installing a new app." },
          { role: "reception", text: "Runs QR check-in instead of paper lists." },
        ],
        faq: [
          { q: "Does everyone have to move into one chat?", a: "No. People stay in their own chats; messages from the church arrive from the bot personally. A shared channel is optional." },
          { q: "How is this different from the Telegram bot module?", a: "The integration connects Telegram to the database: campaigns, reminders, check-in. The Telegram bot module is the church's own bot with a menu: schedule, sign-ups, answers. They work together." },
          { q: "What if someone doesn't use Telegram?", a: "The campaign goes out through another channel — SMS or Viber — depending on what's set in their profile." },
          { q: "Can the bot see private conversations?", a: "No. The bot only receives what a person writes to it directly. It has no access to chats, groups or contacts." },
        ],
        mock: {
          kind: "chat",
          title: "Telegram · reminders",
          subtitle: "Sunday team · 24 recipients",
          messages: [
            { from: "bot", text: "Olena, you're on worship this Sunday at 10:00. Please confirm.", time: "Fri 18:00" },
            { from: "user", text: "Confirmed", time: "Fri 18:04" },
            { from: "bot", text: "Thank you. Rehearsal is on Saturday at 17:00, hall 2." },
            { from: "user", text: "Can I come at 17:30?" },
            { from: "bot", text: "Passed on to Andrii. I'll remind you an hour before." },
          ],
          input: "Message the bot…",
        },
      },
    },
  },
  {
    id: "viber",
    group: "integrations",
    related: ["campaigns", "telegram", "turbosms", "automations"],
    copy: {
      ua: {
        seoTitle: "Viber — модуль «Моя Церква»",
        seoDescription: "Viber у «Моїй Церкві»: розсилки й нагадування для старшого покоління, ті самі сегменти, що й у Telegram, звіт про доставку та резерв через SMS.",
        title: "Нагадування доходять і до тих, хто не в Telegram",
        lead: "У багатьох церквах старше покоління живе у Viber. Підключіть Viber до «Моєї Церкви» — і розсилки про служіння, події та зустрічі груп приходитимуть їм звичним способом, з тієї ж бази.",
        highlights: [
          "Ті самі сегменти, що й у Telegram та SMS",
          "Нагадування про служіння та зустрічі",
          "Звіт про доставку й прочитання",
          "Автоматичний резерв через SMS",
        ],
        features: [
          { icon: "MessageCircle", title: "Від імені церкви", text: "Люди бачать назву й логотип церкви, а не незнайомий номер. Довіра з першого повідомлення." },
          { icon: "Users", title: "Один сегмент — усі канали", text: "Фільтр «сімейна група «Центр»» — той самий для Telegram, Viber і SMS. Не треба збирати списки заново." },
          { icon: "BellRing", title: "Нагадування за розкладом", text: "За день до служіння чи зустрічі, у день народження — повідомлення йде автоматично зі сценарію." },
          { icon: "BarChart3", title: "Доставлено та прочитано", text: "По кожній розсилці видно, скільки доставлено, хто прочитав і кому не дійшло." },
          { icon: "Repeat", title: "Резерв через SMS", text: "Якщо у людини немає Viber, повідомлення само піде через TurboSMS — ніхто не лишиться без нагадування." },
        ],
        steps: [
          { title: "Підключіть акаунт", text: "Створіть бізнес-акаунт Viber для церкви, додайте ключ у налаштування — підключення займає кілька хвилин." },
          { title: "Позначте канал у картках", text: "Під час імпорту або через форму людина обирає, де їй зручніше отримувати повідомлення." },
          { title: "Запускайте розсилки", text: "Пишіть один текст, обирайте сегмент — «Моя Церква» доставить через Viber тим, хто його обрав." },
        ],
        audience: [
          { role: "pastor", text: "Знає, що оголошення дійшло до всієї церкви, а не тільки до молоді." },
          { role: "leader", text: "Нагадує старшій групі про зустріч — і бачить, хто прочитав." },
          { role: "member", text: "Отримує нагадування у звичному месенджері, без нових застосунків." },
        ],
        faq: [
          { q: "Чи потрібно людям щось встановлювати?", a: "Ні. Якщо Viber уже є на телефоні, достатньо один раз натиснути «Підписатися» на повідомлення церкви." },
          { q: "Чи можна надіслати одну розсилку в Telegram і Viber одночасно?", a: "Так. Пишете один текст, обираєте сегмент — система сама розподілить за каналом, який вказано в картці людини." },
          { q: "Чи можна відправляти зображення й кнопки?", a: "Так: картинка з афішею, кнопка «Зареєструватися» чи «Підтвердити участь» — і відповідь одразу потрапляє у базу." },
        ],
        mock: {
          kind: "stats",
          title: "Viber · розсилки",
          subtitle: "Вересень · 6 розсилок",
          kpis: [
            { label: "Надіслано", value: "1 240" },
            { label: "Доставлено", value: "96%", trend: "+2%" },
            { label: "Прочитано", value: "81%", trend: "+5%" },
          ],
          bars: [
            { label: "Недільне служіння", value: 92 },
            { label: "Молитовний вечір", value: 78 },
            { label: "Сімейна група", value: 88 },
            { label: "Дні народження", value: 95 },
            { label: "Конференція", value: 71 },
            { label: "Табір", value: 64 },
            { label: "Збори лідерів", value: 85 },
          ],
          barsTitle: "Прочитано за розсилками, %",
        },
        pipeline: {
          title: "Шлях розсилки у Viber",
          text: "Приклад: нагадування старшій групі про молитовний вечір. Кожен етап видно в картці розсилки.",
          stages: [
            { title: "Сегмент", tone: "neutral", text: "Адміністратор обирає фільтр — група «Надія», вік 60+. Видно, скільки людей отримає Viber.", auto: "Ділить список за каналом, позначеним у картці кожної людини." },
            { title: "Текст і кнопка", tone: "brand", text: "Один текст, картинка з афішею і кнопка «Підтверджу участь».", auto: "Показує попередній перегляд у тому вигляді, в якому людина побачить його на телефоні." },
            { title: "Відправка", tone: "violet", text: "Повідомлення йде від імені церкви: люди бачать назву й логотип, а не незнайомий номер.", auto: "Передає чергу у Viber і фіксує час відправки кожного повідомлення." },
            { title: "Доставка", tone: "amber", text: "Видно, кому доставлено й хто прочитав. Хто натиснув «Підтверджу», вже у списку учасників.", auto: "Оновлює статуси й додає відповіді у картку події." },
            { title: "Резерв", tone: "green", text: "Кому не дійшло через Viber, отримує той самий текст як SMS.", auto: "Запускає відправку через TurboSMS і дописує результат у ту саму картку розсилки." },
          ],
        },
      },
      en: {
        seoTitle: "Viber — My Church module",
        seoDescription: "Viber in My Church: campaigns and reminders for the older generation, the same segments as Telegram, delivery and read reports and an SMS fallback.",
        title: "Reminders that reach the people who aren't on Telegram",
        lead: "In many churches the older generation lives in Viber. Connect it to My Church and campaigns about services, events and group meetings reach them the way they're used to — from the same database.",
        highlights: [
          "The same segments as Telegram and SMS",
          "Reminders about services and meetings",
          "Delivery and read reports",
          "Automatic SMS fallback",
        ],
        features: [
          { icon: "MessageCircle", title: "Sent in the church's name", text: "People see the church's name and logo, not an unknown number. Trust from the first message." },
          { icon: "Users", title: "One segment, every channel", text: "The filter \"Centre family group\" is the same for Telegram, Viber and SMS. No rebuilding lists." },
          { icon: "BellRing", title: "Scheduled reminders", text: "A day before the service or meeting, on a birthday — the message goes out automatically from a scenario." },
          { icon: "BarChart3", title: "Delivered and read", text: "For every campaign you see how many were delivered, who read it and who it didn't reach." },
          { icon: "Repeat", title: "SMS fallback", text: "If someone doesn't have Viber, the message goes out via TurboSMS by itself — nobody misses a reminder." },
        ],
        steps: [
          { title: "Connect the account", text: "Create a Viber business account for the church, add the key in settings — it takes a few minutes." },
          { title: "Mark the channel in profiles", text: "During import or via a form, each person picks where they'd rather receive messages." },
          { title: "Run campaigns", text: "Write one text, choose a segment — My Church delivers via Viber to those who chose it." },
        ],
        audience: [
          { role: "pastor", text: "Knows the announcement reached the whole church, not only the young." },
          { role: "leader", text: "Reminds the older group about the meeting — and sees who has read it." },
          { role: "member", text: "Gets reminders in the messenger they already use, no new apps." },
        ],
        faq: [
          { q: "Do people need to install anything?", a: "No. If Viber is already on the phone, one tap on Subscribe to the church's messages is enough." },
          { q: "Can one campaign go to Telegram and Viber at once?", a: "Yes. Write one text, choose a segment — the system splits it by the channel set in each person's profile." },
          { q: "Can I send images and buttons?", a: "Yes: a poster image, a Register or Confirm button — and the answer lands in the database straight away." },
        ],
        mock: {
          kind: "stats",
          title: "Viber · campaigns",
          subtitle: "September · 6 campaigns",
          kpis: [
            { label: "Sent", value: "1,240" },
            { label: "Delivered", value: "96%", trend: "+2%" },
            { label: "Read", value: "81%", trend: "+5%" },
          ],
          bars: [
            { label: "Sunday service", value: 92 },
            { label: "Prayer evening", value: 78 },
            { label: "Family group", value: 88 },
            { label: "Birthdays", value: 95 },
            { label: "Conference", value: 71 },
            { label: "Camp", value: 64 },
            { label: "Leaders meeting", value: 85 },
          ],
          barsTitle: "Read rate by campaign, %",
        },
        pipeline: {
          title: "A campaign's path through Viber",
          text: "Example: reminding the older group about the prayer evening. Every stage is visible on the campaign card.",
          stages: [
            { title: "Segment", tone: "neutral", text: "The administrator picks a filter — Nadiya group, age 60+. You see how many will get it on Viber.", auto: "Splits the list by the channel marked in each person's profile." },
            { title: "Text and button", tone: "brand", text: "One text, a poster image and a \"Count me in\" button.", auto: "Shows a preview exactly as the person will see it on their phone." },
            { title: "Sending", tone: "violet", text: "The message goes out in the church's name: people see the name and logo, not an unknown number.", auto: "Hands the queue to Viber and records the send time of every message." },
            { title: "Delivery", tone: "amber", text: "You see who received it and who read it. Anyone who tapped \"Count me in\" is on the attendee list.", auto: "Updates statuses and adds the replies to the event card." },
            { title: "Fallback", tone: "green", text: "Whoever wasn't reached on Viber gets the same text as an SMS.", auto: "Starts the TurboSMS send and writes the result onto the same campaign card." },
          ],
        },
      },
    },
  },
  {
    id: "instagram",
    group: "integrations",
    related: ["forms", "onboarding", "people", "automations"],
    copy: {
      ua: {
        seoTitle: "Instagram — модуль «Моя Церква»",
        seoDescription: "Instagram Direct у «Моїй Церкві»: спільна скринька, повідомлення стає карткою людини одним натисканням, швидкі відповіді й онбординг з першого повідомлення.",
        title: "Кожне повідомлення в Direct стає людиною в базі",
        lead: "Новенькі пишуть церкві в Instagram частіше, ніж дзвонять. Підключіть Direct до «Моєї Церкви» — і кожне «а коли у вас служіння?» стане карткою людини, а не загубленим повідомленням.",
        highlights: [
          "Повідомлення з Direct у спільній скриньці команди",
          "Заявка стає карткою одним натисканням",
          "Шаблони відповідей на типові запитання",
          "Історія листування у картці людини",
        ],
        features: [
          { icon: "Inbox", title: "Спільна скринька", text: "Усі повідомлення з Direct — в одному місці для команди. Видно, хто відповів, а хто ще чекає." },
          { icon: "UserPlus", title: "З повідомлення — у картку", text: "Одне натискання — і людина з Instagram стає новеньким у базі з відкритим шляхом онбордингу." },
          { icon: "MessageSquare", title: "Швидкі відповіді", text: "«Служіння в неділю о 10:00, адреса…» — шаблони на типові запитання, які відправляються за секунду." },
          { icon: "Camera", title: "Заявки з постів і сторіс", text: "Посилання «Записатися» під анонсом веде у форму — реєстрація потрапляє в базу з позначкою «з Instagram»." },
          { icon: "Rocket", title: "Запуск онбордингу", text: "Написала людина — автоматизація ставить відповідального і нагадує йому подзвонити наступного дня." },
        ],
        steps: [
          { title: "Підключіть акаунт", text: "Авторизуйте бізнес-акаунт Instagram церкви — це стандартне підключення через Meta, без передачі пароля." },
          { title: "Розподіліть відповіді", text: "Призначте, хто з команди відповідає в Direct, і додайте шаблони на типові запитання." },
          { title: "Перетворюйте на людей", text: "Кожне звернення — у картку та в онбординг. Через місяць ви бачите, скільки людей прийшло саме з Instagram." },
        ],
        audience: [
          { role: "reception", text: "Відповідає на всі «а де?» і «а коли?» з одного екрана і не губить жодного повідомлення." },
          { role: "visitor", text: "Пише туди, де зручно, — і отримує відповідь, запрошення та контакт живої людини." },
          { role: "pastor", text: "Бачить, скільки новеньких приходить з Instagram і хто з них дійшов до групи." },
        ],
        faq: [
          { q: "Коли інтеграція буде доступна?", a: "Інтеграція з Instagram зараз розгортається поетапно. Напишіть нам — ми підключимо вашу церкву до раннього доступу." },
          { q: "Чи потрібно давати комусь пароль від Instagram?", a: "Ні. Підключення відбувається через офіційну авторизацію Meta: ви даєте дозвіл на повідомлення, а пароль лишається у вас." },
          { q: "Хто бачить переписку з Direct?", a: "Лише ті, кому ви відкрили доступ до скриньки. Історія зберігається в картці людини з тими самими правами, що й нотатки." },
          { q: "Чи можна відповідати з телефона?", a: "Так, зі спільної скриньки в мобільній версії «Моєї Церкви» — або як звикли, в Instagram: повідомлення все одно синхронізуються." },
        ],
        mock: {
          kind: "chat",
          title: "Instagram Direct",
          subtitle: "Марія Іщенко · нова заявка",
          messages: [
            { from: "user", text: "Добрий день. А коли у вас служіння і чи є дитяча кімната?", time: "Сб 21:12" },
            { from: "bot", text: "Доброго дня, Маріє. Служіння в неділю о 10:00, дитяча кімната працює з 9:45.", time: "Сб 21:15" },
            { from: "user", text: "Супер, прийдемо з донькою в цю неділю" },
            { from: "bot", text: "Чудово. Залишите номер телефону? Надішлемо адресу й нагадаємо в суботу." },
            { from: "user", text: "Так, +380 67 ••• 41 12" },
            { from: "bot", text: "Дякуємо. Картку створено · Онбординг: крок 1 з 5" },
          ],
          input: "Швидка відповідь…",
        },
        pipeline: {
          title: "Шлях повідомлення з Direct",
          text: "Так звернення проходить через команду після того, як інтеграцію відкрито для вашої церкви.",
          stages: [
            { title: "Прийшло в Direct", tone: "neutral", text: "Людина пише під анонсом або зі сторіс. Повідомлення з'являється у спільній скриньці команди.", auto: "Перевіряє, чи є вже картка з таким іменем або номером, і показує її поруч." },
            { title: "Відповіли", tone: "brand", text: "Хтось із команди відповідає шаблоном: час служіння, адреса, дитяча кімната.", auto: "Ставить того, хто відповів, відповідальним і позначає розмову як «в роботі»." },
            { title: "Стало карткою", tone: "violet", text: "Одне натискання — і людина з Direct з'являється в базі з позначкою «з Instagram».", auto: "Переносить листування в картку й відкриває шлях онбордингу." },
            { title: "Онбординг", tone: "green", text: "Відповідальний дзвонить, запрошує на служіння і знайомить із лідером найближчої групи.", auto: "Нагадує подзвонити наступного дня і питає про результат через тиждень." },
          ],
        },
      },
      en: {
        seoTitle: "Instagram — My Church module",
        seoDescription: "Instagram Direct in My Church: a shared team inbox, a message turned into a profile in one tap, quick replies and onboarding from the first message.",
        title: "Every Direct message becomes a person in your database",
        lead: "Newcomers message the church on Instagram more often than they call. Connect Direct to My Church and every \"when is your service?\" becomes a profile, not a lost message.",
        highlights: [
          "Direct messages in a shared team inbox",
          "A request becomes a profile in one tap",
          "Reply templates for common questions",
          "Conversation history in the profile",
        ],
        features: [
          { icon: "Inbox", title: "Shared inbox", text: "Every Direct message in one place for the team. You see who has replied and who is still waiting." },
          { icon: "UserPlus", title: "From message to profile", text: "One tap and a person from Instagram becomes a newcomer in the database with an onboarding path open." },
          { icon: "MessageSquare", title: "Quick replies", text: "\"Service is on Sunday at 10:00, the address is…\" — templates for common questions, sent in a second." },
          { icon: "Camera", title: "Requests from posts and stories", text: "A Sign up link under an announcement leads to a form — the registration lands in the database tagged \"from Instagram\"." },
          { icon: "Rocket", title: "Onboarding kicks in", text: "Someone wrote — automation assigns an owner and reminds them to call the next day." },
        ],
        steps: [
          { title: "Connect the account", text: "Authorise the church's Instagram business account — a standard Meta connection, no password handed over." },
          { title: "Assign replies", text: "Decide who on the team answers in Direct and add templates for common questions." },
          { title: "Turn them into people", text: "Every enquiry becomes a profile and enters onboarding. A month later you see how many came from Instagram." },
        ],
        audience: [
          { role: "reception", text: "Answers every \"where?\" and \"when?\" from one screen and never loses a message." },
          { role: "visitor", text: "Writes where it's convenient — and gets a reply, an invitation and a real person's contact." },
          { role: "pastor", text: "Sees how many newcomers come from Instagram and which of them reached a group." },
        ],
        faq: [
          { q: "When will the integration be available?", a: "The Instagram integration is being rolled out in stages. Write to us and we'll add your church to early access." },
          { q: "Do I have to give anyone the Instagram password?", a: "No. The connection goes through Meta's official authorisation: you grant access to messages, the password stays with you." },
          { q: "Who can see Direct conversations?", a: "Only those you've given inbox access to. History is stored in the person's profile with the same permissions as notes." },
          { q: "Can I reply from my phone?", a: "Yes, from the shared inbox in the My Church mobile version — or as usual in Instagram: messages sync either way." },
        ],
        mock: {
          kind: "chat",
          title: "Instagram Direct",
          subtitle: "Maria Ishchenko · new request",
          messages: [
            { from: "user", text: "Hi. When are your services, and is there a kids' room?", time: "Sat 21:12" },
            { from: "bot", text: "Hello Maria. The service is on Sunday at 10:00, the kids' room opens at 9:45.", time: "Sat 21:15" },
            { from: "user", text: "Great, we'll come with our daughter this Sunday" },
            { from: "bot", text: "Lovely. Leave a phone number? We'll send the address and remind you on Saturday." },
            { from: "user", text: "Sure, +380 67 ••• 41 12" },
            { from: "bot", text: "Thank you. Profile created · Onboarding: step 1 of 5" },
          ],
          input: "Quick reply…",
        },
        pipeline: {
          title: "A Direct message's path",
          text: "This is how an enquiry moves through the team once the integration is open for your church.",
          stages: [
            { title: "Arrives in Direct", tone: "neutral", text: "Someone writes under an announcement or from a story. The message lands in the shared team inbox.", auto: "Checks whether a profile with that name or number already exists and shows it alongside." },
            { title: "Answered", tone: "brand", text: "Someone on the team replies with a template: service time, address, kids' room.", auto: "Makes whoever replied the owner and marks the conversation as in progress." },
            { title: "Becomes a profile", tone: "violet", text: "One tap and the person from Direct appears in the database tagged \"from Instagram\".", auto: "Moves the conversation into the profile and opens the onboarding path." },
            { title: "Onboarding", tone: "green", text: "The owner calls, invites them to a service and introduces the nearest group's leader.", auto: "Reminds the owner to call the next day and asks about the outcome a week later." },
          ],
        },
      },
    },
  },
  {
    id: "whatsapp",
    group: "integrations",
    related: ["campaigns", "viber", "telegram", "people"],
    copy: {
      ua: {
        seoTitle: "WhatsApp — модуль «Моя Церква»",
        seoDescription: "WhatsApp у «Моїй Церкві»: спільна скринька для розмов, розсилки за тими самими сегментами, що й у Telegram, затверджені шаблони та історія в картці людини.",
        title: "Ті, хто живе у WhatsApp, не випадають із розсилок",
        lead: "Частина громади — за кордоном, частина спілкується з місіонерами чи гостями з інших країн, і всі вони у WhatsApp. Підключіть його до «Моєї Церкви» — і листування та розсилки підуть з тієї ж бази, що й Telegram.",
        highlights: [
          "Спільна скринька команди для розмов",
          "Розсилки за тими самими сегментами",
          "Шаблони повідомлень, затверджені WhatsApp",
          "Історія листування у картці людини",
        ],
        features: [
          { icon: "MessagesSquare", title: "Розмови в одному місці", text: "Хто написав, хто відповів, що ще чекає — уся переписка команди з людьми на одному екрані, а не на п'яти телефонах." },
          { icon: "Send", title: "Розсилки за сегментами", text: "«Діаспора в Польщі», «команда табору», «батьки Дитячого містечка» — той самий фільтр, що й для Telegram." },
          { icon: "LayoutTemplate", title: "Затверджені шаблони", text: "WhatsApp вимагає шаблони для масових повідомлень. Ми готуємо їх разом із вами — нагадування, привітання, підтвердження." },
          { icon: "Globe", title: "Церква без кордонів", text: "Члени церкви за кордоном отримують нагадування й новини так само, як ті, хто в залі." },
          { icon: "Contact", title: "Прив'язка до картки", text: "Номер телефону з'єднує розмову з людиною в базі — історія листування зберігається у картці." },
        ],
        steps: [
          { title: "Підключіть номер", text: "Зареєструйте бізнес-номер церкви у WhatsApp Business і додайте його в налаштування «Моєї Церкви»." },
          { title: "Затвердіть шаблони", text: "Ми допоможемо оформити шаблони нагадувань і привітань, щоб їх прийняли з першого разу." },
          { title: "Пишіть і розсилайте", text: "Розмови ведуться зі спільної скриньки, розсилки — з тих самих сегментів, що й у решті каналів." },
        ],
        audience: [
          { role: "pastor", text: "Тримає зв'язок із членами церкви, які виїхали, — без окремого телефона й списків." },
          { role: "leader", text: "Пише групі, частина якої за кордоном, і бачить відповіді в одному місці." },
          { role: "member", text: "Отримує новини й нагадування в месенджері, яким користується щодня." },
        ],
        faq: [
          { q: "Коли можна буде підключити WhatsApp?", a: "Інтеграція розгортається поступово. Напишіть нам — додамо вашу церкву до раннього доступу і допоможемо з підключенням." },
          { q: "Чи потрібен окремий номер телефону?", a: "Так, WhatsApp Business потребує номера, не прив'язаного до особистого акаунта. Підійде окрема SIM-карта церкви." },
          { q: "Чи можна писати з особистого WhatsApp пастора?", a: "Розмови команди ведуться з номера церкви. Так історія лишається в церкві, навіть коли людина з команди змінюється." },
          { q: "Чи є ліміти на розсилки?", a: "WhatsApp обмежує масові повідомлення шаблонами і поступово розширює ліміт для нових номерів. «Моя Церква» показує поточний ліміт і відправляє чергу в його межах." },
        ],
        mock: {
          kind: "list",
          title: "WhatsApp · розмови",
          subtitle: "5 нових · 2 очікують відповіді",
          items: [
            { title: "Ірина Шевчук", sub: "Дякую, будемо в неділю", meta: "12:40", badge: { label: "Відповіли", tone: "green" } },
            { title: "Андрій Мельник", sub: "Чи є ще місця на табір?", meta: "11:15", badge: { label: "Очікує", tone: "amber" } },
            { title: "Група «Варшава»", sub: "Розсилка: молитовний вечір", meta: "Вчора", badge: { label: "Доставлено 18/19", tone: "brand" } },
            { title: "Наталя Рудь", sub: "Підтвердила участь у служінні", meta: "Вчора", badge: { label: "Готово", tone: "neutral" } },
            { title: "Василь Панченко", sub: "Хочу приєднатися до групи", meta: "Пн", badge: { label: "Новенький", tone: "brand" } },
          ],
          footer: "Скринька: усі · мої · без відповіді",
        },
      },
      en: {
        seoTitle: "WhatsApp — My Church module",
        seoDescription: "WhatsApp in My Church: a shared inbox for conversations, campaigns by the same segments as Telegram, approved templates and history in the profile.",
        title: "No one on WhatsApp falls out of the loop",
        lead: "Part of the congregation is abroad, part talks to missionaries or guests from other countries, and all of them are on WhatsApp. Connect it to My Church and conversations and campaigns run from the same database as Telegram.",
        highlights: [
          "Shared team inbox for conversations",
          "Campaigns by the same segments",
          "Message templates approved by WhatsApp",
          "History in the person's profile",
        ],
        features: [
          { icon: "MessagesSquare", title: "Conversations in one place", text: "Who wrote, who replied, what's still waiting — the team's whole correspondence on one screen, not on five phones." },
          { icon: "Send", title: "Campaigns by segment", text: "\"Diaspora in Poland\", \"camp team\", \"Kids Town parents\" — the same filter as for Telegram." },
          { icon: "LayoutTemplate", title: "Approved templates", text: "WhatsApp requires templates for bulk messages. We prepare them with you — reminders, greetings, confirmations." },
          { icon: "Globe", title: "A church without borders", text: "Members abroad get reminders and news just like those sitting in the hall." },
          { icon: "Contact", title: "Linked to the profile", text: "The phone number matches the conversation to a person in the database — history is kept in the profile." },
        ],
        steps: [
          { title: "Connect a number", text: "Register the church's business number in WhatsApp Business and add it in My Church settings." },
          { title: "Approve templates", text: "We'll help you word reminder and greeting templates so they're accepted first time." },
          { title: "Write and send", text: "Conversations run from the shared inbox, campaigns from the same segments as every other channel." },
        ],
        audience: [
          { role: "pastor", text: "Stays in touch with members who moved away — without a separate phone or lists." },
          { role: "leader", text: "Writes to a group that's partly abroad and sees the replies in one place." },
          { role: "member", text: "Gets news and reminders in the messenger they use every day." },
        ],
        faq: [
          { q: "When can I connect WhatsApp?", a: "The integration is being rolled out gradually. Write to us — we'll add your church to early access and help with the setup." },
          { q: "Do I need a separate phone number?", a: "Yes, WhatsApp Business needs a number not tied to a personal account. A separate church SIM card will do." },
          { q: "Can I write from the pastor's personal WhatsApp?", a: "Team conversations run from the church's number. That way the history stays with the church even when someone on the team changes." },
          { q: "Are there limits on campaigns?", a: "WhatsApp restricts bulk messages to templates and raises the limit gradually for new numbers. My Church shows the current limit and sends the queue within it." },
        ],
        mock: {
          kind: "list",
          title: "WhatsApp · conversations",
          subtitle: "5 new · 2 awaiting a reply",
          items: [
            { title: "Iryna Shevchuk", sub: "Thanks, we'll be there Sunday", meta: "12:40", badge: { label: "Replied", tone: "green" } },
            { title: "Andrii Melnyk", sub: "Any places left for camp?", meta: "11:15", badge: { label: "Waiting", tone: "amber" } },
            { title: "Warsaw group", sub: "Campaign: prayer evening", meta: "Yesterday", badge: { label: "Delivered 18/19", tone: "brand" } },
            { title: "Natalia Rud", sub: "Confirmed for the service", meta: "Yesterday", badge: { label: "Done", tone: "neutral" } },
            { title: "Vasyl Panchenko", sub: "I'd like to join a group", meta: "Mon", badge: { label: "Newcomer", tone: "brand" } },
          ],
          footer: "Inbox: all · mine · unanswered",
        },
      },
    },
  },
  {
    id: "turbosms",
    group: "integrations",
    related: ["campaigns", "viber", "automations", "events"],
    copy: {
      ua: {
        seoTitle: "TurboSMS — модуль «Моя Церква»",
        seoDescription: "TurboSMS у «Моїй Церкві»: масові SMS по Україні за секунди, назва церкви замість номера, статус доставки по кожному номеру й резерв для Telegram і Viber.",
        title: "SMS доходить кожному — навіть без інтернету",
        lead: "Коли треба, щоб повідомлення побачили всі — і бабуся без смартфона, і той, у кого вимкнений Telegram, — працює SMS. TurboSMS відправляє тисячі повідомлень по Україні за секунди, прямо з «Моєї Церкви».",
        highlights: [
          "Назва церкви замість незнайомого номера",
          "Розсилка на сегмент за хвилину",
          "Статус доставки по кожному номеру",
          "Резервний канал для Telegram і Viber",
        ],
        features: [
          { icon: "Smartphone", title: "Від імені церкви", text: "Замість «+380…» люди бачать назву церкви в полі відправника. Зареєструємо альфа-ім'я разом із вами." },
          { icon: "Zap", title: "Тисячі повідомлень за секунди", text: "Уся церква — 400 номерів — отримує термінове оголошення за той час, поки ви дочитаєте це речення." },
          { icon: "ClipboardCheck", title: "Статус по кожному номеру", text: "Доставлено, у черзі, не доставлено — і одразу список номерів, які варто перевірити в картках." },
          { icon: "Repeat", title: "Резерв для месенджерів", text: "Не дійшло через Telegram чи Viber — та сама розсилка автоматично піде SMS. Без окремої дії." },
          { icon: "Timer", title: "Запланована відправка", text: "Нагадування про служіння — у суботу о 18:00, про зустріч групи — за 2 години. Поставили — і забули." },
        ],
        steps: [
          { title: "Підключіть TurboSMS", text: "Вставте API-ключ із кабінету TurboSMS у налаштування — розсилки готові за хвилину." },
          { title: "Зареєструйте ім'я відправника", text: "Оформіть альфа-ім'я церкви — ми підкажемо, які документи потрібні." },
          { title: "Надсилайте з бази", text: "Обирайте сегмент, пишіть текст, бачте кількість символів і отримувачів до відправки." },
        ],
        audience: [
          { role: "pastor", text: "Впевнений, що термінове оголошення — зміна часу служіння чи скасування — побачили всі." },
          { role: "leader", text: "Нагадує групі про зустріч тим, хто не читає месенджери." },
          { role: "reception", text: "Надсилає підтвердження реєстрації й нагадування гостям без ручного набору." },
        ],
        faq: [
          { q: "Чи можна надсилати SMS з назвою церкви замість номера?", a: "Так. Альфа-ім'я — це назва до 11 латинських символів, яку реєструє TurboSMS. Ми допоможемо оформити." },
          { q: "Що буде з довгими повідомленнями?", a: "SMS ділиться на частини по 70 символів кирилицею. Редактор показує кількість частин до відправки, щоб ви не здивувалися." },
          { q: "Чи можна відписатися від SMS?", a: "Так. У картці людини є позначка «не надсилати SMS», і система її поважає в усіх розсилках — навіть автоматичних." },
          { q: "Чи підходить для нагадувань служителям?", a: "Так — через автоматизації: за день до служіння служитель отримує SMS, якщо ще не підтвердив участь у месенджері." },
        ],
        mock: {
          kind: "table",
          title: "TurboSMS · розсилки",
          subtitle: "Відправник: DZHERELO · вересень",
          columns: ["Розсилка", "Надіслано", "Доставлено", "Дата"],
          rows: [
            { cells: ["Перенесення служіння", "412", "409", "14 вер"], badge: { label: "Готово", tone: "green" } },
            { cells: ["Нагадування · неділя", "386", "380", "13 вер"], badge: { label: "Готово", tone: "green" } },
            { cells: ["Табір · оплата", "64", "64", "11 вер"], badge: { label: "Готово", tone: "green" } },
            { cells: ["Конференція · запрошення", "540", "527", "9 вер"], badge: { label: "Готово", tone: "green" } },
            { cells: ["Зустріч лідерів", "23", "—", "Сб 18:00"], badge: { label: "Заплановано", tone: "brand" } },
            { cells: ["Дні народження", "5", "4", "Сьогодні"], badge: { label: "1 не доставлено", tone: "amber" } },
          ],
        },
        pipeline: {
          title: "Шлях SMS-розсилки",
          text: "Приклад: перенесення недільного служіння. Від тексту до звіту — чотири етапи в одній картці.",
          stages: [
            { title: "Текст", tone: "neutral", text: "Адміністратор пише повідомлення. Редактор рахує символи й показує, на скільки частин розіб'ється SMS.", auto: "Підставляє ім'я людини та назву церкви у шаблон." },
            { title: "Отримувачі", tone: "brand", text: "Обираєте сегмент — уся церква чи окрема група. Видно точну кількість номерів до відправки.", auto: "Прибирає дублікати й тих, хто позначив у картці «не надсилати SMS»." },
            { title: "Відправка", tone: "violet", text: "Розсилка йде одразу або в запланований час — наприклад, у суботу о 18:00.", auto: "Передає чергу в TurboSMS і показує, скільки повідомлень уже пішло." },
            { title: "Звіт", tone: "green", text: "У картці розсилки видно по кожному номеру: доставлено, у черзі, не доставлено.", auto: "Позначає номери з помилкою в картках людей, щоб рецепція їх уточнила." },
          ],
        },
      },
      en: {
        seoTitle: "TurboSMS — My Church module",
        seoDescription: "TurboSMS in My Church: bulk SMS across Ukraine in seconds, the church's name as sender, delivery status per number and a fallback for Telegram and Viber.",
        title: "An SMS reaches everyone, even without internet",
        lead: "When a message must be seen by everyone — the grandmother without a smartphone and the person whose Telegram is off — SMS does the job. TurboSMS sends thousands of messages across Ukraine in seconds, straight from My Church.",
        highlights: [
          "The church's name instead of an unknown number",
          "A segment campaign in a minute",
          "Delivery status for every number",
          "Fallback channel for Telegram and Viber",
        ],
        features: [
          { icon: "Smartphone", title: "In the church's name", text: "Instead of \"+380…\" people see the church's name in the sender field. We'll register the sender name with you." },
          { icon: "Zap", title: "Thousands of messages in seconds", text: "The whole church — 400 numbers — gets an urgent announcement in the time it takes to finish this sentence." },
          { icon: "ClipboardCheck", title: "Status for every number", text: "Delivered, queued, failed — and an instant list of the numbers worth checking in profiles." },
          { icon: "Repeat", title: "Fallback for messengers", text: "Didn't get through on Telegram or Viber — the same campaign goes out as SMS automatically. No extra step." },
          { icon: "Timer", title: "Scheduled sending", text: "The service reminder on Saturday at 18:00, the group meeting reminder 2 hours ahead. Set it and forget it." },
        ],
        steps: [
          { title: "Connect TurboSMS", text: "Paste the API key from your TurboSMS account into settings — campaigns are ready in a minute." },
          { title: "Register a sender name", text: "Set up the church's alphanumeric sender name — we'll tell you which documents are needed." },
          { title: "Send from the database", text: "Choose a segment, write the text, see the character count and recipients before sending." },
        ],
        audience: [
          { role: "pastor", text: "Is certain that an urgent announcement — a time change or a cancellation — was seen by everyone." },
          { role: "leader", text: "Reminds the group about the meeting, including those who don't read messengers." },
          { role: "reception", text: "Sends registration confirmations and reminders to guests without dialling by hand." },
        ],
        faq: [
          { q: "Can SMS show the church's name instead of a number?", a: "Yes. The sender name is up to 11 Latin characters, registered through TurboSMS. We'll help you set it up." },
          { q: "What happens with long messages?", a: "An SMS is split into parts of 70 Cyrillic characters. The editor shows the number of parts before sending, so there are no surprises." },
          { q: "Can someone opt out of SMS?", a: "Yes. A person's profile has a \"no SMS\" flag, and the system respects it in every campaign — automated ones included." },
          { q: "Is it useful for volunteer reminders?", a: "Yes — through automations: a day before the service a volunteer gets an SMS if they haven't yet confirmed in a messenger." },
        ],
        mock: {
          kind: "table",
          title: "TurboSMS · campaigns",
          subtitle: "Sender: DZHERELO · September",
          columns: ["Campaign", "Sent", "Delivered", "Date"],
          rows: [
            { cells: ["Service moved", "412", "409", "14 Sep"], badge: { label: "Done", tone: "green" } },
            { cells: ["Reminder · Sunday", "386", "380", "13 Sep"], badge: { label: "Done", tone: "green" } },
            { cells: ["Camp · payment", "64", "64", "11 Sep"], badge: { label: "Done", tone: "green" } },
            { cells: ["Conference · invitation", "540", "527", "9 Sep"], badge: { label: "Done", tone: "green" } },
            { cells: ["Leaders meeting", "23", "—", "Sat 18:00"], badge: { label: "Scheduled", tone: "brand" } },
            { cells: ["Birthdays", "5", "4", "Today"], badge: { label: "1 failed", tone: "amber" } },
          ],
        },
        pipeline: {
          title: "An SMS campaign's path",
          text: "Example: the Sunday service is moved. From text to report — four stages on one card.",
          stages: [
            { title: "Text", tone: "neutral", text: "The administrator writes the message. The editor counts characters and shows how many parts it becomes.", auto: "Fills the person's name and the church's name into the template." },
            { title: "Recipients", tone: "brand", text: "You choose a segment — the whole church or one group. The exact number of numbers is shown before sending.", auto: "Removes duplicates and anyone whose profile is flagged \"no SMS\"." },
            { title: "Sending", tone: "violet", text: "The campaign goes out at once or at a scheduled time — Saturday at 18:00, for instance.", auto: "Hands the queue to TurboSMS and shows how many messages have gone out." },
            { title: "Report", tone: "green", text: "The campaign card shows each number: delivered, queued or failed.", auto: "Flags the failed numbers in people's profiles so reception can check them." },
          ],
        },
      },
    },
  },
  {
    id: "notion",
    group: "integrations",
    related: ["knowledge", "tables", "projects", "learning"],
    copy: {
      ua: {
        seoTitle: "Notion — модуль «Моя Церква»",
        seoDescription: "Двостороння синхронізація Notion і «Моєї Церкви»: сторінки стають базою знань, бази — таблицями, зміни підхоплюються за хвилину, права доступу зберігаються.",
        title: "Документи церкви живуть у Notion і в «Моїй Церкві» одночасно",
        lead: "Якщо команда вже веде інструкції, плани й бази в Notion — не переносьте нічого вручну. Двостороння синхронізація тримає документи й таблиці однаковими в обох місцях.",
        highlights: [
          "Двостороння синхронізація сторінок і баз",
          "Зміни підхоплюються за хвилину",
          "База знань церкви — з Notion без копіювання",
          "Права доступу «Моєї Церкви» зберігаються",
        ],
        features: [
          { icon: "RefreshCw", title: "В обидва боки", text: "Змінили сторінку в Notion — вона оновилась у базі знань. Додали людину в «Мою Церкву» — рядок з'явився в базі Notion." },
          { icon: "Database", title: "Бази ↔ таблиці", text: "Список служителів, інвентар, задачі проєкту — база Notion стає таблицею «Моєї Церкви» зі збереженням типів полів." },
          { icon: "BookOpen", title: "База знань без копіювання", text: "Інструкції для команди, сценарії служінь, політики — публікуються в базу знань прямо з Notion." },
          { icon: "GitBranch", title: "Вибіркова синхронізація", text: "Обирайте, які сторінки й бази синхронізувати. Особисті нотатки команди лишаються в Notion." },
          { icon: "Lock", title: "Права доступу", text: "Хто бачить документ у «Моїй Церкві», визначають її ж ролі — навіть якщо у Notion сторінка відкрита всім." },
        ],
        steps: [
          { title: "Підключіть робочий простір", text: "Авторизуйте Notion і оберіть сторінки та бази, до яких «Моя Церква» матиме доступ." },
          { title: "Зіставте поля", text: "Для баз — вкажіть, яка колонка Notion відповідає якому полю «Моєї Церкви». Одного разу." },
          { title: "Працюйте, де зручно", text: "Команда редагує в Notion, лідери читають у «Моїй Церкві» — і ніхто не запитує, яка версія актуальна." },
        ],
        audience: [
          { role: "pastor", text: "Читає плани й документи в «Моїй Церкві», не заходячи в Notion." },
          { role: "leader", text: "Відкриває інструкцію до служіння в базі знань — завжди актуальну." },
          { role: "hr", text: "Веде політики й чек-листи в Notion, а команда бачить їх у своїх ролях у «Моїй Церкві»." },
        ],
        faq: [
          { q: "Що станеться, якщо змінити документ в обох місцях одночасно?", a: "Перемагає остання збережена версія, а попередню ми зберігаємо в історії — нічого не втрачається." },
          { q: "Чи синхронізуються люди з бази «Моєї Церкви» у Notion?", a: "Так, якщо ви це увімкнете для конкретної бази. Нотатки з обмеженим доступом у Notion не передаються." },
          { q: "Як часто оновлюються дані?", a: "Зміни з Notion підхоплюються протягом хвилини. Зміни з «Моєї Церкви» потрапляють у Notion одразу." },
          { q: "Чи можна відключити Notion пізніше без втрати даних?", a: "Так. Усе, що було синхронізовано, лишається в «Моїй Церкві» як звичайні документи й таблиці." },
        ],
        mock: {
          kind: "list",
          title: "Notion · синхронізація",
          subtitle: "14 сторінок · 3 бази · оновлено щойно",
          items: [
            { title: "Сценарій недільного служіння", sub: "База знань · Служіння", meta: "2 хв тому", badge: { label: "Синхронізовано", tone: "green" } },
            { title: "Служителі 2026", sub: "База Notion → Таблиці", meta: "5 хв тому", badge: { label: "Синхронізовано", tone: "green" } },
            { title: "Інструкція для рецепції", sub: "База знань · Команда", meta: "Щойно", badge: { label: "Оновлюється", tone: "brand" } },
            { title: "План табору «Літо-2026»", sub: "Notion → Проєкти", meta: "Вчора", badge: { label: "Синхронізовано", tone: "green" } },
            { title: "Політика захисту дітей", sub: "База знань · Дитяче містечко", meta: "3 дні тому", badge: { label: "Конфлікт версій", tone: "amber" } },
          ],
          footer: "Синхронізується щохвилини · в обидва боки",
        },
      },
      en: {
        seoTitle: "Notion — My Church module",
        seoDescription: "Notion and My Church in two-way sync: pages become the knowledge base, databases become tables, changes land within a minute and permissions still apply.",
        title: "Church documents live in Notion and My Church at once",
        lead: "If the team already keeps guides, plans and databases in Notion, don't move anything by hand. Two-way sync keeps documents and tables identical in both places.",
        highlights: [
          "Two-way sync of pages and databases",
          "Changes picked up within a minute",
          "Church knowledge base from Notion, no copying",
          "My Church access rights still apply",
        ],
        features: [
          { icon: "RefreshCw", title: "Both directions", text: "Edit a page in Notion — it updates in the knowledge base. Add a person in My Church — a row appears in the Notion database." },
          { icon: "Database", title: "Databases ↔ tables", text: "The volunteer list, inventory, project tasks — a Notion database becomes a My Church table with field types preserved." },
          { icon: "BookOpen", title: "Knowledge base without copying", text: "Team guides, service scripts, policies — published to the knowledge base straight from Notion." },
          { icon: "GitBranch", title: "Selective sync", text: "Choose which pages and databases to sync. The team's personal notes stay in Notion." },
          { icon: "Lock", title: "Access rights", text: "Who sees a document in My Church is decided by My Church roles — even if the Notion page is open to everyone." },
        ],
        steps: [
          { title: "Connect the workspace", text: "Authorise Notion and choose the pages and databases My Church may access." },
          { title: "Map the fields", text: "For databases, say which Notion column matches which My Church field. Once." },
          { title: "Work where it suits you", text: "The team edits in Notion, leaders read in My Church — and nobody asks which version is current." },
        ],
        audience: [
          { role: "pastor", text: "Reads plans and documents in My Church without opening Notion." },
          { role: "leader", text: "Opens the service guide in the knowledge base — always the current one." },
          { role: "hr", text: "Keeps policies and checklists in Notion while the team sees them in their My Church roles." },
        ],
        faq: [
          { q: "What if a document is edited in both places at once?", a: "The last saved version wins, and we keep the previous one in history — nothing is lost." },
          { q: "Do people from My Church sync into Notion?", a: "Yes, if you turn it on for a specific database. Restricted-access notes are never sent to Notion." },
          { q: "How often is data updated?", a: "Changes from Notion are picked up within a minute. Changes from My Church reach Notion immediately." },
          { q: "Can I disconnect Notion later without losing data?", a: "Yes. Everything already synced stays in My Church as ordinary documents and tables." },
        ],
        mock: {
          kind: "list",
          title: "Notion · sync",
          subtitle: "14 pages · 3 databases · just updated",
          items: [
            { title: "Sunday service script", sub: "Knowledge base · Services", meta: "2 min ago", badge: { label: "Synced", tone: "green" } },
            { title: "Volunteers 2026", sub: "Notion database → Tables", meta: "5 min ago", badge: { label: "Synced", tone: "green" } },
            { title: "Reception guide", sub: "Knowledge base · Team", meta: "Just now", badge: { label: "Updating", tone: "brand" } },
            { title: "Camp plan \"Summer 2026\"", sub: "Notion → Projects", meta: "Yesterday", badge: { label: "Synced", tone: "green" } },
            { title: "Child protection policy", sub: "Knowledge base · Kids Town", meta: "3 days ago", badge: { label: "Version conflict", tone: "amber" } },
          ],
          footer: "Syncs every minute · both directions",
        },
      },
    },
  },
];
