import type { ModuleDetail } from "./types";

/* Module pages: people, family — their catalogue group is the `group` field below. */
export const peopleModules: ModuleDetail[] = [
  {
    id: "people",
    group: "people",
    related: ["family", "groups", "onboarding", "analytics"],
    copy: {
      ua: {
        seoTitle: "Люди — модуль «Моя Церква»",
        seoDescription: "Картка кожної людини в церкві: статус, історія участі, нотатки, контакти та зв'язки — в одному місці замість трьох таблиць.",
        title: "Кожна людина в церкві — на своєму місці",
        lead: "Модуль «Люди» — серце «Моєї Церкви». Одна картка замість трьох таблиць: хто ця людина, у якій групі, коли була востаннє і хто за неї відповідає.",
        highlights: [
          "Профіль з повною історією участі",
          "Статуси: гість, новенький, член церкви",
          "Фільтри й сегменти за будь-яким полем",
          "Нотатки з обмеженим доступом",
        ],
        features: [
          { icon: "UserCheck", title: "Профіль людини", text: "Контакти, дата приходу, членство, хрещення, групи та служіння — усе на одному екрані." },
          { icon: "History", title: "Історія участі", text: "Служіння, зустрічі груп, події та курси автоматично збираються в хронологію людини." },
          { icon: "Filter", title: "Розумні фільтри", text: "«Новенькі без групи», «не були 3 тижні», «волонтери молодіжки» — зберігайте сегменти й повертайтесь до них." },
          { icon: "Tags", title: "Статуси й теги", text: "Гість → новенький → член церкви. Свої статуси й теги під процеси саме вашої церкви." },
          { icon: "NotebookPen", title: "Нотатки та відповідальні", text: "Пасторські нотатки з обмеженим доступом і людина, яка супроводжує кожного новенького." },
          { icon: "Upload", title: "Імпорт із таблиць", text: "Перенесіть Excel чи Google Таблиці за кілька хвилин — без ручного передруку." },
        ],
        steps: [
          { title: "Перенесіть базу", text: "Завантажте таблицю або додайте людей вручну — система сама покаже дублікати." },
          { title: "Налаштуйте статуси", text: "Опишіть шлях людини у вашій церкві: від першого візиту до членства." },
          { title: "Працюйте з картками", text: "Лідери відмічають явку, пастор бачить, кому потрібна увага, — усе в одній базі." },
        ],
        audience: [
          { role: "pastor", text: "Бачить усю церкву: скільки людей, хто нещодавно прийшов, хто перестав приходити." },
          { role: "leader", text: "Веде свою групу: склад, контакти, явка — без доступу до чужих даних." },
          { role: "reception", text: "За секунди знаходить людину, реєструє новеньких і бачить сьогоднішній день." },
        ],
        faq: [
          { q: "Чи можна перенести дані з Google Таблиць?", a: "Так. Завантажте таблицю — ми зіставимо колонки з полями картки, а дублікати покажемо ще до імпорту." },
          { q: "Хто бачить нотатки про людину?", a: "Лише ті, кому ви дали доступ. Пасторські нотатки можна закрити навіть від лідерів груп." },
          { q: "Чи можна додати свої поля?", a: "Так, будь-яку кількість: текст, дата, список, чекбокс. Свої поля працюють у фільтрах і звітах так само, як стандартні." },
        ],
        mock: {
          kind: "list",
          title: "Люди",
          subtitle: "428 людей · 12 новеньких за місяць",
          items: [
            { title: "Олена Ковальчук", sub: "Домашня група · Прославлення", badge: { label: "Член церкви", tone: "green" } },
            { title: "Дмитро Лис", sub: "Без групи · прийшов 2 тижні тому", badge: { label: "Новенький", tone: "brand" } },
            { title: "Наталя Рудь", sub: "Група «Центр» · Дитяче служіння", badge: { label: "Член церкви", tone: "green" } },
            { title: "Василь Панченко", sub: "Не був 4 тижні", badge: { label: "Потребує уваги", tone: "amber" } },
            { title: "Марія Іщенко", sub: "Перший візит у неділю", badge: { label: "Гість", tone: "neutral" } },
          ],
          footer: "Фільтр: усі · новенькі · без групи",
        },
      },
      en: {
        seoTitle: "People — My Church module",
        seoDescription: "A profile for every person in the church: status, participation history, notes, contacts and connections — in one place instead of three spreadsheets.",
        title: "Every person in the church, in their place",
        lead: "The People module is the heart of My Church. One profile instead of three spreadsheets: who this person is, which group they're in, when they last came and who looks after them.",
        highlights: [
          "Profile with full participation history",
          "Statuses: guest, newcomer, member",
          "Filters and segments on any field",
          "Notes with restricted access",
        ],
        features: [
          { icon: "UserCheck", title: "Person profile", text: "Contacts, first visit, membership, baptism, groups and ministries — all on one screen." },
          { icon: "History", title: "Participation history", text: "Services, group meetings, events and courses are collected into a timeline automatically." },
          { icon: "Filter", title: "Smart filters", text: "\"Newcomers without a group\", \"absent 3 weeks\", \"youth volunteers\" — save segments and come back to them." },
          { icon: "Tags", title: "Statuses and tags", text: "Guest → newcomer → member. Your own statuses and tags for the way your church actually works." },
          { icon: "NotebookPen", title: "Notes and owners", text: "Pastoral notes with restricted access, and a named person who follows up every newcomer." },
          { icon: "Upload", title: "Import from spreadsheets", text: "Bring over Excel or Google Sheets in minutes — no retyping." },
        ],
        steps: [
          { title: "Bring your data", text: "Upload a spreadsheet or add people by hand — the system flags duplicates for you." },
          { title: "Set up statuses", text: "Describe a person's path in your church: from first visit to membership." },
          { title: "Work from profiles", text: "Leaders mark attendance, the pastor sees who needs attention — all in one database." },
        ],
        audience: [
          { role: "pastor", text: "Sees the whole church: how many people, who arrived recently, who stopped coming." },
          { role: "leader", text: "Runs their own group: members, contacts, attendance — with no access to anyone else's data." },
          { role: "reception", text: "Finds a person in seconds, registers newcomers and sees today at a glance." },
        ],
        faq: [
          { q: "Can I move my data over from Google Sheets?", a: "Yes. Upload the sheet — we map columns to profile fields and show duplicates before anything is imported." },
          { q: "Who can see notes about a person?", a: "Only those you give access to. Pastoral notes can be hidden even from group leaders." },
          { q: "Can I add custom fields?", a: "Yes, as many as you need: text, date, list, checkbox. Custom fields work in filters and reports just like the built-in ones." },
        ],
        mock: {
          kind: "list",
          title: "People",
          subtitle: "428 people · 12 newcomers this month",
          items: [
            { title: "Olena Kovalchuk", sub: "Obolon group · Worship", badge: { label: "Member", tone: "green" } },
            { title: "Dmytro Lys", sub: "No group · joined 2 weeks ago", badge: { label: "Newcomer", tone: "brand" } },
            { title: "Natalia Rud", sub: "Centre group · Kids ministry", badge: { label: "Member", tone: "green" } },
            { title: "Vasyl Panchenko", sub: "Absent for 4 weeks", badge: { label: "Needs attention", tone: "amber" } },
            { title: "Maria Ishchenko", sub: "First visit on Sunday", badge: { label: "Guest", tone: "neutral" } },
          ],
          footer: "Filter: all · newcomers · no group",
        },
      },
    },
  },
  {
    id: "family",
    group: "people",
    related: ["people", "kids-town", "campaigns", "events"],
    copy: {
      ua: {
        seoTitle: "Сім'я — модуль «Моя Церква»",
        seoDescription: "Картка родини в церкві: подружжя, діти, батьки, важливі дати та спільна історія. Одна картка на сім'ю замість п'яти окремих профілів.",
        title: "Бачите родину цілком, а не окремих людей",
        lead: "Модуль «Сім'я» зв'язує людей у родини: подружжя, діти, батьки. Одна картка — і ви знаєте, хто до кого належить, хто з дітей у «Дитячому містечку» і коли в родини річниця.",
        highlights: [
          "Подружжя, діти й батьки — в одній картці",
          "Діти прив'язані до батьків для відмітки приходу",
          "Річниці й дні народження з нагадуванням",
          "Одне повідомлення на родину, а не на кожного",
        ],
        features: [
          { icon: "Home", title: "Картка родини", text: "Подружжя, діти, батьки — усі зв'язки на одному екрані, з переходом до профілю кожного." },
          { icon: "Baby", title: "Діти під батьками", text: "Дитина без телефону й пошти — теж картка. Вона живе під батьками, і «Дитяче містечко» знає, кому її віддати." },
          { icon: "Gift", title: "Дати родини", text: "Дні народження, річниця весілля, посвята дитини — система нагадає пастору чи лідеру за кілька днів." },
          { icon: "History", title: "Спільна історія", text: "Весілля, посвята, хрещення дітей, переїзд — події родини в одній хронології, а не розкидані по профілях." },
          { icon: "Send", title: "Повідомлення на родину", text: "Запрошення на сімейний табір іде одному контакту сім'ї, а не кожному з подружжя окремо." },
          { icon: "Users", title: "Родини в групах", text: "Лідер бачить, які пари в його групі, і помічає, коли перестала приходити вся родина." },
        ],
        steps: [
          { title: "Об'єднайте людей у родини", text: "Оберіть людей у базі й вкажіть зв'язок: подружжя, дитина, батьки. Спільне прізвище й адреса підкажуть, кого варто об'єднати." },
          { title: "Додайте дітей", text: "Вік, група в «Дитячому містечку», алергії — і хто з дорослих має право забирати дитину." },
          { title: "Позначте дати", text: "Річниця, дні народження, дата посвяти — система нагадає, і церква привітає родину вчасно." },
          { title: "Працюйте з родиною цілком", text: "Реєстрація на табір, розсилка, візит пастора — на рівні сім'ї, а не окремих людей." },
        ],
        audience: [
          { role: "pastor", text: "Бачить родини церкви, помічає, коли пара перестала приходити разом, і знає, в кого цього тижня річниця." },
          { role: "leader", text: "Знає, які подружжя в його групі, і бачить, коли родина пропускає зустрічі разом." },
          { role: "member", text: "Оновлює дані своєї сім'ї сам: народилась дитина, змінилась адреса — без дзвінка в офіс." },
          { role: "reception", text: "Відмічає прихід дитини за іменем батьків і бачить, хто має право її забрати." },
        ],
        faq: [
          { q: "Чи може людина бути в кількох родинах?", a: "Так. Дорослі діти створюють свою родину й залишаються дітьми в картці батьків. Система зберігає обидва зв'язки." },
          { q: "Що бачить член церкви про свою сім'ю?", a: "Лише свою родину: дані подружжя, дітей, дати. Він може їх оновити — відповідальний отримає сповіщення про зміну." },
          { q: "Чи потрібен дитині окремий профіль?", a: "Так, але без телефону й пошти. Дитяча картка живе під батьками, а коли дитина доростає до молодіжки — стає повноцінним профілем з усією історією." },
          { q: "Як бути з розлученням чи опікою?", a: "Зв'язки можна змінити будь-коли, історія зберігається. Хто має право забирати дитину — окреме поле, яке бачать лише «Дитяче містечко» і рецепція." },
        ],
        mock: {
          kind: "list",
          title: "Родина Ковальчуків",
          subtitle: "5 осіб · Виноградар · річниця 14 травня",
          items: [
            { title: "Андрій Ковальчук", sub: "Чоловік · Зустріч гостей", badge: { label: "Контакт родини", tone: "brand" } },
            { title: "Олена Ковальчук", sub: "Дружина · Прославлення", badge: { label: "Член церкви", tone: "green" } },
            { title: "Марко Ковальчук", sub: "Син · 9 років · група 7–10", badge: { label: "Дитяче містечко", tone: "amber" } },
            { title: "Софія Ковальчук", sub: "Донька · 5 років · група 4–6", badge: { label: "Дитяче містечко", tone: "amber" } },
            { title: "Галина Ковальчук", sub: "Мама Андрія · Група «Центр»", badge: { label: "Член церкви", tone: "green" } },
          ],
          footer: "Дати: 14 тра — річниця · 20 чер — Андрій",
        },
        pipeline: {
          title: "Шлях родини — від окремих карток до однієї сім'ї",
          text: "Приклад: Ковальчуки — подружжя, двоє дітей і мама Андрія.",
          stages: [
            { title: "Окремі картки", tone: "neutral", text: "Андрій і Олена в базі окремо, діти не заведені взагалі. Ніхто не бачить, що це одна сім'я.", auto: "Підказує «схоже на одну родину» за спільним прізвищем і адресою." },
            { title: "Зв'язки проставлені", tone: "brand", text: "Адміністратор вказує подружжя, додає маму Андрія і обирає контакт родини.", auto: "Створює картки дітей без телефону й пошти — під батьками." },
            { title: "Діти в Дитячому містечку", tone: "amber", text: "Вік, група, алергії та список тих, хто має право забирати дитину.", auto: "Показує при відмітці приходу лише дорослих із цього списку й позначає алергії." },
            { title: "Родина як одне ціле", tone: "green", text: "Запрошення на сімейний табір іде одному контакту, а участь записується в картку кожного з п'ятьох.", auto: "Нагадує пастору й лідеру групи про річницю 14 травня за три дні." },
          ],
        },
      },
      en: {
        seoTitle: "Family — My Church module",
        seoDescription: "One family record instead of five separate profiles: spouses, children, parents, key dates and shared history for every household in the church.",
        title: "See the whole family, not just individuals",
        lead: "The Family module links people into households: spouses, children, parents. One record — and you know who belongs to whom, which children are in Kids Town and when the family's anniversary is.",
        highlights: [
          "Spouses, children and parents in one record",
          "Children linked to parents for check-in",
          "Anniversaries and birthdays with reminders",
          "One message per family, not per person",
        ],
        features: [
          { icon: "Home", title: "Family record", text: "Spouses, children, parents — every connection on one screen, with a link to each person's profile." },
          { icon: "Baby", title: "Children under parents", text: "A child with no phone or email still gets a profile. It lives under the parents, and Kids Town knows who to hand the child to." },
          { icon: "Gift", title: "Family dates", text: "Birthdays, wedding anniversary, child dedication — the system reminds the pastor or leader a few days ahead." },
          { icon: "History", title: "Shared history", text: "Wedding, dedication, children's baptism, a move — family events in one timeline instead of scattered across profiles." },
          { icon: "Send", title: "One message per household", text: "An invitation to family camp goes to one family contact, not to each spouse separately." },
          { icon: "Users", title: "Families in groups", text: "A leader sees which couples are in their group and notices when a whole family stops coming." },
        ],
        steps: [
          { title: "Link people into families", text: "Pick people in the database and set the relationship: spouse, child, parent. A shared surname and address suggest who to link." },
          { title: "Add the children", text: "Age, Kids Town group, allergies — and which adults are allowed to collect the child." },
          { title: "Mark the dates", text: "Anniversary, birthdays, dedication date — the system reminds you, and the church greets the family on time." },
          { title: "Work with the household", text: "Camp registration, a campaign, a pastoral visit — at family level, not person by person." },
        ],
        audience: [
          { role: "pastor", text: "Sees the church's families, notices when a couple stops coming together and knows whose anniversary is this week." },
          { role: "leader", text: "Knows which couples are in their group and sees when a family misses meetings together." },
          { role: "member", text: "Updates their own family details: a new baby, a new address — without calling the office." },
          { role: "reception", text: "Checks a child in by the parents' name and sees who is allowed to collect them." },
        ],
        faq: [
          { q: "Can a person belong to more than one family?", a: "Yes. Grown-up children start their own household and stay listed as children in their parents' record. Both links are kept." },
          { q: "What does a member see about their family?", a: "Only their own household: spouse, children, dates. They can update it — the person responsible gets a notification about the change." },
          { q: "Does a child need a separate profile?", a: "Yes, but without a phone or email. The child's record lives under the parents and becomes a full profile with all its history once they move up to youth." },
          { q: "What about divorce or guardianship?", a: "Relationships can be changed at any time and the history is kept. Who may collect a child is a separate field, visible only to Kids Town and reception." },
        ],
        mock: {
          kind: "list",
          title: "The Kovalchuk family",
          subtitle: "5 people · Obolon · anniversary 14 May",
          items: [
            { title: "Andrii Kovalchuk", sub: "Husband · Welcome team", badge: { label: "Family contact", tone: "brand" } },
            { title: "Olena Kovalchuk", sub: "Wife · Worship", badge: { label: "Member", tone: "green" } },
            { title: "Marko Kovalchuk", sub: "Son · 9 y.o. · group 7–10", badge: { label: "Kids Town", tone: "amber" } },
            { title: "Sofiia Kovalchuk", sub: "Daughter · 5 y.o. · group 4–6", badge: { label: "Kids Town", tone: "amber" } },
            { title: "Halyna Kovalchuk", sub: "Andrii's mother · Centre group", badge: { label: "Member", tone: "green" } },
          ],
          footer: "Upcoming: 14 May — anniversary · 20 Jun — Andrii",
        },
        pipeline: {
          title: "A household, from separate profiles to one family",
          text: "Example: the Kovalchuks — a couple, two children and Andrii's mother.",
          stages: [
            { title: "Separate profiles", tone: "neutral", text: "Andrii and Olena sit in the database separately, the children aren't there at all. Nobody sees one family.", auto: "Suggests \"looks like one family\" from the shared surname and address." },
            { title: "Relationships set", tone: "brand", text: "The administrator marks the couple, adds Andrii's mother and picks the family contact.", auto: "Creates the children's records without phone or email — under the parents." },
            { title: "Children in Kids Town", tone: "amber", text: "Age, group, allergies and the list of adults allowed to collect the child.", auto: "Shows only those adults at check-in and flags the allergies." },
            { title: "The household as one", tone: "green", text: "A family camp invitation goes to one contact, and the sign-up is written into all five profiles.", auto: "Reminds the pastor and the group leader about the 14 May anniversary three days ahead." },
          ],
        },
      },
    },
  },
];
