import type { ModuleDetail } from "./types";

/* Module pages: calendar, seasons, goals, events — their catalogue group is the `group` field below. */
export const planningModules: ModuleDetail[] = [
  {
    id: "calendar",
    group: "schedule",
    related: ["rooms", "service-planning", "events", "groups"],
    copy: {
      ua: {
        seoTitle: "Календар — модуль «Моя Церква»",
        seoDescription: "Служіння, зустрічі малих груп, події та бронювання приміщень в одному календарі церкви. Кожен бачить своє, а накладки видно ще до збереження.",
        title: "Усе, що відбувається в церкві, — в одному календарі",
        lead: "Служіння, репетиції, зустрічі малих груп, конференції та бронювання залів — у спільному календарі. Кожен бачить своє: пастор — усю церкву, лідер — свою групу, рецепція — сьогоднішній день.",
        highlights: [
          "Служіння, групи, події та бронювання разом",
          "Накладки приміщень видно ще до збереження",
          "Особистий розклад для кожного служителя",
          "Нагадування в Telegram за день і за годину",
        ],
        features: [
          { icon: "CalendarDays", title: "Спільний календар церкви", text: "Недільні служіння, репетиції, зустрічі груп, події й бронювання — на одній сітці, з фільтром за служінням, групою чи кемпусом." },
          { icon: "Repeat", title: "Повторювані події", text: "Служіння щонеділі, група щочетверга, репетиція щосереди — задайте раз, а винятки й перенесення правте окремо." },
          { icon: "DoorOpen", title: "Бронювання приміщень", text: "Подія одразу займає зал чи кімнату. Якщо час зайнятий — система покаже, ким, і запропонує вільний слот." },
          { icon: "User", title: "Мій розклад", text: "Служитель бачить лише те, де він задіяний: коли, де, у якій ролі. Лідер — свою групу та служіння." },
          { icon: "BellRing", title: "Нагадування", text: "Бот церкви нагадає учасникам про зустріч, а команді — про підготовку. Змінили час — усі отримають оновлення." },
          { icon: "Share2", title: "Публічний розклад", text: "Публікуйте розклад на сайт або в бот церкви. Людина підписується на служіння чи групу і бачить їх у своєму телефоні." },
        ],
        steps: [
          { title: "Додайте регулярні події", text: "Служіння, репетиції, групи — один раз із правилом повторення. Далі календар веде їх сам." },
          { title: "Прив'яжіть приміщення й команди", text: "Кожній події — зал, відповідальний і склад. Накладки й перевантаження команди видно одразу." },
          { title: "Відкрийте розклад людям", text: "Служителі бачать свій графік у боті, члени церкви — події й групи, рецепція — сьогоднішній день." },
        ],
        audience: [
          { role: "pastor", text: "Бачить тиждень усієї церкви: де служіння, де групи, що готує команда і чи не перетинаються події." },
          { role: "leader", text: "Ставить зустрічі своєї групи, бронює кімнату й знає, що учасники отримали нагадування." },
          { role: "volunteer", text: "Бачить свій графік на місяць у телефоні: коли служити, де і в якій ролі." },
          { role: "reception", text: "Відповідає на «а коли…?» за секунду і бачить усі бронювання на сьогодні." },
        ],
        faq: [
          { q: "Чи можна синхронізувати з Google Календарем?", a: "Так. Розклад можна підключити до Google чи Apple Календаря за посиланням — зміни в «Моїй Церкві» з'являються там автоматично." },
          { q: "Що буде, якщо дві події претендують на один зал?", a: "Система попередить ще до збереження: покаже, хто вже забронював зал, і запропонує вільний час або іншу кімнату. Накладка не збережеться непомітно." },
          { q: "Чи бачить служитель чужі події?", a: "За замовчуванням — лише свої служіння та групи й публічні події церкви. Повний календар бачать пастор, адміністратор і ті, кому ви дали доступ." },
          { q: "Як перенести чи скасувати служіння?", a: "Змініть час або позначте скасування — учасники й команда отримають повідомлення в Telegram, а бронювання залу звільниться саме." },
        ],
        mock: {
          kind: "calendar",
          title: "Календар церкви",
          subtitle: "Тиждень 14–20 вересня · 11 подій",
          days: ["Пн", "Вт", "Ср", "Чт", "Пт", "Сб", "Нд"],
          events: [
            { day: 0, start: 2, span: 1, title: "Лідери", tone: "neutral" },
            { day: 1, start: 1, span: 1, title: "Молитва", tone: "violet" },
            { day: 2, start: 4, span: 2, title: "Репетиція", tone: "violet" },
            { day: 3, start: 1, span: 2, title: "Бронь зали", tone: "amber" },
            { day: 3, start: 5, span: 2, title: "Група Центр", tone: "green" },
            { day: 4, start: 5, span: 2, title: "Домашня група", tone: "green" },
            { day: 5, start: 3, span: 2, title: "Молодіжка", tone: "brand" },
            { day: 6, start: 0, span: 2, title: "Служіння", tone: "brand" },
            { day: 6, start: 3, span: 1, title: "Зустріч гостей", tone: "green" },
          ],
        },
      },
      en: {
        seoTitle: "Calendar — My Church module",
        seoDescription: "Services, small-group meetings, events and room bookings in one church calendar. Everyone sees their own schedule, and clashes show up before you save.",
        title: "Everything happening in the church, in one calendar",
        lead: "Services, rehearsals, small-group meetings, conferences and hall bookings — in one shared calendar. Everyone sees what's theirs: the pastor sees the whole church, a leader their group, reception today's day.",
        highlights: [
          "Services, groups, events and bookings together",
          "Room clashes flagged before you save",
          "A personal schedule for every volunteer",
          "Telegram reminders a day and an hour ahead",
        ],
        features: [
          { icon: "CalendarDays", title: "One church calendar", text: "Sunday services, rehearsals, group meetings, events and bookings on one grid — filtered by ministry, group or campus." },
          { icon: "Repeat", title: "Recurring events", text: "Service every Sunday, group every Thursday, rehearsal every Wednesday — set it once and handle exceptions and reschedules individually." },
          { icon: "DoorOpen", title: "Room bookings", text: "An event takes the hall or room as soon as it's created. If the slot is taken, the system shows who has it and suggests a free one." },
          { icon: "User", title: "My schedule", text: "A volunteer sees only what involves them: when, where and in which role. A leader sees their group and ministry." },
          { icon: "BellRing", title: "Reminders", text: "The church bot reminds participants about the meeting and the team about preparation. Change the time and everyone gets the update." },
          { icon: "Share2", title: "Public schedule", text: "Publish the schedule to your website or church bot. People subscribe to a service or group and see it on their phone." },
        ],
        steps: [
          { title: "Add the regular events", text: "Services, rehearsals, groups — once, with a repeat rule. The calendar keeps them going from there." },
          { title: "Attach rooms and teams", text: "Every event gets a hall, an owner and a team. Clashes and overloaded volunteers show up straight away." },
          { title: "Open the schedule to people", text: "Volunteers see their rota in the bot, members see events and groups, reception sees today." },
        ],
        audience: [
          { role: "pastor", text: "Sees the whole church's week: where services are, where groups meet, what the team is preparing and whether anything overlaps." },
          { role: "leader", text: "Schedules their group's meetings, books a room and knows the members have been reminded." },
          { role: "volunteer", text: "Sees their month's rota on their phone: when to serve, where and in which role." },
          { role: "reception", text: "Answers \"when is…?\" in a second and sees every booking for today." },
        ],
        faq: [
          { q: "Can I sync with Google Calendar?", a: "Yes. Connect your schedule to Google or Apple Calendar with a link — changes made in My Church appear there automatically." },
          { q: "What happens when two events want the same hall?", a: "The system warns you before saving: it shows who already has the hall and offers a free time or another room. A clash never slips through unnoticed." },
          { q: "Can a volunteer see other people's events?", a: "By default only their own services and groups, plus the church's public events. The pastor, the administrator and anyone you grant access see the full calendar." },
          { q: "How do I move or cancel a service?", a: "Change the time or mark it cancelled — participants and the team get a Telegram message, and the hall booking is released automatically." },
        ],
        mock: {
          kind: "calendar",
          title: "Church calendar",
          subtitle: "Week 14–20 Sep · 11 events",
          days: ["Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"],
          events: [
            { day: 0, start: 2, span: 1, title: "Leaders", tone: "neutral" },
            { day: 1, start: 1, span: 1, title: "Prayer", tone: "violet" },
            { day: 2, start: 4, span: 2, title: "Rehearsal", tone: "violet" },
            { day: 3, start: 1, span: 2, title: "Hall booking", tone: "amber" },
            { day: 3, start: 5, span: 2, title: "Centre group", tone: "green" },
            { day: 4, start: 5, span: 2, title: "Obolon group", tone: "green" },
            { day: 5, start: 3, span: 2, title: "Youth", tone: "brand" },
            { day: 6, start: 0, span: 2, title: "Service", tone: "brand" },
            { day: 6, start: 3, span: 1, title: "Guest welcome", tone: "green" },
          ],
        },
      },
    },
  },
  {
    id: "seasons",
    group: "schedule",
    related: ["goals", "calendar", "events", "analytics"],
    copy: {
      ua: {
        seoTitle: "Сезони — модуль «Моя Церква»",
        seoDescription: "Плануйте церковний рік сезонами: Різдво, Великдень, літо, осінній старт. Цілі, події, команда та підсумки кожного сезону — в одному місці.",
        title: "Плануйте рік церкви сезонами, а не окремими подіями",
        lead: "Сезон — це кілька тижнів із власною метою: Різдво, Великдень, літні табори, осінній старт груп. Модуль збирає події, цілі, команду й підсумки кожного сезону, щоб церква рухалась у одному напрямку.",
        highlights: [
          "Цілі й події сезону на одній сторінці",
          "Готові шаблони: Різдво, Великдень, літо",
          "Віхи з відповідальними та дедлайнами",
          "Підсумки сезону — порівняння з минулим роком",
        ],
        features: [
          { icon: "CalendarClock", title: "Сторінка сезону", text: "Дати, мета, ключові події, команда й бюджет — одна сторінка, з якої видно весь сезон, а не десяток розрізнених подій." },
          { icon: "Milestone", title: "Віхи й дедлайни", text: "Старт реєстрації, друк запрошень, репетиції, служіння — кожна віха має відповідального й дату. Прострочене підсвічується." },
          { icon: "Target", title: "Цілі сезону", text: "«30 новеньких на Різдво», «5 нових груп восени» — ціль прив'язана до сезону, і прогрес рахується сам із даних системи." },
          { icon: "LayoutTemplate", title: "Шаблони сезонів", text: "Різдво минулого року стає шаблоном для цього: копіюйте план, віхи й команду, змінюйте лише дати." },
          { icon: "Users", title: "Команда сезону", text: "Хто за що відповідає в цьому сезоні — окремо від постійних служінь. Навантаження людей видно поруч із графіком." },
          { icon: "TrendingUp", title: "Підсумки сезону", text: "Скільки прийшло, скільки лишилось, які події спрацювали. Порівняння з попереднім сезоном — автоматично." },
        ],
        steps: [
          { title: "Створіть сезон", text: "Оберіть шаблон або задайте дати й мету самі. Різдво, Великдень, літо — або свій сезон церкви." },
          { title: "Розкладіть віхи та події", text: "Додайте ключові події з календаря, призначте відповідальних і дедлайни підготовки." },
          { title: "Ведіть команду по плану", text: "Відповідальні отримують нагадування, пастор бачить прогрес по віхах і цілях щотижня." },
          { title: "Підбийте підсумки", text: "Після сезону — звіт: цифри, що спрацювало, що ні. Наступного року починаєте з готового плану." },
        ],
        audience: [
          { role: "pastor", text: "Бачить сезон цілком: цілі, ключові події, хто відповідає й чи встигає команда." },
          { role: "leader", text: "Знає, що від його служіння чекають цього сезону, і бачить дедлайни своїх віх." },
          { role: "hr", text: "Бачить навантаження команди по сезонах і планує заміни ще до пікових тижнів." },
        ],
        faq: [
          { q: "Чим сезон відрізняється від події?", a: "Подія — це один день чи захід. Сезон — кілька тижнів із власною метою, у які входять кілька подій, віхи підготовки та команда. Різдвяне служіння — подія, різдвяний сезон — шість тижнів навколо нього." },
          { q: "Чи можуть сезони перетинатись?", a: "Так. Осінній старт груп і підготовка до Різдва можуть іти паралельно — кожен сезон має свою сторінку, а в календарі видно обидва." },
          { q: "Чи можна повторити сезон минулого року?", a: "Так, одним кліком. План, віхи, команда та події копіюються в новий сезон, лишається змінити дати й оновити цілі." },
          { q: "Як рахуються підсумки сезону?", a: "Автоматично з даних, які вже є в системі: явка, новенькі, реєстрації на події, нові групи. Нічого не потрібно вносити вручну." },
        ],
        mock: {
          kind: "timeline",
          title: "Сезон «Різдво 2026»",
          subtitle: "1 лис — 10 січ · 6 віх · 3 цілі",
          items: [
            { time: "1 лис", title: "Старт: цілі й команда", who: "Пастор Іван", done: true },
            { time: "15 лис", title: "Відкрито реєстрацію", who: "Олена Ковальчук", done: true },
            { time: "6 гру", title: "Дитяча вистава", who: "Наталя Рудь", done: false },
            { time: "20 гру", title: "Різдвяний концерт", who: "Андрій Мельник", done: false },
            { time: "25 гру", title: "Різдвяне служіння", who: "Команда служіння", done: false },
            { time: "10 січ", title: "Підсумки сезону", who: "Пастор Іван", done: false },
          ],
        },
        pipeline: {
          title: "Як сезон проходить від задуму до підсумків",
          text: "Приклад різдвяного сезону. Сезон переходить на наступний етап, коли ви це позначаєте, — система підхоплює решту.",
          stages: [
            { title: "Задум", tone: "neutral", text: "Пастор задає дати, мету сезону й команду. Або копіює сезон минулого року цілком.", auto: "Створює сторінку сезону та додає його ключові події в календар церкви." },
            { title: "Підготовка", tone: "brand", text: "Віхи розписані: відкриття реєстрації, друк запрошень, репетиції. У кожної — відповідальний і дата.", auto: "Нагадує відповідальному за три дні до віхи, а прострочене показує пастору." },
            { title: "Проведення", tone: "violet", text: "Події сезону йдуть одна за одною. Команда бачить свій графік, реєстрації тривають.", auto: "Показує на сторінці сезону явку й реєстрації по кожній події в день, коли вона минула." },
            { title: "Підсумки", tone: "green", text: "Лідери сходяться на розбір: що спрацювало, що прибрати наступного року. Висновки лишаються в сезоні.", auto: "Збирає цифри сезону, порівнює з минулим роком і зберігає план як шаблон." },
          ],
        },
      },
      en: {
        seoTitle: "Seasons — My Church module",
        seoDescription: "Plan the church year in seasons: Christmas, Easter, summer, the autumn launch. Goals, events, team and a review for every season — all in one place.",
        title: "Plan the church year in seasons, not scattered events",
        lead: "A season is a few weeks with a purpose of its own: Christmas, Easter, summer camps, the autumn group launch. The module gathers each season's events, goals, team and review so the whole church moves in one direction.",
        highlights: [
          "Season goals and events on one page",
          "Ready templates: Christmas, Easter, summer",
          "Milestones with owners and deadlines",
          "Season review compared with last year",
        ],
        features: [
          { icon: "CalendarClock", title: "Season page", text: "Dates, purpose, key events, team and budget — one page that shows the whole season rather than a dozen unrelated events." },
          { icon: "Milestone", title: "Milestones and deadlines", text: "Registration opens, invitations printed, rehearsals, the service itself — every milestone has an owner and a date. Overdue ones are highlighted." },
          { icon: "Target", title: "Season goals", text: "\"30 newcomers at Christmas\", \"5 new groups in autumn\" — the goal is tied to the season and progress is counted from the system's own data." },
          { icon: "LayoutTemplate", title: "Season templates", text: "Last year's Christmas becomes this year's template: copy the plan, milestones and team, and change only the dates." },
          { icon: "Users", title: "Season team", text: "Who is responsible for what this season — separate from permanent ministries. Workload is visible next to the schedule." },
          { icon: "TrendingUp", title: "Season review", text: "How many came, how many stayed, which events worked. Comparison with the previous season is automatic." },
        ],
        steps: [
          { title: "Create a season", text: "Pick a template or set the dates and purpose yourself. Christmas, Easter, summer — or a season of your own." },
          { title: "Lay out milestones and events", text: "Add the key events from the calendar, assign owners and preparation deadlines." },
          { title: "Lead the team through the plan", text: "Owners get reminders; the pastor sees progress on milestones and goals every week." },
          { title: "Review the season", text: "After the season — a report: the numbers, what worked and what didn't. Next year you start from a ready plan." },
        ],
        audience: [
          { role: "pastor", text: "Sees the season as a whole: goals, key events, who is responsible and whether the team is on track." },
          { role: "leader", text: "Knows what is expected of their ministry this season and sees the deadlines for their milestones." },
          { role: "hr", text: "Sees the team's workload season by season and arranges cover before the peak weeks." },
        ],
        faq: [
          { q: "How is a season different from an event?", a: "An event is one day or one occasion. A season is several weeks with a purpose, containing a few events, preparation milestones and a team. The Christmas service is an event; the Christmas season is the six weeks around it." },
          { q: "Can seasons overlap?", a: "Yes. The autumn group launch and Christmas preparation can run in parallel — each season has its own page, and the calendar shows both." },
          { q: "Can I repeat last year's season?", a: "Yes, in one click. The plan, milestones, team and events are copied into a new season; you only change the dates and update the goals." },
          { q: "How is the season review calculated?", a: "Automatically, from data already in the system: attendance, newcomers, event registrations, new groups. Nothing has to be entered by hand." },
        ],
        mock: {
          kind: "timeline",
          title: "Christmas 2026 season",
          subtitle: "1 Nov – 10 Jan · 6 milestones · 3 goals",
          items: [
            { time: "1 Nov", title: "Kick-off: goals and team", who: "Pastor Ivan", done: true },
            { time: "15 Nov", title: "Registration opened", who: "Olena Kovalchuk", done: true },
            { time: "6 Dec", title: "Kids' nativity play", who: "Natalia Rud", done: false },
            { time: "20 Dec", title: "Christmas concert", who: "Andrii Melnyk", done: false },
            { time: "25 Dec", title: "Christmas service", who: "Service team", done: false },
            { time: "10 Jan", title: "Season review", who: "Pastor Ivan", done: false },
          ],
        },
        pipeline: {
          title: "How a season runs from idea to review",
          text: "An example Christmas season. You mark the move to the next stage; the system picks up the rest.",
          stages: [
            { title: "Idea", tone: "neutral", text: "The pastor sets the dates, the purpose of the season and the team. Or copies last year's season whole.", auto: "Creates the season page and adds its key events to the church calendar." },
            { title: "Preparation", tone: "brand", text: "Milestones are laid out: registration opens, invitations printed, rehearsals. Each has an owner and a date.", auto: "Reminds the owner three days before a milestone and shows overdue ones to the pastor." },
            { title: "Running", tone: "violet", text: "The season's events follow one after another. The team sees its rota, registrations keep coming in.", auto: "Adds attendance and registrations for each event to the season page on the day it passes." },
            { title: "Review", tone: "green", text: "Leaders meet to go through it: what worked and what to drop next year. The conclusions stay with the season.", auto: "Gathers the season's numbers, compares them with last year and saves the plan as a template." },
          ],
        },
      },
    },
  },
  {
    id: "goals",
    group: "insight",
    related: ["analytics", "seasons", "groups", "ministries"],
    copy: {
      ua: {
        seoTitle: "Цілі та метрики — модуль «Моя Церква»",
        seoDescription: "Ставте цілі для церкви, малих груп і служінь та бачте прогрес щотижня. План проти факту рахується з реальних даних явки, без ручних звітів.",
        title: "Цілі церкви, прогрес яких видно щотижня",
        lead: "Пастор ставить ціль церкві, лідер — своїй групі чи служінню, а прогрес рахується сам із явки, новеньких і реєстрацій. План проти факту — на одному екрані, без ручних звітів у понеділок.",
        highlights: [
          "Цілі для церкви, груп і служінь",
          "Прогрес рахується з реальних даних",
          "Дерево цілей: від бачення до команди",
          "Хто відстає — видно завчасно",
        ],
        features: [
          { icon: "Target", title: "Цілі на трьох рівнях", text: "Церква → служіння → мала група. Ціль пастора «40 хрещень за рік» розкладається на цілі команд, і кожна бачить свою частину." },
          { icon: "Activity", title: "Живі метрики", text: "Явка, новенькі, реєстрації, активні групи — метрика прив'язана до цілі, і прогрес оновлюється щоразу, коли лідер відмічає явку." },
          { icon: "Gauge", title: "План проти факту", text: "Де ви зараз, де мали б бути за графіком і чи встигаєте до дедлайну. Відставання підсвічується жовтим ще до кінця сезону." },
          { icon: "Flag", title: "Відповідальні та дедлайни", text: "Кожна ціль має власника й дату. Власник бачить її на своєму дашборді, пастор — усі цілі команди разом." },
          { icon: "Repeat", title: "Регулярний перегляд", text: "Щотижня чи щомісяця — нагадування переглянути цілі на зустрічі лідерів. Коментарі та рішення лишаються в історії цілі." },
          { icon: "BarChart3", title: "Звіт для ради", text: "Усі цілі церкви з прогресом і коментарями — одним кліком у PDF для ради чи зборів членів." },
        ],
        steps: [
          { title: "Сформулюйте цілі року", text: "Пастор задає 3–5 цілей церкви: люди, групи, служителі, хрещення. Кожна — з цифрою й датою." },
          { title: "Розкладіть на команди", text: "Лідери груп і служінь отримують свої частини цілі й погоджують, що реально." },
          { title: "Прив'яжіть метрики", text: "Оберіть, з чого рахується прогрес: явка, новенькі, реєстрації, нові групи. Далі система рахує сама." },
          { title: "Переглядайте щотижня", text: "На зустрічі лідерів відкриваєте один екран замість звітів і бачите, де потрібна допомога." },
        ],
        audience: [
          { role: "pastor", text: "Бачить усі цілі церкви на одному екрані: що в графіку, що відстає, і кому потрібна допомога." },
          { role: "leader", text: "Знає ціль своєї групи чи служіння й бачить, як явка та новенькі наближають до неї." },
          { role: "hr", text: "Ставить цілі команді — набір служителів, навчання — і бачить прогрес по відділах." },
        ],
        faq: [
          { q: "Чи потрібно вносити прогрес вручну?", a: "Ні, якщо ціль прив'язана до метрики системи: явка, новенькі, реєстрації, нові групи рахуються самі. Для цілей без даних у системі — наприклад, «відремонтувати зал» — прогрес оновлює відповідальний." },
          { q: "Чи бачить лідер цілі інших груп?", a: "Лідер бачить цілі церкви й свої власні. Цілі інших груп і служінь відкриті лише тим, кому ви дали доступ." },
          { q: "Що буде, коли ціль не досягнуто?", a: "Нічого не зникає: ціль закривається з фактичним результатом і коментарем, а історія лишається. Наступного року ви побачите, звідки стартували." },
          { q: "Чи можна ставити цілі на сезон, а не на рік?", a: "Так. Ціль має будь-який період: рік, сезон, квартал або конкретна подія. Цілі сезону автоматично показуються на його сторінці." },
        ],
        mock: {
          kind: "board",
          title: "Цілі 2026",
          subtitle: "9 цілей · 6 у графіку · 2 відстають",
          columns: [
            {
              title: "Церква",
              cards: [
                { title: "450 людей до літа", sub: "428 · 95% плану", tag: { label: "У графіку", tone: "green" } },
                { title: "40 хрещень за рік", sub: "27 · 68% плану", tag: { label: "У графіку", tone: "green" } },
                { title: "Явка 80% на служіннях", sub: "74% · дедлайн — грудень", tag: { label: "Відстає", tone: "amber" } },
              ],
            },
            {
              title: "Малі групи",
              cards: [
                { title: "25 активних груп", sub: "23 · Андрій Мельник", tag: { label: "У графіку", tone: "green" } },
                { title: "Явка груп 85%", sub: "79% · Олена Ковальчук", tag: { label: "Відстає", tone: "amber" } },
              ],
            },
            {
              title: "Служіння",
              cards: [
                { title: "60 нових служителів", sub: "41 · Ірина Шевчук", tag: { label: "У графіку", tone: "green" } },
                { title: "Команда Дитячого містечка — 20", sub: "20 · Наталя Рудь", tag: { label: "Досягнуто", tone: "brand" } },
              ],
            },
          ],
        },
        pipeline: {
          title: "Шлях цілі від формулювання до закриття",
          text: "Приклад цілі «40 хрещень до грудня». Етапи однакові для цілі церкви, служіння чи малої групи.",
          stages: [
            { title: "Сформульована", tone: "neutral", text: "Пастор записує ціль із цифрою й датою. Поки що це чернетка, яку бачить лише він.", auto: "Пропонує метрику, з якої рахувати прогрес, і ставить дату першого перегляду." },
            { title: "Розкладена на команди", tone: "brand", text: "Лідери груп і служінь отримують свою частину цілі й підтверджують, що беруть її.", auto: "Створює дочірні цілі з власниками й підсумовує їхній прогрес у головній цілі." },
            { title: "У роботі", tone: "violet", text: "Прогрес рахується з явки, новеньких і реєстрацій. Власник дописує коментар, коли є що сказати.", auto: "Оновлює цифру щоночі та показує поруч, де ви мали б бути за графіком." },
            { title: "Під питанням", tone: "amber", text: "Факт відстає від графіка. Ціль підіймається вгору списку, щоб її розібрали командою.", auto: "Підсвічує ціль жовтим і додає її в порядок денний найближчої зустрічі лідерів." },
            { title: "Закрита", tone: "green", text: "Ціль закривається з фактичним результатом і висновком команди — досягнута вона чи ні.", auto: "Зберігає підсумок в історії й переносить цифру у стартову точку наступного року." },
          ],
        },
      },
      en: {
        seoTitle: "Goals and metrics — My Church module",
        seoDescription: "Set goals for the church, small groups and ministries and see progress every week. Plan versus actual is counted from real data, with no manual reports.",
        title: "Church goals with progress you see every week",
        lead: "The pastor sets a goal for the church, a leader for their group or ministry, and progress is counted automatically from attendance, newcomers and registrations. Plan versus actual on one screen — no Monday-morning reports.",
        highlights: [
          "Goals for the church, groups and ministries",
          "Progress counted from real data",
          "A goal tree: from vision to teams",
          "Who is falling behind — visible early",
        ],
        features: [
          { icon: "Target", title: "Goals on three levels", text: "Church → ministry → small group. The pastor's goal of \"40 baptisms this year\" breaks down into team goals, and each team sees its own part." },
          { icon: "Activity", title: "Live metrics", text: "Attendance, newcomers, registrations, active groups — a metric is tied to the goal and progress updates every time a leader marks attendance." },
          { icon: "Gauge", title: "Plan versus actual", text: "Where you are, where you should be by now and whether you'll make the deadline. Falling behind is highlighted in amber before the season ends." },
          { icon: "Flag", title: "Owners and deadlines", text: "Every goal has an owner and a date. The owner sees it on their dashboard; the pastor sees all the team's goals together." },
          { icon: "Repeat", title: "Regular review", text: "Weekly or monthly — a reminder to review goals at the leaders' meeting. Comments and decisions stay in the goal's history." },
          { icon: "BarChart3", title: "Board report", text: "Every church goal with progress and comments — one click to a PDF for the board or the members' meeting." },
        ],
        steps: [
          { title: "Set the year's goals", text: "The pastor defines 3–5 church goals: people, groups, volunteers, baptisms. Each with a number and a date." },
          { title: "Break them down to teams", text: "Group and ministry leaders receive their share of the goal and agree on what is realistic." },
          { title: "Attach metrics", text: "Choose what progress is counted from: attendance, newcomers, registrations, new groups. The system counts from there." },
          { title: "Review weekly", text: "At the leaders' meeting you open one screen instead of reports and see where help is needed." },
        ],
        audience: [
          { role: "pastor", text: "Sees every church goal on one screen: what's on track, what's behind and who needs help." },
          { role: "leader", text: "Knows their group's or ministry's goal and sees how attendance and newcomers move it forward." },
          { role: "hr", text: "Sets team goals — recruiting volunteers, training — and tracks progress by department." },
        ],
        faq: [
          { q: "Do I have to update progress by hand?", a: "Not when the goal is tied to a system metric: attendance, newcomers, registrations and new groups count themselves. For goals with no data in the system — say, \"renovate the hall\" — the owner updates progress." },
          { q: "Can a leader see other groups' goals?", a: "A leader sees the church goals and their own. Other groups' and ministries' goals are open only to those you grant access." },
          { q: "What happens when a goal isn't met?", a: "Nothing disappears: the goal is closed with the actual result and a comment, and the history stays. Next year you'll see where you started from." },
          { q: "Can I set goals for a season rather than a year?", a: "Yes. A goal can have any period: a year, a season, a quarter or a specific event. Season goals appear on the season's page automatically." },
        ],
        mock: {
          kind: "board",
          title: "Goals 2026",
          subtitle: "9 goals · 6 on track · 2 behind",
          columns: [
            {
              title: "Church",
              cards: [
                { title: "450 people by summer", sub: "428 · 95% of plan", tag: { label: "On track", tone: "green" } },
                { title: "40 baptisms this year", sub: "27 · 68% of plan", tag: { label: "On track", tone: "green" } },
                { title: "80% service attendance", sub: "74% · due December", tag: { label: "Behind", tone: "amber" } },
              ],
            },
            {
              title: "Small groups",
              cards: [
                { title: "25 active groups", sub: "23 · Andrii Melnyk", tag: { label: "On track", tone: "green" } },
                { title: "85% group attendance", sub: "79% · Olena Kovalchuk", tag: { label: "Behind", tone: "amber" } },
              ],
            },
            {
              title: "Ministries",
              cards: [
                { title: "60 new volunteers", sub: "41 · Iryna Shevchuk", tag: { label: "On track", tone: "green" } },
                { title: "Kids Town team of 20", sub: "20 · Natalia Rud", tag: { label: "Achieved", tone: "brand" } },
              ],
            },
          ],
        },
        pipeline: {
          title: "A goal's path from wording to closing",
          text: "An example goal: \"40 baptisms by December\". The stages are the same for a church, ministry or small-group goal.",
          stages: [
            { title: "Written down", tone: "neutral", text: "The pastor writes the goal with a number and a date. For now it is a draft only they can see.", auto: "Suggests the metric to count progress from and sets the date of the first review." },
            { title: "Split between teams", tone: "brand", text: "Group and ministry leaders receive their share of the goal and confirm that they are taking it.", auto: "Creates child goals with owners and rolls their progress up into the main goal." },
            { title: "In progress", tone: "violet", text: "Progress is counted from attendance, newcomers and registrations. The owner adds a comment when there is something to say.", auto: "Updates the number every night and shows alongside it where you should be by the schedule." },
            { title: "At risk", tone: "amber", text: "The actual figure is behind the schedule. The goal moves to the top of the list to be discussed as a team.", auto: "Highlights the goal in amber and adds it to the agenda of the next leaders' meeting." },
            { title: "Closed", tone: "green", text: "The goal is closed with the actual result and the team's conclusion — whether it was reached or not.", auto: "Keeps the summary in the history and carries the number over as next year's starting point." },
          ],
        },
      },
    },
  },
  {
    id: "events",
    group: "schedule",
    related: ["forms", "links", "calendar", "camps"],
    copy: {
      ua: {
        seoTitle: "Організатор подій — модуль «Моя Церква»",
        seoDescription: "Конференції, служіння, табори: реєстрація, квитки, команда, розклад і нагадування в одному місці. Кожен учасник одразу потрапляє в базу церкви.",
        title: "Від анонсу до підсумків — уся подія в одному місці",
        lead: "Конференція, вечір для сімей чи молодіжний табір — модуль веде подію від сторінки реєстрації до звіту після. Учасники, квитки, команда, розклад і нагадування — в одному місці, а не в п'яти чатах.",
        highlights: [
          "Сторінка реєстрації й QR за хвилину",
          "Квитки, ліміти місць та список очікування",
          "Відмітка приходу на вході з телефону",
          "Учасники одразу в базі церкви",
        ],
        features: [
          { icon: "Ticket", title: "Реєстрація та квитки", text: "Сторінка події з формою, типами квитків, лімітом місць і списком очікування. Посилання чи QR — і люди реєструються з телефону." },
          { icon: "ScanLine", title: "Відмітка приходу на вході", text: "Рецепція сканує QR з квитка або шукає за іменем — секунда на людину. Хто прийшов, а хто ні, видно одразу." },
          { icon: "Users", title: "Команда події", text: "Ролі, зони відповідальності та графік змін. Волонтер підтверджує участь одним натисканням, координатор бачить, кого бракує." },
          { icon: "Clock", title: "Розклад і програма", text: "Сесії, спікери, зали й перерви — програма на сторінці події та в боті. Змінили час — учасники отримали оновлення." },
          { icon: "BellRing", title: "Нагадування", text: "За тиждень, за день, за годину — в Telegram, Viber чи SMS. Після події — подяка й посилання на матеріали." },
          { icon: "UserPlus", title: "Гість стає новеньким", text: "Кожен зареєстрований потрапляє в базу: гість конференції за тиждень уже в онбордингу, а не в загубленій таблиці." },
        ],
        steps: [
          { title: "Створіть подію", text: "Назва, дати, місце, типи квитків і ліміт. Шаблон із минулої конференції — за один клік." },
          { title: "Відкрийте реєстрацію", text: "Опублікуйте сторінку, розішліть посилання й QR у боті, соцмережах та з кафедри." },
          { title: "Проведіть", text: "Відмітка приходу на вході, команда за графіком, розклад у боті, нагадування — самі." },
          { title: "Підбийте підсумки", text: "Скільки зареєструвалось, скільки прийшло, скільки новеньких лишилось у церкві — звіт готовий наступного дня." },
        ],
        audience: [
          { role: "pastor", text: "Бачить подію в цифрах: реєстрації, явка, скільки новеньких залишились після неї." },
          { role: "leader", text: "Організовує подію свого служіння: реєстрація, команда, розклад — без таблиць і чатів." },
          { role: "reception", text: "Відмічає прихід за QR чи іменем і бачить, хто ще не прийшов." },
          { role: "member", text: "Реєструється за кілька натискань, отримує квиток і нагадування в боті." },
        ],
        faq: [
          { q: "Чи можна продавати платні квитки?", a: "Так. Задайте типи квитків — стандарт, студентський, сімейний — з вартістю або без. Оплата фіксується у квитку, а підсумок бачить бухгалтер." },
          { q: "Що, якщо місць менше, ніж охочих?", a: "Задайте ліміт — після нього реєстрація переходить у список очікування. Хтось скасував — наступний у черзі отримує запрошення автоматично." },
          { q: "Чи можна реєструвати кількох людей одразу?", a: "Так. Одна форма — уся сім'я або група: кожен отримає свій квиток, а в базі з'явиться окрема картка з правильними зв'язками." },
          { q: "Куди потрапляють дані учасників?", a: "У базу церкви. Якщо людина вже є — реєстрація додається до її історії; якщо нова — створюється картка зі статусом «гість» і, за бажанням, запускається онбординг." },
        ],
        mock: {
          kind: "table",
          title: "Конференція «Разом»",
          subtitle: "186 зареєстровано · 142 прийшли",
          columns: ["Учасник", "Квиток", "Реєстрація"],
          rows: [
            { cells: ["Олена Ковальчук", "Стандарт", "2 вер"], badge: { label: "На місці", tone: "green" } },
            { cells: ["Дмитро Лис", "Студент", "5 вер"], badge: { label: "На місці", tone: "green" } },
            { cells: ["Марія Іщенко", "Сімейний ×3", "9 вер"], badge: { label: "Очікує оплату", tone: "amber" } },
            { cells: ["Андрій Мельник", "Волонтер", "1 вер"], badge: { label: "Команда", tone: "brand" } },
            { cells: ["Ірина Шевчук", "Стандарт", "12 вер"], badge: { label: "У черзі", tone: "neutral" } },
            { cells: ["Василь Панченко", "Стандарт", "3 вер"], badge: { label: "Скасовано", tone: "red" } },
          ],
        },
      },
      en: {
        seoTitle: "Event organiser — My Church module",
        seoDescription: "Conferences, services, camps: registration, tickets, team, schedule and reminders in one place. Every attendee lands in the church database straight away.",
        title: "Every event from sign-up to follow-up, in one place",
        lead: "A conference, a family evening or a youth camp — the module runs the event from the registration page to the report afterwards. Attendees, tickets, team, schedule and reminders in one place, not in five chats.",
        highlights: [
          "Registration page and QR code in a minute",
          "Tickets, seat limits and a waiting list",
          "Check-in at the door from a phone",
          "Attendees go straight into the church database",
        ],
        features: [
          { icon: "Ticket", title: "Registration and tickets", text: "An event page with a form, ticket types, a seat limit and a waiting list. Share a link or QR code and people register from their phone." },
          { icon: "ScanLine", title: "Check-in at the door", text: "Reception scans the QR code on the ticket or searches by name — a second per person. Who came and who didn't is visible at once." },
          { icon: "Users", title: "Event team", text: "Roles, areas of responsibility and a shift rota. A volunteer confirms with one tap; the coordinator sees who is still missing." },
          { icon: "Clock", title: "Schedule and programme", text: "Sessions, speakers, halls and breaks — the programme lives on the event page and in the bot. Change a time and attendees get the update." },
          { icon: "BellRing", title: "Reminders", text: "A week before, a day before, an hour before — in Telegram, Viber or SMS. After the event, a thank-you and a link to the materials." },
          { icon: "UserPlus", title: "A guest becomes a newcomer", text: "Every registration lands in the database: a conference guest is in onboarding a week later, not lost in a spreadsheet." },
        ],
        steps: [
          { title: "Create the event", text: "Name, dates, venue, ticket types and a limit. A template from last year's conference — one click." },
          { title: "Open registration", text: "Publish the page and share the link and QR code in the bot, on social media and from the pulpit." },
          { title: "Run it", text: "Check-in at the door, the team on its rota, the schedule in the bot, reminders sent automatically." },
          { title: "Review", text: "How many registered, how many came, how many newcomers stayed in the church — the report is ready the next day." },
        ],
        audience: [
          { role: "pastor", text: "Sees the event in numbers: registrations, attendance and how many newcomers stayed afterwards." },
          { role: "leader", text: "Organises their ministry's event: registration, team, schedule — without spreadsheets or chats." },
          { role: "reception", text: "Runs check-in by QR code or name and sees who hasn't arrived yet." },
          { role: "member", text: "Registers in a few taps and gets a ticket and reminders in the bot." },
        ],
        faq: [
          { q: "Can we sell paid tickets?", a: "Yes. Set up ticket types — standard, student, family — with or without a price. Payment is recorded on the ticket and the accountant sees the totals." },
          { q: "What if there are more people than seats?", a: "Set a limit — once it's reached, registration switches to a waiting list. If someone cancels, the next in line is invited automatically." },
          { q: "Can one person register several people?", a: "Yes. One form covers a whole family or group: each person gets their own ticket, and the database gets a separate profile with the right connections." },
          { q: "Where does attendee data go?", a: "Into the church database. If the person already exists, the registration is added to their history; if they're new, a profile is created with the status \"guest\" and, if you wish, onboarding starts." },
        ],
        mock: {
          kind: "table",
          title: "Together conference",
          subtitle: "186 registered · 142 checked in",
          columns: ["Attendee", "Ticket", "Registered"],
          rows: [
            { cells: ["Olena Kovalchuk", "Standard", "2 Sep"], badge: { label: "Checked in", tone: "green" } },
            { cells: ["Dmytro Lys", "Student", "5 Sep"], badge: { label: "Checked in", tone: "green" } },
            { cells: ["Maria Ishchenko", "Family ×3", "9 Sep"], badge: { label: "Awaiting payment", tone: "amber" } },
            { cells: ["Andrii Melnyk", "Volunteer", "1 Sep"], badge: { label: "Team", tone: "brand" } },
            { cells: ["Iryna Shevchuk", "Standard", "12 Sep"], badge: { label: "Waitlist", tone: "neutral" } },
            { cells: ["Vasyl Panchenko", "Standard", "3 Sep"], badge: { label: "Cancelled", tone: "red" } },
          ],
        },
      },
    },
  },
];
