import type { ModuleDetail } from "./types";

/* Module pages: customization, templates, telegram-bot — their catalogue group is the `group` field below. */
export const platformModules: ModuleDetail[] = [
  {
    id: "customization",
    group: "platform",
    related: ["people", "automations", "org", "tables"],
    copy: {
      ua: {
        seoTitle: "Кастомізація — модуль «Моя Церква»",
        seoDescription: "Налаштуйте «Мою Церкву» під свою церкву: свої поля будь-якого типу, статуси й етапи, ролі з точними правами, процеси, термінологія та брендування — без програміста.",
        title: "Система підлаштовується під вашу церкву, а не навпаки",
        lead: "Кожна церква веде людей по-своєму. Кастомізація дає змогу додати свої поля, статуси, ролі та етапи процесів — без програміста і без очікування оновлень.",
        highlights: [
          "Свої поля будь-якого типу в картці людини",
          "Статуси й етапи під ваш шлях новенького",
          "Ролі з точними правами доступу",
          "Своя термінологія, логотип і кольори",
        ],
        features: [
          { icon: "SlidersHorizontal", title: "Свої поля", text: "Текст, дата, список, чекбокс, файл — у картці людини, групи, події чи служіння. Працюють у фільтрах і звітах, як стандартні." },
          { icon: "Tags", title: "Статуси й етапи", text: "Гість → новенький → член церкви — або ваш власний шлях із десяти кроків. Ви задаєте назви, порядок і що відбувається на кожному." },
          { icon: "ShieldCheck", title: "Ролі та права", text: "Лідер бачить свою групу, бухгалтер — фінанси, рецепція — сьогоднішній день. Створюйте ролі й вирішуйте, хто що бачить і редагує." },
          { icon: "Workflow", title: "Процеси під себе", text: "Погодження запитів, шлях онбордингу, підготовка події — кроки, відповідальні й нагадування налаштовуються без коду." },
          { icon: "Languages", title: "Своя термінологія", text: "«Домашня група» замість «мала група», «пресвітер» замість «лідер» — перейменуйте, і команда бачить звичні слова." },
          { icon: "Palette", title: "Брендування", text: "Логотип, кольори, назва церкви в боті, формах і на сторінках реєстрації — усе виглядає як ваше." },
        ],
        steps: [
          { title: "Опишіть, як у вас", text: "Які статуси, ролі й поля важливі саме вашій церкві — можна почати зі стандартних і змінювати поступово." },
          { title: "Налаштуйте в конструкторі", text: "Поля, статуси й ролі додаються з інтерфейсу адміністратора — без програміста, зміни діють одразу." },
          { title: "Перевірте на одній групі", text: "Увімкніть нові поля чи процес для одного служіння, зберіть відгуки лідерів — і розгортайте на всю церкву." },
          { title: "Змінюйте, коли виростете", text: "Церква змінюється — налаштування теж. Історія даних при цьому зберігається." },
        ],
        audience: [
          { role: "pastor", text: "Отримує систему, що говорить мовою його церкви і відображає її реальний процес." },
          { role: "hr", text: "Створює ролі й права для команди без звернення до підтримки." },
          { role: "leader", text: "Бачить у картках саме ті поля, які потрібні його служінню — без зайвого." },
        ],
        faq: [
          { q: "Чи потрібен програміст, щоб щось змінити?", a: "Ні. Поля, статуси, ролі й процеси налаштовує адміністратор церкви з інтерфейсу. Код не потрібен." },
          { q: "Чи можна змінити статуси, коли в базі вже є люди?", a: "Так. Перейменування зберігає історію, а при видаленні статусу система запропонує, куди перенести людей." },
          { q: "Чи працюють свої поля в аналітиці?", a: "Так. Будь-яке своє поле можна вивести у фільтр, звіт чи дашборд — так само, як стандартне." },
          { q: "Чи можна обмежити, хто бачить конкретне поле?", a: "Так. Для кожного поля задається, які ролі його бачать і редагують — наприклад, пасторські нотатки закриті від лідерів." },
        ],
        mock: {
          kind: "form",
          title: "Нове поле · картка людини",
          subtitle: "Налаштування → Поля",
          fields: [
            { label: "Назва поля", value: "Дата водного хрещення", type: "text" },
            { label: "Тип", value: "Дата", type: "select" },
            { label: "Розділ картки", value: "Духовний шлях", type: "select" },
            { label: "Хто бачить", value: "Пастор, лідери груп", type: "select" },
            { label: "Показувати у фільтрах", value: "Так", type: "check" },
            { label: "Обов'язкове для статусу", value: "Член церкви", type: "select" },
          ],
          submit: "Додати поле",
        },
        pipeline: {
          title: "Шлях свого поля — від прохання до фільтра",
          text: "Приклад: пастор просить бачити в картці дату водного хрещення.",
          stages: [
            { title: "Прохання", tone: "neutral", text: "Лідер служіння просить додати поле: «хочу бачити, хто вже охрещений». Адміністратор записує прохання.", auto: "Показує, чи таке поле вже є в іншому розділі картки." },
            { title: "Налаштування", tone: "brand", text: "Адміністратор відкриває «Налаштування → Поля»: тип, розділ картки, хто бачить і хто редагує.", auto: "Додає поле в усі картки одразу, без перезапуску системи." },
            { title: "Перевірка на одному служінні", tone: "amber", text: "Поле вмикають для однієї групи. Лідер заповнює десяток карток і каже, чого бракує.", auto: "Тримає поле прихованим для решти ролей, поки перевірка триває." },
            { title: "У роботі", tone: "green", text: "Поле відкрите всій церкві й живе у фільтрах, звітах і умовах сценаріїв.", auto: "Дає зберегти сегмент «охрещені цього року» і вивести його в дашборд." },
          ],
        },
      },
      en: {
        seoTitle: "Customisation — My Church module",
        seoDescription: "Customise My Church: your own fields, statuses and stages, roles with precise permissions, processes, terminology and branding — no developer needed.",
        title: "The system bends to your church, not the reverse",
        lead: "Every church looks after people in its own way. Customisation lets you add your own fields, statuses, roles and process stages — without a developer and without waiting for an update.",
        highlights: [
          "Custom fields of any type in the profile",
          "Statuses and stages for your newcomer path",
          "Roles with precise access rights",
          "Your own terminology, logo and colours",
        ],
        features: [
          { icon: "SlidersHorizontal", title: "Your own fields", text: "Text, date, list, checkbox, file — in the profile of a person, group, event or ministry. They work in filters and reports like the built-in ones." },
          { icon: "Tags", title: "Statuses and stages", text: "Guest → newcomer → member — or your own ten-step path. You set the names, the order and what happens at each step." },
          { icon: "ShieldCheck", title: "Roles and permissions", text: "A leader sees their group, the accountant sees finances, reception sees today. Create roles and decide who sees and edits what." },
          { icon: "Workflow", title: "Processes your way", text: "Request approvals, the onboarding path, event preparation — steps, owners and reminders configured without code." },
          { icon: "Languages", title: "Your own terminology", text: "\"Home group\" instead of \"small group\", \"elder\" instead of \"leader\" — rename it and the team sees familiar words." },
          { icon: "Palette", title: "Branding", text: "Logo, colours, the church's name in the bot, forms and registration pages — everything looks like yours." },
        ],
        steps: [
          { title: "Describe how you work", text: "Which statuses, roles and fields matter to your church — start with the defaults and change them gradually." },
          { title: "Set it up in the builder", text: "Fields, statuses and roles are added from the admin interface — no developer, changes apply at once." },
          { title: "Try it on one group", text: "Turn on new fields or a process for one ministry, gather the leaders' feedback — then roll it out to the whole church." },
          { title: "Change it as you grow", text: "The church changes, so do the settings. Data history is preserved along the way." },
        ],
        audience: [
          { role: "pastor", text: "Gets a system that speaks the language of their church and reflects its real process." },
          { role: "hr", text: "Creates roles and permissions for the team without contacting support." },
          { role: "leader", text: "Sees exactly the fields their ministry needs in profiles — nothing extra." },
        ],
        faq: [
          { q: "Do I need a developer to change something?", a: "No. Fields, statuses, roles and processes are configured by the church administrator from the interface. No code." },
          { q: "Can I change statuses when people are already in the database?", a: "Yes. Renaming keeps the history, and when you delete a status the system asks where to move the people." },
          { q: "Do custom fields work in analytics?", a: "Yes. Any custom field can go into a filter, report or dashboard — exactly like a built-in one." },
          { q: "Can I restrict who sees a specific field?", a: "Yes. Each field defines which roles can see and edit it — pastoral notes hidden from leaders, for example." },
        ],
        mock: {
          kind: "form",
          title: "New field · person profile",
          subtitle: "Settings → Fields",
          fields: [
            { label: "Field name", value: "Baptism date", type: "text" },
            { label: "Type", value: "Date", type: "select" },
            { label: "Profile section", value: "Spiritual journey", type: "select" },
            { label: "Visible to", value: "Pastor, group leaders", type: "select" },
            { label: "Show in filters", value: "Yes", type: "check" },
            { label: "Required for status", value: "Member", type: "select" },
          ],
          submit: "Add field",
        },
        pipeline: {
          title: "A custom field, from request to filter",
          text: "Example: the pastor wants the baptism date visible in the profile.",
          stages: [
            { title: "The request", tone: "neutral", text: "A ministry leader asks for a field: \"I want to see who has been baptised\". The administrator writes it down.", auto: "Shows whether such a field already exists in another profile section." },
            { title: "Setting it up", tone: "brand", text: "The administrator opens Settings → Fields: type, profile section, who sees it and who edits it.", auto: "Adds the field to every profile at once, with no restart." },
            { title: "Tried on one ministry", tone: "amber", text: "The field is switched on for one group. The leader fills in a dozen profiles and says what is missing.", auto: "Keeps the field hidden from other roles while the trial runs." },
            { title: "Live", tone: "green", text: "The field is open to the whole church and works in filters, reports and scenario conditions.", auto: "Lets you save the segment \"baptised this year\" and put it on a dashboard." },
          ],
        },
      },
    },
  },
  {
    id: "templates",
    group: "platform",
    related: ["forms", "campaigns", "events", "service-planning"],
    copy: {
      ua: {
        seoTitle: "Шаблони — модуль «Моя Церква»",
        seoDescription: "Бібліотека готових шаблонів «Моєї Церкви»: форми, розсилки, події та процеси на реальних потребах церков. Беріть, змінюйте, запускайте — і зберігайте свої.",
        title: "Не починайте з чистого аркуша — беріть готове",
        lead: "Анкета новенького, нагадування служителю, реєстрація на табір, шлях онбордингу — усе це вже зроблено іншими церквами. Беріть шаблон, змінюйте під себе, запускайте.",
        highlights: [
          "Бібліотека шаблонів форм, розсилок і подій",
          "Готові процеси: онбординг, табір, конференція",
          "Свої шаблони для повторюваних задач",
          "Обмін шаблонами між кемпусами",
        ],
        features: [
          { icon: "LayoutTemplate", title: "Бібліотека", text: "Десятки шаблонів, зроблених на реальних потребах церков: від анкети гостя до чек-листа підготовки Різдва." },
          { icon: "ClipboardList", title: "Форми й анкети", text: "Анкета новенького, реєстрація на курс, опитування після події — з правильними полями, які одразу пишуться в картку." },
          { icon: "Mail", title: "Розсилки й нагадування", text: "Привітання новенького, нагадування служителю, запрошення на групу — тексти, які можна взяти як є або підправити." },
          { icon: "Tent", title: "Події та табори", text: "Конференція, табір, вечір молитви — з готовою структурою: реєстрація, команда, розклад, нагадування." },
          { icon: "Copy", title: "Свої шаблони", text: "Провели служіння один раз добре — збережіть як шаблон. Наступного тижня порядок служіння готовий за 5 хвилин." },
          { icon: "Share2", title: "Обмін між кемпусами", text: "Шаблон, створений у центральній церкві, доступний усім кемпусам — з єдиним стандартом." },
        ],
        steps: [
          { title: "Оберіть шаблон", text: "Знайдіть у бібліотеці за типом: форма, розсилка, подія, процес — і подивіться, як він виглядає." },
          { title: "Підправте під себе", text: "Змініть назви, поля, тексти й відповідальних. Усе, що не потрібно, — приберіть." },
          { title: "Запустіть", text: "Форма опублікована, розсилка запланована, подія створена — за хвилини, а не за вечір." },
          { title: "Збережіть як свій", text: "Те, що працює саме у вас, стає шаблоном вашої церкви — для наступного разу і для інших кемпусів." },
        ],
        audience: [
          { role: "pastor", text: "Запускає онбординг чи підготовку до Великодня за перевіреним сценарієм, а не з нуля." },
          { role: "leader", text: "Створює порядок служіння чи реєстрацію на подію за 5 хвилин зі свого шаблону." },
          { role: "reception", text: "Друкує анкети, відкриває форми реєстрації та надсилає стандартні відповіді — без пошуку «де той файл»." },
        ],
        faq: [
          { q: "Чи можна змінювати шаблони?", a: "Так, будь-який. Шаблон — це стартова точка: змініть поля, тексти, кроки. Оригінал у бібліотеці залишиться." },
          { q: "Чи можна зберегти власний шаблон?", a: "Так. Будь-яку форму, розсилку, подію чи порядок служіння можна зберегти як шаблон церкви одним натисканням." },
          { q: "Чи є шаблони для конкретних сезонів?", a: "Так: Різдво, Великдень, літній табір, старт навчального року — з подіями, розсилками й чек-листами підготовки." },
          { q: "Шаблони однакові для всіх церков?", a: "Бібліотека спільна, але ваші зміни бачить лише ваша церква. Свої шаблони можна відкрити іншим кемпусам вашої церкви." },
        ],
        mock: {
          kind: "board",
          title: "Бібліотека шаблонів",
          subtitle: "48 шаблонів · 6 своїх",
          columns: [
            {
              title: "Форми",
              cards: [
                { title: "Анкета новенького", sub: "8 полів · одразу в картку", tag: { label: "Популярний", tone: "brand" } },
                { title: "Реєстрація на курс", sub: "Альфа, Основи віри" },
                { title: "Відгук після події", sub: "5 запитань" },
              ],
            },
            {
              title: "Розсилки",
              cards: [
                { title: "Привітання новенького", sub: "Telegram · того ж дня" },
                { title: "Нагадування служителю", sub: "За день до служіння", tag: { label: "Автомат", tone: "green" } },
                { title: "Запрошення в групу", sub: "Через 2 тижні після візиту" },
              ],
            },
            {
              title: "Події й процеси",
              cards: [
                { title: "Літній табір", sub: "Реєстрація, команда, розклад" },
                { title: "Шлях новенького", sub: "5 кроків до членства", tag: { label: "Свій", tone: "violet" } },
                { title: "Різдвяне служіння", sub: "Чек-лист підготовки" },
              ],
            },
          ],
        },
        pipeline: {
          title: "Шлях шаблону — від бібліотеки до власного",
          text: "Приклад: реєстрація на літній табір, яку церква проводить щороку.",
          stages: [
            { title: "Обрали", tone: "neutral", text: "Адміністратор знаходить у бібліотеці «Літній табір» і відкриває перегляд: поля, листи, кроки підготовки.", auto: "Показує, які модулі шаблон зачепить: форми, події, розсилки." },
            { title: "Підправили", tone: "brand", text: "Свої дати, вартість, вік дітей і відповідальні. Зайві поля прибирають одразу.", auto: "Підставляє назву церкви, логотип і контакти в усі тексти шаблону." },
            { title: "Запустили", tone: "amber", text: "Форма опублікована, подія створена, посилання й QR — в оголошення з кафедри.", auto: "Ставить задачі відповідальним і планує нагадування за тиждень і за день до заїзду." },
            { title: "Зберегли як свій", tone: "green", text: "Після табору шаблон із вашими правками стає шаблоном церкви — на наступний рік.", auto: "Відкриває його іншим кемпусам і зберігає версію цьогорічного табору." },
          ],
        },
      },
      en: {
        seoTitle: "Templates — My Church module",
        seoDescription: "A library of My Church templates: forms, campaigns, events and processes built on real church needs. Pick one, adjust it, launch — and save your own.",
        title: "Never start from a blank page",
        lead: "A newcomer form, a volunteer reminder, camp registration, an onboarding path — other churches have already built all of it. Take a template, adjust it, launch.",
        highlights: [
          "Library of form, campaign and event templates",
          "Ready processes: onboarding, camp, conference",
          "Your own templates for recurring tasks",
          "Templates shared between campuses",
        ],
        features: [
          { icon: "LayoutTemplate", title: "The library", text: "Dozens of templates built on real church needs: from a guest form to a Christmas preparation checklist." },
          { icon: "ClipboardList", title: "Forms and surveys", text: "Newcomer form, course registration, post-event survey — with the right fields that write straight to the profile." },
          { icon: "Mail", title: "Campaigns and reminders", text: "Newcomer greeting, volunteer reminder, group invitation — texts to use as they are or tweak." },
          { icon: "Tent", title: "Events and camps", text: "Conference, camp, prayer evening — with a ready structure: registration, team, schedule, reminders." },
          { icon: "Copy", title: "Your own templates", text: "Ran a service well once — save it as a template. Next week the order of service is ready in 5 minutes." },
          { icon: "Share2", title: "Shared across campuses", text: "A template created at the central church is available to every campus — one standard for all." },
        ],
        steps: [
          { title: "Pick a template", text: "Find it in the library by type — form, campaign, event, process — and preview how it looks." },
          { title: "Adjust it", text: "Change names, fields, texts and owners. Remove whatever you don't need." },
          { title: "Launch", text: "The form is published, the campaign scheduled, the event created — in minutes, not an evening." },
          { title: "Save it as yours", text: "What works for you becomes your church's template — for next time and for other campuses." },
        ],
        audience: [
          { role: "pastor", text: "Launches onboarding or Easter preparation from a proven scenario, not from scratch." },
          { role: "leader", text: "Builds an order of service or an event registration in 5 minutes from their own template." },
          { role: "reception", text: "Prints forms, opens registration pages and sends standard replies — without hunting for \"that file\"." },
        ],
        faq: [
          { q: "Can templates be edited?", a: "Yes, any of them. A template is a starting point: change fields, texts, steps. The original stays in the library." },
          { q: "Can I save my own template?", a: "Yes. Any form, campaign, event or order of service can be saved as a church template in one tap." },
          { q: "Are there templates for specific seasons?", a: "Yes: Christmas, Easter, summer camp, the start of the academic year — with events, campaigns and preparation checklists." },
          { q: "Are templates the same for every church?", a: "The library is shared, but your changes are visible only to your church. Your own templates can be opened to your other campuses." },
        ],
        mock: {
          kind: "board",
          title: "Template library",
          subtitle: "48 templates · 6 your own",
          columns: [
            {
              title: "Forms",
              cards: [
                { title: "Newcomer form", sub: "8 fields · straight to profile", tag: { label: "Popular", tone: "brand" } },
                { title: "Course registration", sub: "Alpha, Foundations" },
                { title: "Post-event feedback", sub: "5 questions" },
              ],
            },
            {
              title: "Campaigns",
              cards: [
                { title: "Newcomer greeting", sub: "Telegram · same day" },
                { title: "Volunteer reminder", sub: "Day before the service", tag: { label: "Automated", tone: "green" } },
                { title: "Group invitation", sub: "2 weeks after first visit" },
              ],
            },
            {
              title: "Events and processes",
              cards: [
                { title: "Summer camp", sub: "Registration, team, schedule" },
                { title: "Newcomer path", sub: "5 steps to membership", tag: { label: "Yours", tone: "violet" } },
                { title: "Christmas service", sub: "Preparation checklist" },
              ],
            },
          ],
        },
        pipeline: {
          title: "A template, from the library to your own",
          text: "Example: summer camp registration, which the church runs every year.",
          stages: [
            { title: "Picked", tone: "neutral", text: "The administrator finds \"Summer camp\" in the library and previews it: fields, messages, preparation steps.", auto: "Shows which modules the template touches: forms, events, campaigns." },
            { title: "Adjusted", tone: "brand", text: "Your dates, price, children's ages and owners. Fields you don't need are removed.", auto: "Drops the church name, logo and contacts into every text in the template." },
            { title: "Launched", tone: "amber", text: "The form is published, the event created, the link and QR go into the announcement.", auto: "Assigns tasks to owners and schedules reminders a week and a day before arrival." },
            { title: "Saved as yours", tone: "green", text: "After the camp the template with your edits becomes your church's own — ready for next year.", auto: "Opens it to your other campuses and keeps this year's version." },
          ],
        },
      },
    },
  },
  {
    id: "telegram-bot",
    group: "outreach",
    related: ["telegram", "events", "forms", "onboarding"],
    copy: {
      ua: {
        seoTitle: "Telegram-бот — модуль «Моя Церква»",
        seoDescription: "Telegram-бот церкви з вашою назвою й логотипом: розклад, реєстрації на події, відмітка приходу за QR, відповіді на типові запитання і перший контакт з новеньким.",
        title: "Церква відповідає людям будь-якої години",
        lead: "Власний Telegram-бот з назвою і логотипом вашої церкви. Розклад служінь, реєстрація на події, відмітка приходу на вході й відповіді на типові запитання — людина отримує все у звичному месенджері, а команда — менше повідомлень «а коли?».",
        highlights: [
          "Бот з назвою й логотипом вашої церкви",
          "Розклад, події та реєстрації в меню",
          "Відмітка приходу за одним натисканням",
          "Відповіді на типові запитання з бази знань",
        ],
        features: [
          { icon: "Bot", title: "Свій бот, своя назва", text: "@YourChurchBot з логотипом і привітанням вашими словами. Люди бачать церкву, а не платформу." },
          { icon: "CalendarDays", title: "Розклад завжди під рукою", text: "Служіння, зустрічі груп, події тижня — актуальні дані з календаря «Моєї Церкви», без ручного оновлення." },
          { icon: "Ticket", title: "Реєстрація в два натискання", text: "Табір, конференція, курс — людина обирає подію, підтверджує дані з картки — і вже в списку учасників." },
          { icon: "ScanLine", title: "Відмітка приходу в боті", text: "QR на вході чи кнопка «Я тут» — явка на служінні або зустрічі групи записана без рецепції." },
          { icon: "HelpCircle", title: "Відповіді на запитання", text: "«Де припаркуватись?», «Чи є дитяча кімната?» — бот відповідає з бази знань церкви, а складне передає людині." },
          { icon: "UserPlus", title: "Перший контакт новенького", text: "Натиснув «Старт» — і людина вже в базі зі статусом «гість», а відповідальний отримав нагадування написати." },
        ],
        steps: [
          { title: "Створіть бота", text: "Хвилина в BotFather: назва, логотип, токен — і бот з'явився в налаштуваннях «Моєї Церкви»." },
          { title: "Зберіть меню", text: "Увімкніть розділи: розклад, події, реєстрації, моя група, запитання. Тексти привітання — ваші." },
          { title: "Поставте QR на вході", text: "Роздрукуйте QR-код — гості реєструються, члени церкви відмічають прихід, і всі підписуються на нагадування." },
          { title: "Навчіть бота відповідати", text: "Додайте типові запитання й відповіді або підключіть базу знань — бот перекриє більшість «а де?» і «а коли?»." },
        ],
        audience: [
          { role: "member", text: "Дивиться розклад, реєструється на події й отримує нагадування про свою групу — без дзвінків у церкву." },
          { role: "visitor", text: "Сканує QR, натискає «Старт» — і отримує привітання, адресу й запрошення на наступне служіння." },
          { role: "volunteer", text: "Бачить свій графік, підтверджує участь або просить заміну прямо в боті." },
          { role: "reception", text: "Відмічає прихід без паперових списків і відповідає лише на те, з чим не впорався бот." },
        ],
        faq: [
          { q: "Чим бот церкви відрізняється від інтеграції з Telegram?", a: "Інтеграція з'єднує Telegram з базою для розсилок і сповіщень. Бот — це те, з чим взаємодіє людина: меню, розклад, реєстрації, відмітка приходу. Інтеграція працює всередині бота." },
          { q: "Чи потрібно знати програмування?", a: "Ні. Ви створюєте бота в BotFather за інструкцією, вставляєте токен — а меню й тексти налаштовуєте в «Моїй Церкві»." },
          { q: "Чи може бот відповідати на довільні запитання?", a: "На типові — з бази знань і ваших відповідей. Якщо не знає — передає повідомлення відповідальній людині й повідомляє про це користувача." },
          { q: "Чи можна кілька ботів для кемпусів?", a: "Так. Кожен кемпус може мати свій бот зі своїм розкладом — або один спільний, який запитує, яку локацію людина відвідує." },
        ],
        mock: {
          kind: "chat",
          title: "Бот церкви «Джерело»",
          subtitle: "386 підписників · онлайн",
          messages: [
            { from: "user", text: "/start", time: "Нд 9:41" },
            { from: "bot", text: "Вітаємо в церкві «Джерело», Дмитре. Що вас цікавить: розклад, події, моя група?", time: "Нд 9:41" },
            { from: "user", text: "Розклад на тиждень" },
            { from: "bot", text: "Нд 10:00 — служіння · Ср 19:00 — молитва · Чт 19:00 — домашня група" },
            { from: "user", text: "Записатися на табір" },
            { from: "bot", text: "Літній табір 14–20 липня. Ви в списку. Нагадаю за тиждень." },
          ],
          input: "Написати боту…",
        },
      },
      en: {
        seoTitle: "Telegram bot — My Church module",
        seoDescription: "Your church's own Telegram bot with your name and logo: schedule, event sign-ups, QR check-in, answers to common questions and a first contact for newcomers.",
        title: "Your church answers people at any hour",
        lead: "Your own Telegram bot with your church's name and logo. Service schedule, event sign-ups, check-in at the door and answers to common questions — people get it all in a familiar messenger, and the team gets fewer \"when is it?\" messages.",
        highlights: [
          "A bot with your church's name and logo",
          "Schedule, events and sign-ups in the menu",
          "Check-in with a single tap",
          "Answers to common questions from the knowledge base",
        ],
        features: [
          { icon: "Bot", title: "Your bot, your name", text: "@YourChurchBot with a logo and a greeting in your own words. People see the church, not the platform." },
          { icon: "CalendarDays", title: "Schedule always at hand", text: "Services, group meetings, this week's events — live data from the My Church calendar, no manual updates." },
          { icon: "Ticket", title: "Sign up in two taps", text: "Camp, conference, course — a person picks the event, confirms the details from their profile — and they're on the list." },
          { icon: "ScanLine", title: "Check-in in the bot", text: "A QR at the door or an \"I'm here\" button — attendance at the service or group meeting is recorded without reception." },
          { icon: "HelpCircle", title: "Answers to questions", text: "\"Where do I park?\", \"Is there a kids' room?\" — the bot answers from the church knowledge base and hands the hard ones to a person." },
          { icon: "UserPlus", title: "A newcomer's first contact", text: "Tapped Start — and the person is in the database as a guest, while their owner gets a reminder to write." },
        ],
        steps: [
          { title: "Create the bot", text: "A minute in BotFather: name, logo, token — and the bot appears in My Church settings." },
          { title: "Build the menu", text: "Turn on sections: schedule, events, sign-ups, my group, questions. The greeting texts are yours." },
          { title: "Put a QR at the door", text: "Print the QR code — guests register, members check in, and everyone subscribes to reminders." },
          { title: "Teach it to answer", text: "Add common questions and answers or connect the knowledge base — the bot covers most of the \"where?\" and \"when?\"." },
        ],
        audience: [
          { role: "member", text: "Checks the schedule, signs up for events and gets group reminders — without calling the church." },
          { role: "visitor", text: "Scans the QR, taps Start — and gets a greeting, the address and an invitation to the next service." },
          { role: "volunteer", text: "Sees their rota, confirms or asks for cover right in the bot." },
          { role: "reception", text: "Runs check-in without paper lists and answers only what the bot couldn't." },
        ],
        faq: [
          { q: "How is the church bot different from the Telegram integration?", a: "The integration connects Telegram to the database for campaigns and notifications. The bot is what a person interacts with: menu, schedule, sign-ups, check-in. The integration works inside the bot." },
          { q: "Do I need to know how to code?", a: "No. You create the bot in BotFather following the guide, paste the token — and set up the menu and texts in My Church." },
          { q: "Can the bot answer free-form questions?", a: "Common ones — from the knowledge base and your answers. If it doesn't know, it passes the message to the owner and tells the person so." },
          { q: "Can I have several bots for campuses?", a: "Yes. Each campus can have its own bot with its own schedule — or one shared bot that asks which location the person attends." },
        ],
        mock: {
          kind: "chat",
          title: "Dzherelo Church bot",
          subtitle: "386 subscribers · online",
          messages: [
            { from: "user", text: "/start", time: "Sun 9:41" },
            { from: "bot", text: "Welcome to Dzherelo Church, Dmytro. What would you like: schedule, events, my group?", time: "Sun 9:41" },
            { from: "user", text: "This week's schedule" },
            { from: "bot", text: "Sun 10:00 — service · Wed 19:00 — prayer · Thu 19:00 — Obolon group" },
            { from: "user", text: "Sign up for camp" },
            { from: "bot", text: "Summer camp, 14–20 July. You're on the list. I'll remind you a week before." },
          ],
          input: "Message the bot…",
        },
      },
    },
  },
];
