import type { ModuleDetail } from "./types";

/* Module pages: rooms, inventory, infrastructure — their catalogue group is the `group` field below. */
export const resourcesModules: ModuleDetail[] = [
  {
    id: "rooms",
    group: "property",
    related: ["calendar", "events", "groups", "infrastructure"],
    copy: {
      ua: {
        seoTitle: "Кімнати — модуль «Моя Церква»",
        seoDescription: "Бронювання залів і кімнат церкви без накладок: розклад приміщень на тиждень, заявки від лідерів з телефону, підтвердження та нагадування відповідальним.",
        title: "Кожна кімната — за розкладом, без накладок",
        lead: "Модуль «Кімнати» показує, хто і коли займає кожен зал, кімнату чи дитячу. Лідер бронює з телефону, рецепція підтверджує, і дві групи більше не зустрічаються в одних дверях.",
        highlights: [
          "Розклад усіх приміщень на тиждень",
          "Бронювання з телефону за хвилину",
          "Накладки система не пропустить",
          "Пов'язано з календарем і подіями",
        ],
        features: [
          { icon: "DoorOpen", title: "Перелік приміщень", text: "Зали, кімнати, дитяча, кухня, двір: місткість, обладнання і хто відповідає за ключі." },
          { icon: "CalendarDays", title: "Розклад на тиждень", text: "Усі бронювання на одному екрані: по днях, по кімнатах, по кемпусах. Вільні вікна видно одразу." },
          { icon: "AlertTriangle", title: "Захист від накладок", text: "Дві заявки на один час — система зупинить другу й запропонує вільну кімнату поруч." },
          { icon: "Repeat", title: "Повторювані бронювання", text: "Група щочетверга о 19:00 — одне бронювання на весь сезон, з винятками на свята." },
          { icon: "ClipboardCheck", title: "Заявка та підтвердження", text: "Лідер подає заявку, відповідальний підтверджує одним натисканням. Для своїх кімнат команди — без погодження." },
          { icon: "Bell", title: "Нагадування", text: "Лідеру й тому, хто відкриває приміщення, — за день до зустрічі, у Telegram або SMS." },
        ],
        steps: [
          { title: "Опишіть приміщення", text: "Додайте зали й кімнати: місткість, обладнання, хто відповідає. Для кількох кемпусів — кожен зі своїми." },
          { title: "Перенесіть постійні зустрічі", text: "Служіння, групи й репетиції — як повторювані бронювання на сезон." },
          { title: "Відкрийте бронювання команді", text: "Лідери подають заявки самі, рецепція бачить розклад дня, накладки більше не з'являються." },
        ],
        audience: [
          { role: "reception", text: "Бачить розклад дня, бронює кімнату для гостя чи зустрічі й знає, у кого ключі." },
          { role: "leader", text: "Бронює кімнату для групи з телефону й бачить, коли вона вільна, — без дзвінків в офіс." },
          { role: "pastor", text: "Бачить, наскільки завантажені приміщення й де є вільні вікна для нових груп." },
        ],
        faq: [
          { q: "Що буде, якщо дві групи забронюють одну кімнату?", a: "Система не дасть створити друге бронювання на той самий час: покаже, хто вже зайняв кімнату, і запропонує вільні варіанти поруч." },
          { q: "Чи може будь-хто бронювати кімнати?", a: "Ви обираєте: або лідери бронюють самі, або подають заявку, а рецепція чи адміністратор підтверджує. Права можна задати окремо для кожного приміщення." },
          { q: "Чи видно бронювання в загальному календарі церкви?", a: "Так. Кожне бронювання прив'язане до події, зустрічі групи або служіння й з'являється в календарі автоматично. Кімнату можна обрати прямо при створенні події." },
          { q: "У нас кілька будівель. Як це працює?", a: "Приміщення прив'язуються до кемпусу. Кожна локація бачить свій розклад, а адміністратор — усі будівлі разом." },
        ],
        mock: {
          kind: "calendar",
          title: "Приміщення · тиждень",
          subtitle: "Великий зал · Кімната 2 · Дитяча",
          days: ["Пн", "Вт", "Ср", "Чт", "Пт", "Сб", "Нд"],
          events: [
            { day: 0, start: 1, span: 2, title: "Штаб команди", tone: "neutral" },
            { day: 1, start: 5, span: 2, title: "Група «Центр»", tone: "green" },
            { day: 2, start: 3, span: 2, title: "Альфа-курс", tone: "brand" },
            { day: 3, start: 5, span: 2, title: "Молодіжка", tone: "green" },
            { day: 4, start: 4, span: 3, title: "Репетиція", tone: "violet" },
            { day: 5, start: 2, span: 3, title: "Весілля", tone: "amber" },
            { day: 6, start: 0, span: 3, title: "Служіння", tone: "brand" },
            { day: 6, start: 4, span: 1, title: "Рада церкви", tone: "neutral" },
          ],
        },
      },
      en: {
        seoTitle: "Rooms — MyChurch module",
        seoDescription: "Book church halls and rooms without double-booking: a weekly schedule of every space, requests from leaders on their phones, confirmations and reminders.",
        title: "Every room on schedule, never double-booked",
        lead: "The Rooms module shows who is using each hall, room or kids' space, and when. A leader books from their phone, reception confirms, and two groups never turn up at the same door again.",
        highlights: [
          "A weekly schedule of every space",
          "Book from a phone in a minute",
          "Double-bookings are blocked automatically",
          "Linked to the calendar and events",
        ],
        features: [
          { icon: "DoorOpen", title: "Room directory", text: "Halls, rooms, kids' space, kitchen, courtyard: capacity, equipment and who holds the keys." },
          { icon: "CalendarDays", title: "Weekly schedule", text: "Every booking on one screen: by day, by room, by campus. Free slots are visible at a glance." },
          { icon: "AlertTriangle", title: "Double-booking protection", text: "Two requests for the same slot — the system stops the second and suggests a free room nearby." },
          { icon: "Repeat", title: "Recurring bookings", text: "A group every Thursday at 19:00 is one booking for the whole season, with exceptions for holidays." },
          { icon: "ClipboardCheck", title: "Request and confirmation", text: "A leader submits a request, the owner confirms with one tap. For a team's own rooms — no approval needed." },
          { icon: "Bell", title: "Reminders", text: "To the leader and whoever opens up — the day before, in Telegram or by SMS." },
        ],
        steps: [
          { title: "Describe your spaces", text: "Add halls and rooms: capacity, equipment, who is responsible. Several campuses — each with its own." },
          { title: "Move the regular meetings over", text: "Services, groups and rehearsals — as recurring bookings for the season." },
          { title: "Open booking to the team", text: "Leaders submit requests themselves, reception sees the day's schedule, double-bookings stop happening." },
        ],
        audience: [
          { role: "reception", text: "Sees the day's schedule, books a room for a guest or a meeting and knows who has the keys." },
          { role: "leader", text: "Books a room for their group from a phone and sees when it's free — no calls to the office." },
          { role: "pastor", text: "Sees how busy the building is and where there are free slots for new groups." },
        ],
        faq: [
          { q: "What happens if two groups book the same room?", a: "The system won't create a second booking for the same slot: it shows who already has the room and suggests free alternatives nearby." },
          { q: "Can anyone book a room?", a: "Your choice: either leaders book directly, or they submit a request and reception or an administrator confirms. Permissions can be set per room." },
          { q: "Do bookings show up in the church calendar?", a: "Yes. Every booking is tied to an event, a group meeting or a service and appears in the calendar automatically. You can pick the room while creating the event." },
          { q: "We have several buildings. How does that work?", a: "Rooms belong to a campus. Each location sees its own schedule, and an administrator sees every building together." },
        ],
        mock: {
          kind: "calendar",
          title: "Rooms · this week",
          subtitle: "Main hall · Room 2 · Kids room",
          days: ["Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"],
          events: [
            { day: 0, start: 1, span: 2, title: "Staff meeting", tone: "neutral" },
            { day: 1, start: 5, span: 2, title: "Centre group", tone: "green" },
            { day: 2, start: 3, span: 2, title: "Alpha course", tone: "brand" },
            { day: 3, start: 5, span: 2, title: "Youth", tone: "green" },
            { day: 4, start: 4, span: 3, title: "Rehearsal", tone: "violet" },
            { day: 5, start: 2, span: 3, title: "Wedding", tone: "amber" },
            { day: 6, start: 0, span: 3, title: "Service", tone: "brand" },
            { day: 6, start: 4, span: 1, title: "Church board", tone: "neutral" },
          ],
        },
      },
    },
  },
  {
    id: "inventory",
    group: "property",
    related: ["infrastructure", "rooms", "ministries", "tables"],
    copy: {
      ua: {
        seoTitle: "Інвентаризація — модуль «Моя Церква»",
        seoDescription: "Облік майна церкви: мікрофони, проєктори, стільці, матеріали. Хто взяв, де лежить, коли повернути — з QR-кодами, історією руху та нагадуваннями.",
        title: "Хто взяв, де лежить, коли поверне — завжди відомо",
        lead: "Модуль «Інвентаризація» веде облік усього, що належить церкві: від мікрофонів і проєкторів до стільців і наметів для табору. Видали річ за QR-кодом — і система знає, у кого вона й коли має повернутись.",
        highlights: [
          "Картка кожної речі з фото та серійним номером",
          "Видача й повернення за QR-кодом",
          "Нагадування, коли пора повернути",
          "Історія: хто брав і коли",
        ],
        features: [
          { icon: "Package", title: "Картка предмета", text: "Назва, фото, категорія, серійний номер, дата придбання й вартість. Комплекти — як один предмет зі списком складу." },
          { icon: "QrCode", title: "Видача за QR", text: "Наклейка з QR на кожній речі: відсканували телефоном — вказали, хто бере й до коли. Повернення — так само." },
          { icon: "MapPin", title: "Де що лежить", text: "Кімната, шафа, полиця, кемпус. Шукаєте стійку для мікрофона — бачите, що вона в «Кімнаті 2», у Дмитра." },
          { icon: "History", title: "Історія руху", text: "Хто брав, коли повернув, у якому стані. Зникло — видно, на кому обірвався ланцюжок." },
          { icon: "BellRing", title: "Нагадування про повернення", text: "Термін минув — служитель отримує повідомлення в Telegram, відповідальний за склад — зведення." },
          { icon: "ClipboardCheck", title: "Інвентаризація за годину", text: "Скануєте речі по кімнатах — система сама показує, чого не вистачає і що ще не обліковано." },
        ],
        steps: [
          { title: "Опишіть майно", text: "Додайте речі вручну або імпортом із таблиці. Роздрукуйте QR-наклейки для того, що беруть найчастіше." },
          { title: "Призначте відповідальних", text: "Звук — команді прославлення, дитячі матеріали — «Дитячому містечку». У кожної категорії є господар." },
          { title: "Видавайте й повертайте", text: "Служителі сканують QR при видачі та поверненні. Раз на сезон — швидка звірка по кімнатах." },
        ],
        audience: [
          { role: "leader", text: "Бачить усе обладнання свого служіння, хто що взяв і що потрібно докупити до події." },
          { role: "volunteer", text: "Бере мікрофон або проєктор за QR-кодом і отримує нагадування, коли пора повернути." },
          { role: "accountant", text: "Має перелік майна з вартістю й датами придбання — для обліку основних засобів і звітів." },
        ],
        faq: [
          { q: "Чи обов'язково клеїти QR-коди?", a: "Ні. QR прискорює видачу, але кожну річ можна знайти пошуком за назвою чи номером і видати вручну. Для дрібних матеріалів ведіть кількість без кодів." },
          { q: "Як облікувати витратні матеріали — папір, каву, свічки?", a: "Для них є облік кількості: списуєте витрату, система показує залишок і попереджає, коли він нижче мінімуму." },
          { q: "Ми даємо техніку іншим церквам. Це можливо?", a: "Так. Видачу можна оформити на зовнішню організацію або людину не з вашої бази, з терміном повернення й нагадуванням." },
          { q: "Чи можна вести майно окремо по кемпусах?", a: "Так. Кожна річ прив'язана до кемпусу й приміщення. Адміністратор бачить усе, локальна команда — своє." },
        ],
        mock: {
          kind: "table",
          title: "Обладнання",
          subtitle: "146 предметів · 9 на руках",
          columns: ["Предмет", "У кого", "Де", "Повернути"],
          rows: [
            { cells: ["Мікрофон Shure SM58", "Дмитро Лис", "Великий зал", "Нд, 18:00"], badge: { label: "Видано", tone: "brand" } },
            { cells: ["Проєктор Epson", "Андрій Мельник", "Кімната 2", "Вчора"], badge: { label: "Прострочено", tone: "red" } },
            { cells: ["Стійка для нот ×4", "Олена Ковальчук", "Репетиційна", "Сб"], badge: { label: "Видано", tone: "brand" } },
            { cells: ["Ноутбук для трансляції", "Ірина Шевчук", "Великий зал", "Нд"], badge: { label: "Видано", tone: "brand" } },
            { cells: ["Намет 6-місний ×3", "—", "Склад", "—"], badge: { label: "На складі", tone: "green" } },
          ],
        },
        pipeline: {
          title: "Шлях речі: від бронювання до повернення",
          text: "Приклад для проєктора, який беруть на виїзд малої групи. Статус змінюється скануванням QR.",
          stages: [
            { title: "Заброньовано", tone: "neutral", text: "Лідер бронює проєктор на суботу, щоб його не забрали на іншу подію.", auto: "Позначає річ зайнятою на ці дати й прибирає її з доступних до бронювання." },
            { title: "Видано", tone: "brand", text: "Відповідальний сканує QR: хто бере, до якої дати, у якому стані річ виїжджає.", auto: "Записує видачу в історію речі й ставить термін повернення." },
            { title: "На руках", tone: "amber", text: "У картці видно, у кого річ і де вона зараз. Термін підходить — статус змінюється сам.", auto: "Нагадує служителю в Telegram за день до терміну, а після — щодня." },
            { title: "Повернуто", tone: "green", text: "Скан QR при поверненні, позначка про стан, річ знову на полиці.", auto: "Оновлює місце зберігання й закриває запис у історії руху." },
            { title: "У ремонті", tone: "red", text: "Річ повернулась пошкодженою: лампа перегоріла, кабель обірваний.", auto: "Створює заявку відповідальному й ховає річ зі списку доступних до полагодження." },
          ],
        },
      },
      en: {
        seoTitle: "Inventory — MyChurch module",
        seoDescription: "Keep track of church property: microphones, projectors, materials. Who has it, where it is and when it's due back — with QR codes, history and reminders.",
        title: "Always know who has what and where",
        lead: "The Inventory module keeps a record of everything the church owns, from microphones and projectors to chairs and camp tents. Check an item out by QR code and the system knows who has it and when it's due back.",
        highlights: [
          "A record for every item with photo and serial number",
          "Check-out and return by QR code",
          "Reminders when something is due back",
          "History: who took it and when",
        ],
        features: [
          { icon: "Package", title: "Item record", text: "Name, photo, category, serial number, purchase date and value. Kits are one item with a list of contents." },
          { icon: "QrCode", title: "Check-out by QR", text: "A QR sticker on every item: scan it with a phone, say who is taking it and until when. Returns work the same way." },
          { icon: "MapPin", title: "Where things live", text: "Room, cupboard, shelf, campus. Looking for a mic stand — you can see it's in Room 2, with Dmytro." },
          { icon: "History", title: "Movement history", text: "Who took it, when it came back, in what condition. If something goes missing, you can see where the chain broke." },
          { icon: "BellRing", title: "Return reminders", text: "Past the due date — the volunteer gets a Telegram message, the storekeeper gets a summary." },
          { icon: "ClipboardCheck", title: "Stock-take in an hour", text: "Scan items room by room — the system shows what's missing and what isn't on record yet." },
        ],
        steps: [
          { title: "Record your property", text: "Add items by hand or import from a spreadsheet. Print QR stickers for the things people borrow most." },
          { title: "Assign keepers", text: "Sound gear to the worship team, kids' materials to Kids Town. Every category has someone in charge." },
          { title: "Check out and return", text: "Volunteers scan the QR on the way out and on the way back. Once a season — a quick room-by-room check." },
        ],
        audience: [
          { role: "leader", text: "Sees all of their ministry's equipment, who has what and what needs buying before an event." },
          { role: "volunteer", text: "Takes a microphone or projector by QR code and gets a reminder when it's due back." },
          { role: "accountant", text: "Has a full list of property with values and purchase dates — for fixed-asset records and reports." },
        ],
        faq: [
          { q: "Do we have to put QR codes on everything?", a: "No. QR speeds up check-out, but any item can be found by name or number and issued by hand. For small consumables, just track quantities without codes." },
          { q: "How do we track consumables — paper, coffee, candles?", a: "They use quantity tracking: you log what's used, the system shows what's left and warns when it drops below the minimum." },
          { q: "We lend equipment to other churches. Is that possible?", a: "Yes. A check-out can be made to an outside organisation or a person who isn't in your database, with a due date and a reminder." },
          { q: "Can we keep property separately per campus?", a: "Yes. Every item belongs to a campus and a room. An administrator sees everything, a local team sees its own." },
        ],
        mock: {
          kind: "table",
          title: "Equipment",
          subtitle: "146 items · 9 checked out",
          columns: ["Item", "Who", "Where", "Due"],
          rows: [
            { cells: ["Shure SM58 microphone", "Dmytro Lys", "Main hall", "Sun, 18:00"], badge: { label: "Checked out", tone: "brand" } },
            { cells: ["Epson projector", "Andrii Melnyk", "Room 2", "Yesterday"], badge: { label: "Overdue", tone: "red" } },
            { cells: ["Music stand ×4", "Olena Kovalchuk", "Rehearsal room", "Sat"], badge: { label: "Checked out", tone: "brand" } },
            { cells: ["Streaming laptop", "Iryna Shevchuk", "Main hall", "Sun"], badge: { label: "Checked out", tone: "brand" } },
            { cells: ["6-person tent ×3", "—", "Storage", "—"], badge: { label: "In stock", tone: "green" } },
          ],
        },
        pipeline: {
          title: "An item's path: from booking to return",
          text: "Example for a projector taken on a small group's trip. The status changes with a QR scan.",
          stages: [
            { title: "Booked", tone: "neutral", text: "A leader books the projector for Saturday so it isn't taken for another event.", auto: "Marks the item busy for those dates and removes it from what's available to book." },
            { title: "Checked out", tone: "brand", text: "The keeper scans the QR: who is taking it, until when, and in what condition it leaves.", auto: "Logs the check-out in the item's history and sets the due date." },
            { title: "Out", tone: "amber", text: "The record shows who has the item and where it is. As the date nears, the status changes itself.", auto: "Reminds the volunteer in Telegram the day before, and daily once it's overdue." },
            { title: "Returned", tone: "green", text: "A QR scan on the way back, a note on its condition, and the item is on the shelf again.", auto: "Updates its storage location and closes the entry in the movement history." },
            { title: "In repair", tone: "red", text: "The item came back damaged: a blown lamp, a broken cable.", auto: "Creates a request for the keeper and hides the item from the available list until it's fixed." },
          ],
        },
      },
    },
  },
  {
    id: "infrastructure",
    group: "property",
    related: ["rooms", "inventory", "campuses", "projects"],
    copy: {
      ua: {
        seoTitle: "Інфраструктура — модуль «Моя Церква»",
        seoDescription: "Паспорт кожної будівлі й системи церкви: котел, електрика, вентиляція, дах. Графік обслуговування, заявки на ремонт, підрядники та витрати в одному місці.",
        title: "Будівля церкви не ламається несподівано",
        lead: "Модуль «Інфраструктура» зберігає паспорт кожної будівлі та системи: коли обслуговували котел, хто відповідає за електрику, скільки коштував ремонт даху. Заявки на ремонт подаються з телефону, а планове обслуговування нагадує про себе саме.",
        highlights: [
          "Паспорт кожної будівлі та системи",
          "Графік обслуговування з нагадуваннями",
          "Заявки на ремонт із телефону",
          "Підрядники, документи й витрати поруч",
        ],
        features: [
          { icon: "Building2", title: "Паспорт об'єкта", text: "Будівля, приміщення, система: площа, рік, документи, гарантії, схеми, контакти підрядника." },
          { icon: "CalendarClock", title: "Планове обслуговування", text: "Котел — раз на рік, вогнегасники — раз на п'ять, кондиціонери — навесні. Система нагадує, а не ви згадуєте." },
          { icon: "Wrench", title: "Заявки на ремонт", text: "«Не працює світло в дитячій» — заявка з фото з телефону. Відповідальний бачить, бере в роботу, закриває." },
          { icon: "Handshake", title: "Підрядники", text: "Електрик, сантехнік, клінінг: контакти, договори, історія робіт і оцінка після кожного виклику." },
          { icon: "Coins", title: "Витрати на утримання", text: "Кожен ремонт і обслуговування — із сумою й категорією. Бухгалтер бачить, у що обходиться будівля за рік." },
          { icon: "AlertTriangle", title: "Терміни та ризики", text: "Прострочене обслуговування, гарантія, що закінчується, повторні поломки — підсвічені на головному екрані." },
        ],
        steps: [
          { title: "Опишіть будівлі та системи", text: "Додайте кожну локацію й ключові системи: опалення, електрика, вода, вентиляція, дах, охорона." },
          { title: "Задайте графік обслуговування", text: "Періодичність, відповідальний, підрядник. Далі система сама створює задачі й нагадує." },
          { title: "Відкрийте заявки команді", text: "Рецепція, лідери й служителі подають заявки на ремонт з телефону — одна черга замість чатів." },
        ],
        audience: [
          { role: "pastor", text: "Бачить стан будівель, відкриті заявки й що треба запланувати до сезону — без обходу з блокнотом." },
          { role: "reception", text: "Подає заявку на ремонт з фото за хвилину й бачить, коли її взяли в роботу." },
          { role: "volunteer", text: "Технічна команда отримує заявки в Telegram, бере в роботу й закриває з коментарем." },
          { role: "accountant", text: "Бачить витрати на утримання по будівлях і системах — із документами від підрядників." },
        ],
        faq: [
          { q: "Чим інфраструктура відрізняється від інвентаризації?", a: "Інвентаризація — це речі, які беруть і повертають: мікрофони, проєктори, намети. Інфраструктура — те, що стоїть на місці й потребує обслуговування: будівля, котел, електрика, дах." },
          { q: "Хто може подати заявку на ремонт?", a: "Будь-хто з команди — з вебу або через Telegram-бот. Ви задаєте, хто бачить чергу заявок і хто призначає виконавця." },
          { q: "Чи можна зберігати документи: договори, акти, схеми?", a: "Так. Кожен об'єкт має свої файли: технічний паспорт, гарантії, договори з підрядниками, акти виконаних робіт." },
          { q: "У нас орендоване приміщення. Модуль потрібен?", a: "Так — щоб знати, за що відповідає орендодавець, а за що церква, і мати історію всіх поломок на випадок суперечок." },
        ],
        mock: {
          kind: "timeline",
          title: "Обслуговування · Центр",
          subtitle: "Будівля на вул. Соборній · 4 системи",
          items: [
            { time: "12 вер", title: "Перевірка котла", who: "Василь Панченко", done: true },
            { time: "19 вер", title: "Заміна ламп у залі", who: "Технічна команда", done: true },
            { time: "26 вер", title: "Чистка вентиляції", who: "ТОВ «Клімат»", done: false },
            { time: "3 жов", title: "Повірка вогнегасників", who: "Підрядник", done: false },
            { time: "10 жов", title: "Огляд даху перед зимою", who: "Андрій Мельник", done: false },
          ],
        },
      },
      en: {
        seoTitle: "Infrastructure — MyChurch module",
        seoDescription: "Asset records for every church building and system: boiler, wiring, ventilation, roof. Maintenance schedule, repair requests, contractors and costs together.",
        title: "No more surprise breakdowns in your building",
        lead: "The Infrastructure module keeps a record for every building and system: when the boiler was last serviced, who looks after the wiring, what the roof repair cost. Repair requests come in from phones, and planned maintenance reminds you about itself.",
        highlights: [
          "A record for every building and system",
          "Maintenance schedule with reminders",
          "Repair requests from a phone",
          "Contractors, documents and costs side by side",
        ],
        features: [
          { icon: "Building2", title: "Asset record", text: "Building, room, system: floor area, year, documents, warranties, drawings, contractor contacts." },
          { icon: "CalendarClock", title: "Planned maintenance", text: "Boiler once a year, extinguishers every five, air conditioning in spring. The system reminds you — you don't have to remember." },
          { icon: "Wrench", title: "Repair requests", text: "\"The lights in the kids' room don't work\" — a request with a photo from a phone. The owner sees it, takes it on, closes it." },
          { icon: "Handshake", title: "Contractors", text: "Electrician, plumber, cleaning: contacts, contracts, work history and a rating after every call-out." },
          { icon: "Coins", title: "Upkeep costs", text: "Every repair and service comes with an amount and a category. The accountant sees what the building costs per year." },
          { icon: "AlertTriangle", title: "Deadlines and risks", text: "Overdue maintenance, an expiring warranty, repeat breakdowns — highlighted on the main screen." },
        ],
        steps: [
          { title: "Describe buildings and systems", text: "Add each location and its key systems: heating, wiring, water, ventilation, roof, security." },
          { title: "Set the maintenance schedule", text: "Frequency, owner, contractor. From then on the system creates tasks and reminds you itself." },
          { title: "Open requests to the team", text: "Reception, leaders and volunteers submit repair requests from their phones — one queue instead of chats." },
        ],
        audience: [
          { role: "pastor", text: "Sees the state of the buildings, open requests and what needs planning before the season — without walking round with a notebook." },
          { role: "reception", text: "Submits a repair request with a photo in a minute and sees when it's been picked up." },
          { role: "volunteer", text: "The tech team gets requests in Telegram, takes them on and closes them with a comment." },
          { role: "accountant", text: "Sees upkeep costs by building and system — with the contractors' documents attached." },
        ],
        faq: [
          { q: "How is infrastructure different from inventory?", a: "Inventory is things people take and bring back: microphones, projectors, tents. Infrastructure is what stays put and needs servicing: the building, boiler, wiring, roof." },
          { q: "Who can submit a repair request?", a: "Anyone on the team — from the web or through the Telegram bot. You decide who sees the queue and who assigns the work." },
          { q: "Can we store documents: contracts, certificates, drawings?", a: "Yes. Every asset has its own files: technical passport, warranties, contractor agreements, completion certificates." },
          { q: "We rent our premises. Do we need this module?", a: "Yes — to know what the landlord is responsible for and what the church is, and to have a history of every fault in case of a dispute." },
        ],
        mock: {
          kind: "timeline",
          title: "Maintenance · Centre",
          subtitle: "Building on Soborna St · 4 systems",
          items: [
            { time: "12 Sep", title: "Boiler inspection", who: "Vasyl Panchenko", done: true },
            { time: "19 Sep", title: "Hall lighting replaced", who: "Tech team", done: true },
            { time: "26 Sep", title: "Ventilation cleaning", who: "Klimat Ltd", done: false },
            { time: "3 Oct", title: "Fire extinguisher check", who: "Contractor", done: false },
            { time: "10 Oct", title: "Roof check before winter", who: "Andrii Melnyk", done: false },
          ],
        },
      },
    },
  },
];
