import type { ModuleDetail } from "./types";

/* Module pages: forms, applications, links, automations, campaigns, knowledge, tables, projects — their catalogue group is the `group` field below. */
export const toolsModules: ModuleDetail[] = [
  {
    id: "forms",
    group: "outreach",
    related: ["people", "onboarding", "events", "automations"],
    copy: {
      ua: {
        seoTitle: "Форми — модуль «Моя Церква»",
        seoDescription: "Анкети, реєстрації та опитування замість Google Форм: відповіді одразу потрапляють у картку людини, а не в окрему таблицю, яку потім треба зводити вручну.",
        title: "Анкети, які самі потрапляють у базу",
        lead: "Модуль «Форми» замінює Google Форми й паперові анкети. Реєстрація на подію, анкета новенького, опитування після курсу — відповіді одразу стають картками людей, а не рядками в чужій таблиці.",
        highlights: [
          "Конструктор без коду: поля, умови, логіка",
          "Відповідь створює або оновлює картку людини",
          "QR-код і коротке посилання для кожної форми",
          "Свої поля працюють у фільтрах і звітах",
        ],
        features: [
          { icon: "ClipboardList", title: "Конструктор форм", text: "Текст, дата, список, чекбокс, файл — перетягніть поля, додайте умови й опублікуйте за п'ять хвилин." },
          { icon: "UserPlus", title: "Одразу в картку людини", text: "Заповнив анкету новенький — з'явилась картка зі статусом «гість». Відповів член церкви — картка оновилась, без дублікатів." },
          { icon: "GitBranch", title: "Умовна логіка", text: "Обрав «з дітьми» — з'явились поля про дітей. Обрав «потрібне таксі» — питання про адресу. Форма підлаштовується під відповідь." },
          { icon: "QrCode", title: "QR і посилання", text: "Кожна форма отримує QR-код для екрана в залі та коротке посилання для чату — надрукували, повісили, працює." },
          { icon: "Zap", title: "Дія після відповіді", text: "Привітання в Telegram, задача відповідальному, додавання в групу чи подію — автоматично, одразу після заповнення." },
          { icon: "Lock", title: "Доступ і приватність", text: "Хто бачить відповіді, вирішуєте ви: молитовну потребу читає лише пастор, реєстрацію на табір — команда табору." },
        ],
        steps: [
          { title: "Створіть форму", text: "Оберіть готовий шаблон — анкета гостя, реєстрація, опитування — або зберіть свою з нуля." },
          { title: "Поділіться", text: "Повісьте QR-код на вході, вставте посилання в оголошення чи в бот церкви." },
          { title: "Отримуйте відповіді в базі", text: "Кожна відповідь — нова або оновлена картка, з якою вже можна працювати: дзвонити, додавати в групу, планувати." },
        ],
        audience: [
          { role: "pastor", text: "Бачить, скільки людей заповнили анкету гостя цього місяця і кому ще ніхто не подзвонив." },
          { role: "reception", text: "Реєструє гостя з планшета за 30 секунд або просто показує QR-код на вході." },
          { role: "volunteer", text: "Збирає заявки на табір чи виїзд без окремої таблиці й переписки в чатах." },
          { role: "visitor", text: "Залишає контакт із телефона за пів хвилини — і його вже не загублять." },
        ],
        faq: [
          { q: "Ми вже маємо Google Форми. Навіщо міняти?", a: "Google Форма складає відповіді в таблицю, яку хтось потім зводить із базою вручну. У «Моїй Церкві» відповідь одразу створює або оновлює картку людини — і з нею можна працювати: дзвонити, додавати в групу, запускати сценарій." },
          { q: "Чи можна заповнити форму без реєстрації в системі?", a: "Так. Публічні форми відкриваються за посиланням або QR-кодом, людина вводить лише те, що ви запитали. Система сама знайде наявну картку за телефоном чи поштою і не створить дублікат." },
          { q: "Чи є вкладення файлів і оплата?", a: "Файли — так: довідки, фото, документи для табору. Оплату приймають модулі «Організатор подій» і «Табори», а форма передає туди дані учасника." },
          { q: "Що робити з паперовими анкетами, які вже є?", a: "Рецепція вносить їх через ту саму форму з планшета — поля ті самі, а картка з'являється в базі одразу." },
        ],
        mock: {
          kind: "form",
          title: "Анкета гостя",
          subtitle: "Перший візит · QR на вході",
          fields: [
            { label: "Ім'я та прізвище", value: "Марія Іщенко", type: "text" },
            { label: "Телефон", value: "+380 67 123 45 67", type: "text" },
            { label: "Як дізнались про церкву", value: "Запросила подруга", type: "select" },
            { label: "Хочу в малу групу", value: "Так, на Виноградарі", type: "check" },
            { label: "Молитовна потреба", value: "Про нову роботу", type: "textarea" },
          ],
          submit: "Надіслати",
        },
        pipeline: {
          title: "Шлях однієї відповіді",
          text: "Приклад: анкета гостя з QR-коду на вході. Що відбувається від натискання «Надіслати» до першого дзвінка.",
          stages: [
            { title: "Заповнення", tone: "neutral", text: "Гість сканує QR на вході й відповідає на п'ять питань зі свого телефона.", auto: "Показує лише ті поля, які відповідають попереднім відповідям." },
            { title: "Звірка з базою", tone: "brand", text: "Система шукає картку за телефоном і поштою.", auto: "Знайшла — оновлює наявну картку. Не знайшла — створює нову зі статусом «гість»." },
            { title: "Дії після відповіді", tone: "violet", text: "Форма запускає те, що ви налаштували для неї.", auto: "Надсилає привітання в Telegram і ставить тег «анкета гостя»." },
            { title: "Відповідальний", tone: "amber", text: "Картка потрапляє до лідера групи в районі, який вказав гість.", auto: "Ставить задачу «подзвонити до вівторка» й нагадує, якщо дзвінка не було." },
            { title: "У базі", tone: "green", text: "Відповіді стали полями картки: район, діти, молитовна потреба.", auto: "Ці поля одразу працюють у фільтрах, розсилках і звітах." },
          ],
        },
      },
      en: {
        seoTitle: "Forms — My Church module",
        seoDescription: "Sign-ups, surveys and newcomer cards instead of Google Forms: every answer lands in a person's profile, not in a spreadsheet you reconcile by hand.",
        title: "Forms that land straight in your database",
        lead: "The Forms module replaces Google Forms and paper cards. Event sign-ups, newcomer cards, post-course surveys — every answer becomes a person's profile, not a row in someone else's spreadsheet.",
        highlights: [
          "No-code builder: fields, conditions, logic",
          "An answer creates or updates a profile",
          "A QR code and short link for every form",
          "Custom fields work in filters and reports",
        ],
        features: [
          { icon: "ClipboardList", title: "Form builder", text: "Text, date, list, checkbox, file — drag fields in, add conditions and publish in five minutes." },
          { icon: "UserPlus", title: "Straight into the profile", text: "A newcomer fills in the card — a profile appears with the status \"guest\". A member answers — their profile is updated, no duplicates." },
          { icon: "GitBranch", title: "Conditional logic", text: "Ticked \"with children\" — child fields appear. Chose \"need a lift\" — an address question follows. The form adapts to the answer." },
          { icon: "QrCode", title: "QR and links", text: "Every form gets a QR code for the screen in the hall and a short link for the chat — print it, hang it, it works." },
          { icon: "Zap", title: "Action after submission", text: "A Telegram greeting, a task for the owner, adding to a group or event — automatically, the moment the form is submitted." },
          { icon: "Lock", title: "Access and privacy", text: "You decide who sees the answers: prayer requests go to the pastor only, camp sign-ups to the camp team." },
        ],
        steps: [
          { title: "Create a form", text: "Pick a ready-made template — newcomer card, sign-up, survey — or build your own from scratch." },
          { title: "Share it", text: "Put the QR code at the door, drop the link into an announcement or the church bot." },
          { title: "Get answers in the database", text: "Every answer is a new or updated profile you can act on straight away: call, add to a group, plan." },
        ],
        audience: [
          { role: "pastor", text: "Sees how many people filled in the newcomer card this month and who hasn't been called yet." },
          { role: "reception", text: "Registers a guest on a tablet in 30 seconds or simply shows the QR code at the door." },
          { role: "volunteer", text: "Collects camp or trip sign-ups without a separate spreadsheet or chat threads." },
          { role: "visitor", text: "Leaves their contact from a phone in half a minute — and won't get lost." },
        ],
        faq: [
          { q: "We already use Google Forms. Why switch?", a: "A Google Form drops answers into a spreadsheet that someone later reconciles with the database by hand. In My Church an answer creates or updates a person's profile straight away — and you can act on it: call, add to a group, run a scenario." },
          { q: "Can someone fill in a form without an account?", a: "Yes. Public forms open from a link or QR code and the person enters only what you asked. The system matches an existing profile by phone or email, so no duplicates are created." },
          { q: "Are file uploads and payments supported?", a: "Files, yes: certificates, photos, camp documents. Payments are handled by the Event organiser and Camps modules — the form passes the participant's details across." },
          { q: "What about the paper cards we already have?", a: "Reception enters them through the same form on a tablet — same fields, and the profile appears in the database straight away." },
        ],
        mock: {
          kind: "form",
          title: "Newcomer card",
          subtitle: "First visit · QR at the door",
          fields: [
            { label: "Full name", value: "Maria Ishchenko", type: "text" },
            { label: "Phone", value: "+380 67 123 45 67", type: "text" },
            { label: "How did you hear about us", value: "A friend invited me", type: "select" },
            { label: "I'd like to join a small group", value: "Yes, in Obolon", type: "check" },
            { label: "Prayer request", value: "A new job", type: "textarea" },
          ],
          submit: "Send",
        },
        pipeline: {
          title: "The path of a single answer",
          text: "Example: a newcomer card from the QR code at the door. What happens between \"Send\" and the first phone call.",
          stages: [
            { title: "Filling it in", tone: "neutral", text: "The guest scans the QR at the door and answers five questions on their own phone.", auto: "Shows only the fields that match the earlier answers." },
            { title: "Matching the database", tone: "brand", text: "The system looks for a profile by phone and email.", auto: "Found one — updates it. Found none — creates a new profile with the status \"guest\"." },
            { title: "Actions after the answer", tone: "violet", text: "The form runs whatever you set up for it.", auto: "Sends a Telegram greeting and adds the tag \"newcomer card\"." },
            { title: "Owner", tone: "amber", text: "The profile goes to the group leader for the district the guest named.", auto: "Creates the task \"call by Tuesday\" and reminds them if no call happened." },
            { title: "In the database", tone: "green", text: "The answers are now profile fields: district, children, prayer request.", auto: "Those fields work in filters, campaigns and reports straight away." },
          ],
        },
      },
    },
  },
  {
    id: "applications",
    group: "outreach",
    related: ["forms", "telegram-bot", "automations", "people"],
    copy: {
      ua: {
        seoTitle: "Заявки — модуль «Моя Церква»",
        seoDescription: "Молитва, зустріч із пастором, хрещення, допомога, бажання служити — усі звернення людей з форм, бота й сайту на одній канбан-дошці з відповідальним і терміном.",
        title: "Жодна заявка не зависає без відповіді",
        lead: "Модуль «Заявки» збирає все, що люди просять у церкви — молитву, зустріч, хрещення, допомогу, бажання служити — з форм, Telegram-бота, сайту та Instagram в одну канбан-дошку. Кожна картка має відповідального, етап і термін, а людина отримує відповідь із самої картки.",
        highlights: [
          "Одна дошка для звернень з усіх каналів",
          "Канбан: Нова → У роботі → Очікує → Закрита",
          "Відповідальний і термін на кожній картці",
          "Без руху 3 дні — нагадування відповідальному",
        ],
        features: [
          { icon: "Inbox", title: "Усі канали — одна черга", text: "Форма на сайті, кнопка в боті, Direct в Instagram, дзвінок на рецепцію — усе стає карткою на дошці з позначкою, звідки прийшло." },
          { icon: "Kanban", title: "Канбан-дошка", text: "Стовпці — етапи шляху. Перетягнули картку — етап змінився, людина отримала статус, відповідальний — нагадування." },
          { icon: "Route", title: "Свій шлях для кожного типу", text: "У «Хрещення» — співбесіда, курс, дата. У «Молитви» — молилися, відповіли. Кожен тип заявки має власні стовпці й відповідального за замовчуванням." },
          { icon: "UserCheck", title: "Відповідальний і термін", text: "Заявка на зустріч із пастором потрапляє до помічника пастора з терміном 2 дні. Прострочені — червоні зверху дошки." },
          { icon: "MessageCircle", title: "Відповідь із картки", text: "Пишете людині прямо з картки — вона отримує повідомлення в Telegram чи SMS. Листування зберігається в історії заявки й у картці людини." },
          { icon: "BarChart3", title: "Аналітика звернень", text: "Скільки заявок за місяць, яких типів, скільки часу до першої відповіді, хто закриває найшвидше. Видно, де черга росте." },
        ],
        steps: [
          { title: "Увімкніть типи заявок", text: "Молитва, зустріч, хрещення, вінчання, допомога, служіння — готові типи з власним шляхом; додайте свої за хвилину." },
          { title: "Підключіть джерела", text: "Форма на сайті, кнопка «Написати» у Telegram-боті, Instagram Direct — усе вже вміє створювати картки." },
          { title: "Призначте відповідальних", text: "Хто бере молитовні, хто — зустрічі, хто — допомогу. Термін відповіді для кожного типу." },
          { title: "Ведіть картки по дошці", text: "Взяли — у роботі. Домовились — очікує. Зробили — закрито. Людина отримує відповідь на кожному кроці." },
        ],
        audience: [
          { role: "pastor", text: "Бачить усі заявки на зустріч і молитву в одному місці й знає, кому вже відповіли, а хто чекає третій день." },
          { role: "leader", text: "Отримує заявки на свою групу чи служіння, веде їх по дошці й не тримає список у нотатках телефону." },
          { role: "reception", text: "Заносить дзвінок або прохання з фойє як картку за 20 секунд — і воно не губиться до понеділка." },
          { role: "visitor", text: "Пише в бот «хочу зустрітися з пастором» і за кілька хвилин отримує відповідь, хто і коли з ним зв'яжеться." },
        ],
        faq: [
          { q: "Чим «Заявки» відрізняються від «Запитів» у HR?", a: "«Запити» — внутрішні: відпустки, заміни, кошти для команди. «Заявки» — звернення людей до церкви: молитва, зустріч, хрещення, допомога. Різні дошки, різні відповідальні." },
          { q: "Чи бачить людина, на якому етапі її заявка?", a: "Так, якщо ви цього хочете. На кожному переході картка може надсилати повідомлення: «Ваша заявка взята в роботу, з вами зв'яжеться Андрій до середи»." },
          { q: "Що з конфіденційними зверненнями?", a: "Тип заявки має список тих, хто її бачить. Молитовні потреби або прохання про допомогу може бачити лише пастор і призначений служитель — решта не бачить навіть заголовка." },
          { q: "Чи можна зробити свої стовпці?", a: "Так. Для кожного типу — свій набір етапів. Наприклад, для хрещення: Нова → Співбесіда → Курс → Дата призначена → Охрещений." },
        ],
        mock: {
          kind: "board",
          title: "Заявки",
          subtitle: "Цього тижня: 23 нові · 4 прострочені",
          columns: [
            {
              title: "Нові",
              cards: [
                { title: "Зустріч із пастором", sub: "Оксана Гриценко · з бота", tag: { label: "Зустріч", tone: "brand" } },
                { title: "Молитва за маму", sub: "Ігор Лисенко · з сайту", tag: { label: "Молитва", tone: "violet" } },
                { title: "Хочу служити на звуці", sub: "Тарас Бойко · Instagram", tag: { label: "Служіння", tone: "amber" } },
              ],
            },
            {
              title: "У роботі",
              cards: [
                { title: "Хрещення", sub: "Марія Іщенко · Андрій М. · до пт", tag: { label: "Хрещення", tone: "brand" } },
                { title: "Допомога з продуктами", sub: "Родина Коваль · Наталя Р. · сьогодні", tag: { label: "Допомога", tone: "red" } },
              ],
            },
            {
              title: "Закриті",
              cards: [
                { title: "Вінчання 14 листопада", sub: "Дмитро та Олена", tag: { label: "Готово", tone: "green" } },
                { title: "Молитва за здоров'я", sub: "Ольга Сич · відповіли", tag: { label: "Готово", tone: "green" } },
              ],
            },
          ],
        },
        pipeline: {
          title: "Шлях заявки по дошці",
          text: "Приклад для типу «Зустріч із пастором». Кожен стовпець — етап; перетягування картки запускає дії справа.",
          stages: [
            { title: "Нова", tone: "neutral", text: "Людина написала в бот, заповнила форму або зателефонувала на рецепцію. Картка з'являється на дошці з джерелом і контактом.", auto: "Відповідає людині «отримали, зв'яжемось до середи» і призначає відповідального за типом." },
            { title: "У роботі", tone: "brand", text: "Помічник пастора взяв картку: подзвонив, уточнив тему, запропонував час.", auto: "Ставить термін 2 дні. Без руху — нагадування відповідальному, потім пастору." },
            { title: "Очікує", tone: "amber", text: "Зустріч призначена, чекаємо дати. Або чекаємо відповіді від людини.", auto: "Створює подію в календарі пастора і надсилає людині нагадування за день." },
            { title: "Закрита", tone: "green", text: "Зустріч відбулась. Пастор дописав короткий підсумок — він лишається в картці людини.", auto: "Питає людину «чи допомогли?» через тиждень і закриває картку з оцінкою." },
          ],
        },
      },
      en: {
        seoTitle: "Requests — My Church module",
        seoDescription: "Prayer, a meeting with the pastor, baptism, help, wanting to serve — every request from people via forms, bot and website on one kanban board with an owner and a deadline.",
        title: "No request is left hanging without a reply",
        lead: "The Requests module gathers everything people ask of the church — prayer, a meeting, baptism, help, wanting to serve — from forms, the Telegram bot, the website and Instagram into one kanban board. Every card has an owner, a stage and a deadline, and the person gets a reply straight from the card.",
        highlights: [
          "One board for requests from every channel",
          "Kanban: New → In progress → Waiting → Closed",
          "An owner and a deadline on every card",
          "No movement for 3 days — the owner gets a reminder",
        ],
        features: [
          { icon: "Inbox", title: "Every channel, one queue", text: "A website form, a bot button, an Instagram DM, a call to reception — everything becomes a card on the board, tagged with where it came from." },
          { icon: "Kanban", title: "Kanban board", text: "Columns are stages of the path. Drag a card — the stage changes, the person gets a status, the owner gets a reminder." },
          { icon: "Route", title: "A path per request type", text: "Baptism has an interview, a course and a date. Prayer has prayed and replied. Each request type has its own columns and default owner." },
          { icon: "UserCheck", title: "Owner and deadline", text: "A request to meet the pastor lands with the pastor's assistant with a 2-day deadline. Overdue cards turn red at the top of the board." },
          { icon: "MessageCircle", title: "Reply from the card", text: "Write to the person right from the card — they get it in Telegram or by SMS. The conversation stays in the request history and the person's profile." },
          { icon: "BarChart3", title: "Request analytics", text: "How many requests a month, of which types, time to first reply, who closes fastest. You can see where the queue is growing." },
        ],
        steps: [
          { title: "Switch on request types", text: "Prayer, meeting, baptism, wedding, help, serving — ready-made types with their own path; add your own in a minute." },
          { title: "Connect the sources", text: "A website form, a \"Write to us\" button in the Telegram bot, Instagram DMs — all of them already create cards." },
          { title: "Assign owners", text: "Who takes prayer requests, who takes meetings, who takes help. A reply deadline for each type." },
          { title: "Move cards along the board", text: "Picked up — in progress. Agreed — waiting. Done — closed. The person gets a reply at every step." },
        ],
        audience: [
          { role: "pastor", text: "Sees every meeting and prayer request in one place and knows who has been answered and who has been waiting three days." },
          { role: "leader", text: "Gets requests for their group or ministry, moves them along the board and stops keeping a list in phone notes." },
          { role: "reception", text: "Logs a call or a request from the lobby as a card in 20 seconds — and it doesn't get lost by Monday." },
          { role: "visitor", text: "Writes \"I'd like to meet the pastor\" to the bot and within minutes hears who will get in touch and when." },
        ],
        faq: [
          { q: "How are Requests different from Staff requests in HR?", a: "Staff requests are internal: time off, cover, funds for the team. Requests are what people ask of the church: prayer, a meeting, baptism, help. Different boards, different owners." },
          { q: "Can the person see which stage their request is at?", a: "Yes, if you want. On every transition the card can send a message: \"Your request has been picked up, Andrii will contact you by Wednesday\"." },
          { q: "What about confidential requests?", a: "Each request type has a list of who can see it. Prayer needs or requests for help can be visible only to the pastor and the assigned minister — nobody else sees even the title." },
          { q: "Can we make our own columns?", a: "Yes. Each type has its own set of stages. For baptism, for example: New → Interview → Course → Date set → Baptised." },
        ],
        mock: {
          kind: "board",
          title: "Requests",
          subtitle: "This week: 23 new · 4 overdue",
          columns: [
            {
              title: "New",
              cards: [
                { title: "Meet the pastor", sub: "Oksana Hrytsenko · from bot", tag: { label: "Meeting", tone: "brand" } },
                { title: "Prayer for my mum", sub: "Ihor Lysenko · from website", tag: { label: "Prayer", tone: "violet" } },
                { title: "Want to serve on sound", sub: "Taras Boiko · Instagram", tag: { label: "Serving", tone: "amber" } },
              ],
            },
            {
              title: "In progress",
              cards: [
                { title: "Baptism", sub: "Maria Ishchenko · Andrii M. · by Fri", tag: { label: "Baptism", tone: "brand" } },
                { title: "Help with groceries", sub: "Koval family · Natalia R. · today", tag: { label: "Help", tone: "red" } },
              ],
            },
            {
              title: "Closed",
              cards: [
                { title: "Wedding, 14 November", sub: "Dmytro and Olena", tag: { label: "Done", tone: "green" } },
                { title: "Prayer for health", sub: "Olha Sych · replied", tag: { label: "Done", tone: "green" } },
              ],
            },
          ],
        },
        pipeline: {
          title: "A request's path across the board",
          text: "Example for the \"Meet the pastor\" type. Each column is a stage; dragging a card triggers the actions on the right.",
          stages: [
            { title: "New", tone: "neutral", text: "The person wrote to the bot, filled in a form or called reception. The card appears on the board with its source and contact.", auto: "Replies \"received, we'll be in touch by Wednesday\" and assigns the owner for that type." },
            { title: "In progress", tone: "brand", text: "The pastor's assistant picked up the card: called, clarified the topic, offered a time.", auto: "Sets a 2-day deadline. No movement — a reminder to the owner, then to the pastor." },
            { title: "Waiting", tone: "amber", text: "The meeting is booked and we're waiting for the date. Or waiting for the person to reply.", auto: "Creates an event in the pastor's calendar and reminds the person the day before." },
            { title: "Closed", tone: "green", text: "The meeting happened. The pastor added a short summary — it stays in the person's profile.", auto: "Asks the person \"did it help?\" a week later and closes the card with a rating." },
          ],
        },
      },
    },
  },
  {
    id: "links",
    group: "outreach",
    related: ["forms", "events", "campaigns", "telegram-bot"],
    copy: {
      ua: {
        seoTitle: "Посилання — модуль «Моя Церква»",
        seoDescription: "Короткі посилання та QR-коди для подій, форм і реєстрацій замість Bitly: адреси з назвою церкви, статистика переходів і QR, який можна змінити після друку.",
        title: "Коротке посилання, яке приводить людей у базу",
        lead: "Модуль «Посилання» замінює Bitly та генератори QR-кодів. Коротка адреса церкви на екрані, в оголошенні чи на флаєрі — і ви бачите, скільки людей перейшло, звідки і що зробили далі.",
        highlights: [
          "Короткі адреси з назвою вашої церкви",
          "QR-код, який змінюється без передруку",
          "Переходи й скани в реальному часі",
          "Посилання на форму, подію чи бот — за один клік",
        ],
        features: [
          { icon: "Link2", title: "Короткі посилання", text: "Довга адреса форми чи події перетворюється на коротку й зрозумілу: /альфа, /табір, /неділя. Її можна продиктувати з кафедри." },
          { icon: "QrCode", title: "Живі QR-коди", text: "Надрукували банер із QR на рік — а куди він веде, змінюєте в системі: сьогодні на реєстрацію, завтра на розклад." },
          { icon: "BarChart3", title: "Статистика переходів", text: "Скільки перейшли, з якого каналу, у який день і що зробили далі — заповнили форму чи пішли. Видно, які оголошення працюють." },
          { icon: "Share2", title: "Для кожного каналу окремо", text: "Одна подія — різні посилання для Instagram, Telegram, екрана в залі та флаєра. Порівнюйте, звідки приходять люди." },
          { icon: "Printer", title: "Друк без дизайнера", text: "QR із логотипом церкви, підписом і потрібним розміром — для афіші, слайда чи візитки, одразу у PDF або PNG." },
          { icon: "Clock", title: "Термін дії", text: "Посилання на реєстрацію закривається, коли місця закінчились або минув дедлайн, і показує, куди йти далі." },
        ],
        steps: [
          { title: "Вставте адресу", text: "Форма, подія, сторінка бота чи будь-який зовнішній сайт — система дає коротке посилання та QR." },
          { title: "Розмістіть", text: "Слайд у залі, пост в Instagram, флаєр, оголошення в Telegram — на кожне місце своє посилання." },
          { title: "Дивіться, що працює", text: "Переходи по днях і каналах поруч із відповідями форм — і зрозуміло, які оголошення дають результат." },
        ],
        audience: [
          { role: "pastor", text: "Називає з кафедри одну коротку адресу й у понеділок бачить, скільки людей за нею перейшли." },
          { role: "leader", text: "Ділиться посиланням на реєстрацію в чаті групи й бачить, хто з групи вже записався." },
          { role: "volunteer", text: "Друкує QR для афіші та стійки на вході — без дизайнера й окремих сервісів." },
          { role: "reception", text: "Показує гостю QR на стійці — анкета заповнюється з його телефона, без черги." },
        ],
        faq: [
          { q: "Чим це краще за Bitly чи QR-генератор?", a: "Посилання живе поруч із формою, подією та людьми: ви бачите не лише кількість переходів, а й хто в підсумку зареєструвався. І QR можна перенаправити після друку — статичний код зі стороннього генератора після друку вже не змінити." },
          { q: "Що буде з QR-кодом на банері, якщо подія минула?", a: "Перенаправте його на наступну подію або на розклад церкви — банер лишається робочим, передруковувати не треба." },
          { q: "Чи можна побачити, хто саме перейшов?", a: "Переходи анонімні. Але якщо людина далі заповнила форму або зареєструвалась, у її картці з'явиться, з якого посилання вона прийшла." },
          { q: "Чи можна давати посилання на зовнішні сайти?", a: "Так — на YouTube-трансляцію, Google Карти чи сайт конференції. Статистика переходів працюватиме так само." },
        ],
        mock: {
          kind: "stats",
          title: "Посилання",
          subtitle: "24 активних · вересень",
          kpis: [
            { label: "Переходів", value: "1 284", trend: "+18%" },
            { label: "QR-сканів", value: "312", trend: "+42" },
            { label: "Реєстрацій", value: "96" },
          ],
          barsTitle: "Переходи за тиждень",
          bars: [
            { label: "/альфа", value: 92 },
            { label: "/табір", value: 74 },
            { label: "/неділя", value: 68 },
            { label: "/молодь", value: 55 },
            { label: "/анкета", value: 47 },
            { label: "/пожертва", value: 31 },
          ],
        },
        pipeline: {
          title: "Шлях короткого посилання",
          text: "Приклад: /табір для літнього табору — від створення посилання до картки в базі.",
          stages: [
            { title: "Створення", tone: "neutral", text: "Вставляєте адресу форми реєстрації й називаєте посилання: /табір.", auto: "Одразу віддає QR-код у PNG і PDF — для афіші, слайда й стійки на вході." },
            { title: "Розміщення", tone: "brand", text: "Окреме посилання для Instagram, Telegram, слайда в залі та флаєра.", auto: "Рахує переходи по кожному каналу окремо, без додаткових налаштувань." },
            { title: "Переходи", tone: "amber", text: "Люди сканують QR зі стійки або тиснуть посилання в оголошенні.", auto: "Записує день, канал і пристрій; лічильник оновлюється в реальному часі." },
            { title: "Реєстрація", tone: "green", text: "Частина тих, хто перейшов, заповнює форму табору до кінця.", auto: "Записує в картку людини, з якого саме посилання вона прийшла." },
            { title: "Після події", tone: "violet", text: "Табір минув, а банер із QR лишився висіти на вході.", auto: "Перенаправляєте посилання на наступну подію — передруковувати не треба." },
          ],
        },
      },
      en: {
        seoTitle: "Links — My Church module",
        seoDescription: "Short links and QR codes for events, forms and sign-ups instead of Bitly: your church's addresses, click statistics and a QR you can redirect after printing.",
        title: "Short links that bring people into your database",
        lead: "The Links module replaces Bitly and QR generators. A short church address on the screen, in an announcement or on a flyer — and you see how many people followed it, from where, and what they did next.",
        highlights: [
          "Short addresses with your church's name",
          "QR codes that change without reprinting",
          "Clicks and scans in real time",
          "Link to a form, event or bot in one click",
        ],
        features: [
          { icon: "Link2", title: "Short links", text: "A long form or event address becomes short and readable: /alpha, /camp, /sunday. You can read it out from the pulpit." },
          { icon: "QrCode", title: "Live QR codes", text: "Print a banner with a QR code for the year — and change where it leads in the system: sign-up today, the schedule tomorrow." },
          { icon: "BarChart3", title: "Click statistics", text: "How many clicked, from which channel, on which day, and what they did next — filled in the form or left. You see which announcements work." },
          { icon: "Share2", title: "One link per channel", text: "One event — separate links for Instagram, Telegram, the hall screen and the flyer. Compare where people come from." },
          { icon: "Printer", title: "Print without a designer", text: "A QR code with the church logo, a caption and the right size — for a poster, slide or card, straight to PDF or PNG." },
          { icon: "Clock", title: "Expiry", text: "A sign-up link closes when places run out or the deadline passes, and tells people where to go next." },
        ],
        steps: [
          { title: "Paste an address", text: "A form, an event, a bot page or any external site — the system gives you a short link and a QR code." },
          { title: "Put it out there", text: "A slide in the hall, an Instagram post, a flyer, a Telegram announcement — a separate link for each place." },
          { title: "See what works", text: "Clicks by day and channel next to form answers — and it's clear which announcements bring results." },
        ],
        audience: [
          { role: "pastor", text: "Reads out one short address from the pulpit and on Monday sees how many people followed it." },
          { role: "leader", text: "Shares the sign-up link in the group chat and sees who from the group has already registered." },
          { role: "volunteer", text: "Prints a QR code for the poster and the welcome desk — no designer, no extra services." },
          { role: "reception", text: "Shows a guest the QR code at the desk — the card is filled in from their own phone, no queue." },
        ],
        faq: [
          { q: "Why is this better than Bitly or a QR generator?", a: "The link lives next to the form, the event and the people: you see not just clicks but who actually signed up. And a QR code can be redirected after printing — a static code from a third-party generator can't be changed once it's on the banner." },
          { q: "What happens to the QR on a banner once the event is over?", a: "Redirect it to the next event or to the church schedule — the banner keeps working, no reprint needed." },
          { q: "Can I see exactly who clicked?", a: "Clicks are anonymous. But if the person goes on to fill in a form or sign up, their profile records which link they came from." },
          { q: "Can links point to external sites?", a: "Yes — a YouTube stream, Google Maps or a conference website. Click statistics work just the same." },
        ],
        mock: {
          kind: "stats",
          title: "Links",
          subtitle: "24 active · September",
          kpis: [
            { label: "Clicks", value: "1,284", trend: "+18%" },
            { label: "QR scans", value: "312", trend: "+42" },
            { label: "Sign-ups", value: "96" },
          ],
          barsTitle: "Clicks this week",
          bars: [
            { label: "/alpha", value: 92 },
            { label: "/camp", value: 74 },
            { label: "/sunday", value: 68 },
            { label: "/youth", value: 55 },
            { label: "/card", value: 47 },
            { label: "/give", value: 31 },
          ],
        },
        pipeline: {
          title: "The path of a short link",
          text: "Example: /camp for the summer camp — from creating the link to a profile in the database.",
          stages: [
            { title: "Creating", tone: "neutral", text: "You paste the sign-up form address and name the link: /camp.", auto: "Hands back a QR code as PNG and PDF — for the poster, the slide and the welcome desk." },
            { title: "Placing it", tone: "brand", text: "A separate link for Instagram, Telegram, the hall slide and the flyer.", auto: "Counts clicks per channel separately, with nothing else to set up." },
            { title: "Clicks", tone: "amber", text: "People scan the QR at the desk or tap the link in an announcement.", auto: "Records the day, channel and device; the counter updates in real time." },
            { title: "Sign-up", tone: "green", text: "Some of those who clicked finish the camp form.", auto: "Records in the person's profile which link they arrived from." },
            { title: "After the event", tone: "violet", text: "The camp is over, but the QR banner is still hanging at the door.", auto: "You redirect the link to the next event — no reprinting needed." },
          ],
        },
      },
    },
  },
  {
    id: "automations",
    group: "platform",
    related: ["onboarding", "campaigns", "people", "telegram-bot"],
    copy: {
      ua: {
        seoTitle: "Автоматизації — модуль «Моя Церква»",
        seoDescription: "Сценарії «якщо — то» для церкви: привітання новенького, нагадування лідеру, зміна статусу, задача відповідальному — система робить це сама, без Zapier і чатів.",
        title: "Сценарії, які не дають загубити людину",
        lead: "Модуль «Автоматизації» — це правила «якщо — то» на даних вашої церкви. Новенький заповнив анкету → привітання в Telegram і задача лідеру. Людина пропустила три неділі → пастор бачить її у списку. Без Zapier і без нагадувань самому собі.",
        highlights: [
          "Тригери: анкета, явка, дата, статус, подія",
          "Дії: повідомлення, задача, тег, статус, група",
          "Готові сценарії для новеньких і відсутніх",
          "Журнал кожного запуску — видно, що і кому пішло",
        ],
        features: [
          { icon: "Workflow", title: "Конструктор сценаріїв", text: "Тригер, умови, дії — складаєте ланцюжок мишкою. «Якщо новенький і без групи через 7 днів — задача лідеру найближчої групи»." },
          { icon: "Bell", title: "Нагадування, які не губляться", text: "Лідеру — про людину, що пропускає. Служителю — за день до служіння. Пастору — про день народження члена церкви." },
          { icon: "MessageCircle", title: "Повідомлення в потрібний канал", text: "Telegram, Viber, SMS чи пошта — сценарій пише туди, де людина справді читає, і від імені церкви, а не робота." },
          { icon: "Tags", title: "Статуси й теги оновлюються самі", text: "Пройшов Альфа-курс — тег «Альфа». Три місяці в групі та курс завершено — статус «член церкви». Ручної роботи нуль." },
          { icon: "Timer", title: "Затримки й розклад", text: "«Через 2 дні», «в суботу о 10:00», «за тиждень до події» — сценарій чекає стільки, скільки потрібно, і не забуває." },
          { icon: "History", title: "Журнал запусків", text: "Кожен запуск записано: що спрацювало, кому пішло повідомлення, де сценарій зупинився. Помилку видно одразу." },
        ],
        steps: [
          { title: "Увімкніть готовий сценарій", text: "«Привітати новенького», «Хто зник на 3 тижні», «День народження» — увімкніть і підставте свої тексти." },
          { title: "Опишіть свої правила", text: "Тригер, умова, дія — те, що ви й так робите щотижня вручну, тепер описане один раз." },
          { title: "Перевірте на одній людині", text: "Тестовий запуск показує кожен крок до того, як сценарій піде по всій базі." },
          { title: "Дивіться журнал", text: "Що спрацювало, кому пішло, де зупинилось — і підправляйте сценарій, а не людей." },
        ],
        audience: [
          { role: "pastor", text: "Отримує список тих, хто зникає, у понеділок зранку — без запиту до адміністратора." },
          { role: "leader", text: "Дізнається про новенького у своєму районі того ж дня і має задачу подзвонити." },
          { role: "volunteer", text: "Отримує нагадування про служіння за день і за годину — без чатів і дзвінків лідера." },
          { role: "visitor", text: "Отримує привітання від церкви в день першого візиту й запрошення на наступний крок." },
        ],
        faq: [
          { q: "Чим це відрізняється від Zapier чи Make?", a: "Сценарії працюють на ваших даних — людях, групах, явці, подіях — і не потребують сторонніх підключень. Тригер «пропустив три неділі» просто є, його не треба будувати з веб-хуків." },
          { q: "А якщо сценарій напише не тій людині?", a: "Перед увімкненням є тестовий запуск на одній картці, а кожна дія записується в журнал. Сценарій можна зупинити одним перемикачем." },
          { q: "Чи можна ставити сценарії на свої поля?", a: "Так. Тригером або умовою може бути будь-яке поле картки, зокрема ваші власні: «шукає групу», «хоче служити», «район»." },
          { q: "Хто може створювати сценарії?", a: "Адміністратор церкви. Лідери бачать сценарії своїх груп і можуть вмикати готові, але не змінювати правила для всієї церкви." },
        ],
        benefits: {
          title: "Що реально змінюється за тиждень",
          text: "Приклад: церква на 200 людей, п'ять увімкнених готових сценаріїв. Порівнюємо з тим, як це робиться руками — у чатах і нотатках.",
          items: [
            { value: "6 год", label: "на тиждень повертається адміністратору", text: "Нагадування служителям, привітання новеньких, зміна статусів і задачі лідерам більше не робляться вручну." },
            { value: "100%", label: "новеньких отримують привітання й відповідального", text: "У той самий день, без винятків і без «забув переслати лідеру». Раніше — приблизно кожен третій." },
            { value: "1 день", label: "щоб помітити, що людина зникає", text: "Замість трьох тижнів, коли хтось випадково згадує «а де Ігор?». Лідер має задачу вже в понеділок." },
            { value: "0", label: "повідомлень «не забудь» у чатах", text: "Служителі отримують нагадування напряму від системи — лідер більше не пише кожному окремо." },
          ],
        },
        mock: {
          kind: "timeline",
          title: "Новенький: перший тиждень",
          subtitle: "Спрацював для Дмитра Лиса",
          items: [
            { time: "Нд 12:40", title: "Заповнив анкету гостя", who: "Тригер", done: true },
            { time: "Нд 12:41", title: "Привітання в Telegram", who: "Від імені церкви", done: true },
            { time: "Нд 12:41", title: "Задача: подзвонити", who: "Андрій Мельник", done: true },
            { time: "Ср 10:00", title: "Запрошення в домашню групу", who: "Telegram", done: true },
            { time: "Нд 09:00", title: "Нагадування про служіння", who: "Telegram", done: false },
            { time: "+7 днів", title: "Без групи? → задача лідеру", who: "Умова", done: false },
          ],
        },
      },
      en: {
        seoTitle: "Automations — My Church module",
        seoDescription: "If-this-then-that scenarios for your church: greet a newcomer, remind a leader, change a status, assign a task — done by the system, no Zapier and no chats.",
        title: "Scenarios so nobody slips through the cracks",
        lead: "The Automations module is if-this-then-that rules on your church's data. A newcomer submits a card → a Telegram greeting and a task for the leader. Someone misses three Sundays → the pastor sees them on a list. No Zapier, no notes to self.",
        highlights: [
          "Triggers: form, attendance, date, status, event",
          "Actions: message, task, tag, status, group",
          "Ready-made scenarios for newcomers and absentees",
          "A log of every run — you see what went where",
        ],
        features: [
          { icon: "Workflow", title: "Scenario builder", text: "Trigger, conditions, actions — build the chain with your mouse. \"If newcomer and no group after 7 days — task for the nearest group's leader\"." },
          { icon: "Bell", title: "Reminders that don't get lost", text: "The leader — about a person who's missing meetings. A volunteer — the day before a service. The pastor — about a member's birthday." },
          { icon: "MessageCircle", title: "The right channel", text: "Telegram, Viber, SMS or email — a scenario writes where the person actually reads, and in the church's name, not a robot's." },
          { icon: "Tags", title: "Statuses and tags update themselves", text: "Finished the Alpha course — tag \"Alpha\". Three months in a group and a course completed — status \"member\". Zero manual work." },
          { icon: "Timer", title: "Delays and schedules", text: "\"In 2 days\", \"Saturday at 10:00\", \"a week before the event\" — a scenario waits as long as it needs to and doesn't forget." },
          { icon: "History", title: "Run log", text: "Every run is recorded: what fired, who got a message, where the scenario stopped. Mistakes are visible straight away." },
        ],
        steps: [
          { title: "Switch on a ready-made scenario", text: "\"Greet a newcomer\", \"Missing for 3 weeks\", \"Birthday\" — switch it on and drop in your own wording." },
          { title: "Describe your own rules", text: "Trigger, condition, action — what you already do by hand every week, now written down once." },
          { title: "Test on one person", text: "A test run shows every step before the scenario goes out to the whole database." },
          { title: "Watch the log", text: "What fired, who received it, where it stopped — and tweak the scenario, not the people." },
        ],
        audience: [
          { role: "pastor", text: "Gets the list of people drifting away on Monday morning — without asking the administrator." },
          { role: "leader", text: "Hears about a newcomer in their area the same day and has a task to call." },
          { role: "volunteer", text: "Gets a service reminder a day and an hour ahead — no chats, no calls from the leader." },
          { role: "visitor", text: "Receives a greeting from the church on the day of their first visit and an invitation to the next step." },
        ],
        faq: [
          { q: "How is this different from Zapier or Make?", a: "Scenarios run on your own data — people, groups, attendance, events — with no third-party connections. The trigger \"missed three Sundays\" simply exists; you don't have to build it from webhooks." },
          { q: "What if a scenario messages the wrong person?", a: "Before switching it on there's a test run on a single profile, and every action is written to the log. A scenario can be paused with one toggle." },
          { q: "Can scenarios use my custom fields?", a: "Yes. Any profile field can be a trigger or a condition, including your own: \"looking for a group\", \"wants to serve\", \"district\"." },
          { q: "Who can create scenarios?", a: "The church administrator. Leaders see scenarios for their own groups and can switch on ready-made ones, but can't change rules for the whole church." },
        ],
        benefits: {
          title: "What actually changes in a week",
          text: "Example: a church of 200 people with five ready-made scenarios switched on. Compared with doing it by hand — in chats and notes.",
          items: [
            { value: "6 hrs", label: "a week given back to the administrator", text: "Volunteer reminders, newcomer greetings, status changes and tasks for leaders are no longer done by hand." },
            { value: "100%", label: "of newcomers get a greeting and an owner", text: "The same day, no exceptions and no \"forgot to forward it to the leader\". Before — roughly one in three." },
            { value: "1 day", label: "to notice that someone is drifting away", text: "Instead of three weeks, when somebody happens to ask \"where's Ihor?\". The leader has a task on Monday." },
            { value: "0", label: "\"don't forget\" messages in chats", text: "Volunteers get reminders straight from the system — the leader no longer writes to each one separately." },
          ],
        },
        mock: {
          kind: "timeline",
          title: "Newcomer: first week",
          subtitle: "Ran for Dmytro Lys",
          items: [
            { time: "Sun 12:40", title: "Filled in newcomer card", who: "Trigger", done: true },
            { time: "Sun 12:41", title: "Telegram greeting", who: "From the church", done: true },
            { time: "Sun 12:41", title: "Task: call", who: "Andrii Melnyk", done: true },
            { time: "Wed 10:00", title: "Invite to Obolon group", who: "Telegram", done: true },
            { time: "Sun 09:00", title: "Service reminder", who: "Telegram", done: false },
            { time: "+7 days", title: "No group? → task for leader", who: "Condition", done: false },
          ],
        },
      },
    },
  },
  {
    id: "campaigns",
    group: "outreach",
    related: ["telegram", "viber", "turbosms", "people"],
    copy: {
      ua: {
        seoTitle: "Розсилки — модуль «Моя Церква»",
        seoDescription: "Розсилки для церкви в Telegram, Viber, SMS та на пошту за групами й фільтрами: персональні повідомлення, статистика доставки й відповіді — замість п'яти чатів.",
        title: "Повідомлення, яке дійде до кожного",
        lead: "Модуль «Розсилки» надсилає повідомлення тим, кому вони справді адресовані: домашній групі, волонтерам молодіжки, тим, хто не був три тижні. У той канал, де людина читає, — і ви бачите, хто отримав.",
        highlights: [
          "Telegram, Viber, SMS та пошта з одного вікна",
          "Отримувачі — будь-який фільтр бази",
          "Ім'я, група, дата — підставляються самі",
          "Доставлено, прочитано, відповіли — по кожному",
        ],
        features: [
          { icon: "Send", title: "Усі канали разом", text: "Оберіть канал для кожного або дозвольте системі: Telegram, якщо є, інакше Viber, інакше SMS. Одна розсилка — і всі отримали." },
          { icon: "Filter", title: "Точний список отримувачів", text: "Не «всім», а «батькам дітей 6–10 з Лівого берега» або «служителям, які не підтвердили неділю». Фільтр збережеться для наступного разу." },
          { icon: "User", title: "Персональні повідомлення", text: "«Олено, у четвер ваша група збирається о 19:00 у кімнаті 3» — ім'я, група, час і кімната підставляються з бази." },
          { icon: "CalendarClock", title: "Заплановані й регулярні", text: "Нагадування в суботу ввечері, дайджест у понеділок, привітання з днем народження — налаштували раз, далі саме." },
          { icon: "MessagesSquare", title: "Відповіді повертаються в систему", text: "Людина відповіла «буду» або поставила запитання — відповідь видно в розсилці й у картці, і на неї можна відреагувати." },
          { icon: "PieChart", title: "Статистика доставки", text: "Доставлено, прочитано, перейшли за посиланням, відписались — по кожній розсилці й по кожній людині. Чиї номери не працюють — теж видно." },
        ],
        steps: [
          { title: "Оберіть, кому", text: "Група, служіння, статус або будь-який фільтр — список отримувачів формується з бази, а не з пам'яті." },
          { title: "Напишіть текст", text: "Один текст для всіх каналів або окремий для SMS. Підставте ім'я й деталі — і перевірте на собі." },
          { title: "Надішліть або заплануйте", text: "Зараз, у певний час чи регулярно — а потім дивіться, хто отримав і хто відповів." },
        ],
        audience: [
          { role: "pastor", text: "Звертається до всієї церкви або до конкретного сегмента — і бачить, що повідомлення дійшло." },
          { role: "leader", text: "Пише своїй групі за два кліки з телефона — без пошуку номерів і пересилання в чатах." },
          { role: "reception", text: "Надсилає нагадування зареєстрованим на подію й відповідає на запитання з одного вікна." },
          { role: "member", text: "Отримує лише те, що стосується його: своя група, свої події, свій кемпус." },
        ],
        faq: [
          { q: "Чи потрібні окремі сервіси для SMS та Telegram?", a: "SMS ідуть через TurboSMS, Telegram і Viber — через бота церкви; кожен канал підключається один раз у розділі інтеграцій. Далі всі канали працюють з одного вікна розсилки." },
          { q: "Чи можна написати від імені лідера, а не церкви?", a: "Так. Telegram і Viber надсилають через бота церкви, але з підписом і контактом лідера, а відповіді потрапляють саме йому." },
          { q: "Як не набридати людям розсилками?", a: "Кожна людина має свої налаштування каналів і тем, а відписка від будь-якої категорії — одним натисканням. Система також показує, скільки повідомлень людина отримала за тиждень." },
          { q: "Що з тими, у кого немає месенджерів?", a: "Для них залишаються SMS та пошта, а якщо немає й цього — система покаже список, кому варто подзвонити." },
        ],
        mock: {
          kind: "chat",
          title: "Служіння подяки",
          subtitle: "Розсилка · Telegram · 174/186 прочитали",
          messages: [
            { from: "bot", text: "Олено, вітаємо. Цієї неділі о 10:00 — служіння подяки. Будете з сім'єю?", time: "Сб 18:00" },
            { from: "user", text: "Так, будемо втрьох", time: "Сб 18:12" },
            { from: "bot", text: "Записали 3 місця. «Дитяче містечко» працює з 9:45.", time: "Сб 18:12" },
            { from: "user", text: "А буде трансляція для бабусі?", time: "Сб 18:14" },
            { from: "bot", text: "Так, посилання надішлемо в неділю о 9:30.", time: "Сб 18:15" },
          ],
          input: "Відповісти Олені…",
        },
      },
      en: {
        seoTitle: "Campaigns — My Church module",
        seoDescription: "Church messaging in Telegram, Viber, SMS and email by group and filter: personalised messages, delivery statistics and replies — instead of five chats.",
        title: "A message that reaches every person",
        lead: "The Campaigns module sends messages to the people they're actually for: the Obolon group, youth volunteers, those absent for three weeks. In the channel where each person reads — and you see who received it.",
        highlights: [
          "Telegram, Viber, SMS and email from one window",
          "Recipients are any filter on your database",
          "Name, group, date — filled in automatically",
          "Delivered, read, replied — for every person",
        ],
        features: [
          { icon: "Send", title: "All channels together", text: "Pick a channel for each person or let the system decide: Telegram if they have it, otherwise Viber, otherwise SMS. One campaign — everyone gets it." },
          { icon: "Filter", title: "A precise recipient list", text: "Not \"everyone\" but \"parents of 6–10-year-olds on the Left Bank\" or \"volunteers who haven't confirmed Sunday\". The filter is saved for next time." },
          { icon: "User", title: "Personalised messages", text: "\"Olena, your group meets on Thursday at 19:00 in room 3\" — the name, group, time and room come from the database." },
          { icon: "CalendarClock", title: "Scheduled and recurring", text: "A reminder on Saturday evening, a digest on Monday, birthday greetings — set up once, then it runs itself." },
          { icon: "MessagesSquare", title: "Replies come back in", text: "Someone replies \"I'll be there\" or asks a question — the reply shows up in the campaign and in their profile, ready to act on." },
          { icon: "PieChart", title: "Delivery statistics", text: "Delivered, read, clicked the link, opted out — for every campaign and every person. Numbers that no longer work are visible too." },
        ],
        steps: [
          { title: "Choose who", text: "A group, a ministry, a status or any filter — the recipient list comes from the database, not from memory." },
          { title: "Write the text", text: "One text for every channel or a separate one for SMS. Add the name and details — and test it on yourself." },
          { title: "Send or schedule", text: "Now, at a set time or on a recurring basis — then watch who received it and who replied." },
        ],
        audience: [
          { role: "pastor", text: "Speaks to the whole church or a specific segment — and sees that the message arrived." },
          { role: "leader", text: "Messages their group in two taps from a phone — no hunting for numbers or forwarding in chats." },
          { role: "reception", text: "Sends reminders to everyone registered for an event and answers questions from one window." },
          { role: "member", text: "Gets only what concerns them: their group, their events, their campus." },
        ],
        faq: [
          { q: "Do I need separate services for SMS and Telegram?", a: "SMS goes through TurboSMS, Telegram and Viber through the church bot; each channel is connected once in Integrations. After that every channel works from the one campaign window." },
          { q: "Can a message come from a leader rather than the church?", a: "Yes. Telegram and Viber send via the church bot, but with the leader's name and contact, and replies go to that leader." },
          { q: "How do we avoid overwhelming people?", a: "Every person has their own channel and topic settings, and can opt out of any category with one tap. The system also shows how many messages a person received this week." },
          { q: "What about people without messengers?", a: "They still get SMS and email, and if there's neither, the system gives you a list of who to call." },
        ],
        mock: {
          kind: "chat",
          title: "Thanksgiving service",
          subtitle: "Campaign · Telegram · 174 of 186 read",
          messages: [
            { from: "bot", text: "Olena, hi. Thanksgiving service this Sunday at 10:00. Will the family be coming?", time: "Sat 18:00" },
            { from: "user", text: "Yes, all three of us", time: "Sat 18:12" },
            { from: "bot", text: "Three places saved. Kids Town opens at 9:45.", time: "Sat 18:12" },
            { from: "user", text: "Will there be a live stream for grandma?", time: "Sat 18:14" },
            { from: "bot", text: "Yes, we'll send the link on Sunday at 9:30.", time: "Sat 18:15" },
          ],
          input: "Reply to Olena…",
        },
      },
    },
  },
  {
    id: "knowledge",
    group: "team",
    related: ["learning", "ministries", "notion", "org"],
    copy: {
      ua: {
        seoTitle: "База знань — модуль «Моя Церква»",
        seoDescription: "Документи, інструкції, регламенти й матеріали церкви в одному місці замість Google Диска й Notion: доступ за ролями, історія версій і пошук по всьому тексту.",
        title: "Знання, які не йдуть разом із людиною",
        lead: "Модуль «База знань» зберігає все, що команда й так знає, але тримає в головах і чатах: як проводити служіння, де ключ від звукової, як зустрічати гостей. Замість Google Диска, Notion і «запитай у Андрія».",
        highlights: [
          "Документи, чек-листи, відео та файли",
          "Доступ за ролями: команда, лідери, вся церква",
          "Пошук по всьому тексту, а не лише по назвах",
          "Прив'язка до служіння, події чи ролі",
        ],
        features: [
          { icon: "BookOpen", title: "Документи й розділи", text: "Регламенти, інструкції, сценарії служінь, статут — структурою розділів, з форматуванням, картинками й вкладеннями." },
          { icon: "ListChecks", title: "Чек-листи", text: "Відкриття зали в неділю, підготовка табору, зустріч гостей — чек-лист відкривається служителю саме тоді, коли потрібен." },
          { icon: "KeyRound", title: "Доступ за ролями", text: "Політики й договори бачить команда, інструкції звукової — служіння звуку, а розклад і правила — вся церква." },
          { icon: "Search", title: "Пошук по всьому", text: "«Ключ від звукової», «як увімкнути проєктор», «правила для волонтерів табору» — знаходиться за секунду з телефона." },
          { icon: "History", title: "Версії та автори", text: "Хто і коли змінив документ, що саме — і повернення до попередньої версії одним кліком." },
          { icon: "Video", title: "Відео та матеріали", text: "Ноти, презентації, записи навчань, відео для нових служителів — поруч із текстом, у тому ж розділі." },
        ],
        steps: [
          { title: "Зберіть те, що вже є", text: "Перенесіть документи з Google Диска чи Notion, вставте посилання на відео, додайте файли." },
          { title: "Розкладіть по розділах", text: "Служіння, команда, події, для новеньких — і дайте кожному розділу свої права доступу." },
          { title: "Прив'яжіть до процесів", text: "Інструкція відкривається в картці служіння, чек-лист — у задачі, матеріали курсу — в уроці." },
        ],
        audience: [
          { role: "pastor", text: "Знає, що передача будь-якого служіння не залежить від однієї людини — усе описано." },
          { role: "leader", text: "Має під рукою сценарій зустрічі, правила групи й матеріали для навчання лідерів." },
          { role: "volunteer", text: "Відкриває інструкцію до своєї ролі з телефона за хвилину до служіння." },
          { role: "hr", text: "Тримає договори, політики й регламенти команди з контрольованим доступом." },
        ],
        faq: [
          { q: "У нас усе в Google Диску. Навіщо переносити?", a: "Диск зберігає файли, але не знає, що документ стосується звукового служіння, і не покаже його новому служителю сам. У базі знань документ прив'язаний до ролі, служіння чи події — і відкривається там, де потрібен." },
          { q: "Чи можна тримати документи в Notion і бачити їх тут?", a: "Так. Інтеграція з Notion синхронізує обрані сторінки, і вони відкриваються в «Моїй Церкві» з тими самими правами доступу." },
          { q: "Хто може редагувати?", a: "Ви призначаєте редакторів на кожен розділ. Решта читає, а зміни бачать із позначкою, хто й коли їх зробив." },
          { q: "Чи шукає пошук у вкладених файлах?", a: "Так — у PDF, Word і презентаціях. Пошук працює по тексту документа, а не лише по назві." },
        ],
        mock: {
          kind: "list",
          title: "База знань",
          subtitle: "64 документи · 9 розділів",
          items: [
            { title: "Зустріч гостей у неділю", sub: "Рецепція · Ірина Шевчук", meta: "оновлено вчора", badge: { label: "Чек-лист", tone: "green" } },
            { title: "Звуковий пульт: інструкція", sub: "Служіння звуку · Дмитро Лис", meta: "2 тижні тому", badge: { label: "Інструкція", tone: "brand" } },
            { title: "Правила волонтерів табору", sub: "Табори · Наталя Рудь", meta: "серпень", badge: { label: "Регламент", tone: "violet" } },
            { title: "Сценарій зустрічі групи", sub: "Лідери груп · Андрій Мельник", meta: "оновлено", badge: { label: "Шаблон", tone: "neutral" } },
            { title: "Політика захисту дітей", sub: "Дитяче містечко · лише команда", meta: "версія 3", badge: { label: "Обмежений", tone: "amber" } },
          ],
          footer: "Пошук: «ключ від звукової»",
        },
      },
      en: {
        seoTitle: "Knowledge base — My Church module",
        seoDescription: "Church documents, guides, policies and materials in one place instead of Google Drive and Notion: role-based access, version history and full-text search.",
        title: "Knowledge that stays when people move on",
        lead: "The Knowledge base keeps everything the team already knows but holds in heads and chats: how to run a service, where the sound room key is, how to welcome guests. Instead of Google Drive, Notion and \"ask Andrii\".",
        highlights: [
          "Documents, checklists, videos and files",
          "Access by role: team, leaders, whole church",
          "Search the full text, not just titles",
          "Linked to a ministry, event or role",
        ],
        features: [
          { icon: "BookOpen", title: "Documents and sections", text: "Policies, guides, service outlines, the constitution — organised in sections, with formatting, images and attachments." },
          { icon: "ListChecks", title: "Checklists", text: "Opening the hall on Sunday, camp preparation, welcoming guests — the checklist opens for the volunteer exactly when it's needed." },
          { icon: "KeyRound", title: "Access by role", text: "The team sees policies and contracts, the sound ministry sees sound desk guides, and the whole church sees the schedule and rules." },
          { icon: "Search", title: "Search everything", text: "\"Sound room key\", \"how to turn on the projector\", \"camp volunteer rules\" — found in a second from a phone." },
          { icon: "History", title: "Versions and authors", text: "Who changed a document, when and what exactly — and a return to the previous version in one click." },
          { icon: "Video", title: "Video and materials", text: "Sheet music, presentations, training recordings, videos for new volunteers — next to the text, in the same section." },
        ],
        steps: [
          { title: "Gather what you have", text: "Move documents over from Google Drive or Notion, paste video links, add files." },
          { title: "Sort into sections", text: "Ministries, team, events, for newcomers — and give each section its own access rights." },
          { title: "Tie it to your processes", text: "A guide opens in the ministry card, a checklist inside a task, course materials inside a lesson." },
        ],
        audience: [
          { role: "pastor", text: "Knows that handing over any ministry doesn't depend on one person — it's all written down." },
          { role: "leader", text: "Has the meeting outline, group rules and leader training materials to hand." },
          { role: "volunteer", text: "Opens the guide for their role on a phone a minute before the service." },
          { role: "hr", text: "Keeps contracts, policies and team regulations with controlled access." },
        ],
        faq: [
          { q: "Everything is in Google Drive. Why move it?", a: "Drive stores files, but it doesn't know a document belongs to the sound ministry and won't show it to a new volunteer on its own. In the knowledge base a document is tied to a role, ministry or event — and opens where it's needed." },
          { q: "Can we keep documents in Notion and see them here?", a: "Yes. The Notion integration syncs the pages you choose, and they open in My Church with the same access rights." },
          { q: "Who can edit?", a: "You appoint editors for each section. Everyone else reads, and changes are shown with who made them and when." },
          { q: "Does search look inside attached files?", a: "Yes — PDF, Word and presentations. Search goes through the text of a document, not just its title." },
        ],
        mock: {
          kind: "list",
          title: "Knowledge base",
          subtitle: "64 documents · 9 sections",
          items: [
            { title: "Welcoming guests on Sunday", sub: "Reception · Iryna Shevchuk", meta: "updated yesterday", badge: { label: "Checklist", tone: "green" } },
            { title: "Sound desk: how-to", sub: "Sound ministry · Dmytro Lys", meta: "2 weeks ago", badge: { label: "Guide", tone: "brand" } },
            { title: "Camp volunteer rules", sub: "Camps · Natalia Rud", meta: "August", badge: { label: "Policy", tone: "violet" } },
            { title: "Small group meeting outline", sub: "Group leaders · Andrii Melnyk", meta: "updated", badge: { label: "Template", tone: "neutral" } },
            { title: "Child safeguarding policy", sub: "Kids Town · team only", meta: "version 3", badge: { label: "Restricted", tone: "amber" } },
          ],
          footer: "Search: \"sound room key\"",
        },
      },
    },
  },
  {
    id: "tables",
    group: "team",
    related: ["analytics", "inventory", "accounting", "forms"],
    copy: {
      ua: {
        seoTitle: "Таблиці — модуль «Моя Церква»",
        seoDescription: "Гнучкі таблиці для будь-якого обліку церкви замість Excel: свої колонки, зв'язок із людьми й подіями, фільтри, формули та спільна робота без версій файлу.",
        title: "Будь-який облік — без Excel і файлів у чатах",
        lead: "Модуль «Таблиці» — для всього, під що немає окремого модуля: подарунки дітям на Різдво, облік ключів, чергування прибирання, бюджет виїзду. Колонки ваші, а люди, групи й події — з бази, а не передруковані.",
        highlights: [
          "Типи колонок: текст, число, дата, список, файл, людина",
          "Колонка «Людина» тягне картку з бази",
          "Фільтри, сортування, групування, формули",
          "Спільна робота без «фінальна_версія_2.xlsx»",
        ],
        features: [
          { icon: "Table2", title: "Свої колонки", text: "Текст, число, дата, чекбокс, список, файл, посилання — і колонки-зв'язки з людьми, групами, подіями чи іншими таблицями." },
          { icon: "Users", title: "Зв'язок із базою", text: "Впишіть у колонку «Відповідальний» ім'я — і система підставить картку людини з телефоном. Змінився номер — змінився скрізь." },
          { icon: "Calculator", title: "Формули та підсумки", text: "Сума, середнє, кількість, «днів до» — у колонках і в підсумковому рядку. Бюджет виїзду рахується сам." },
          { icon: "LayoutGrid", title: "Кілька виглядів", text: "Та сама таблиця — як список, дошка, календар або групування за статусом. Кожен дивиться так, як зручно йому." },
          { icon: "FileSpreadsheet", title: "Імпорт і експорт Excel", text: "Перенесіть наявну таблицю за хвилину, а звіт для ради вивантажте в Excel чи CSV, коли потрібно." },
          { icon: "ShieldCheck", title: "Права на рівні таблиці", text: "Бюджет бачать пастор і бухгалтер, чергування — вся команда, а редагувати можуть лише відповідальні." },
        ],
        steps: [
          { title: "Створіть або імпортуйте", text: "Порожня таблиця, шаблон — чергування, інвентар, бюджет — або ваш Excel-файл." },
          { title: "Прив'яжіть до бази", text: "Колонки з людьми, групами й подіями заповнюйте з підказок — без передруку імен." },
          { title: "Працюйте разом", text: "Кілька людей редагують одночасно, зміни зберігаються самі, а історія показує, хто що змінив." },
        ],
        audience: [
          { role: "pastor", text: "Бачить усі обліки церкви в одному місці, а не в десятку файлів у різних людей." },
          { role: "leader", text: "Веде чергування, списки на виїзд чи збір коштів у групі без окремого Excel." },
          { role: "accountant", text: "Тримає бюджети служінь і проєктів у таблицях, пов'язаних із витратами в бухгалтерії." },
          { role: "volunteer", text: "Відкриває чергування або список закупівель з телефона й відмічає своє." },
        ],
        faq: [
          { q: "Чим це краще за Google Таблиці?", a: "Колонка «Людина» — це картка з бази, а не текст. Ви бачите телефон, групу й статус, а коли людина змінить номер, він оновиться в усіх таблицях. І права доступу — на рівні системи, а не окремого файлу." },
          { q: "Чи є формули?", a: "Так: арифметика, підсумки по колонках, дати («днів до події»), умовні значення. Складних макросів немає — для цього є модулі бухгалтерії та аналітики." },
          { q: "Чи можна перенести наявний Excel?", a: "Завантажте файл — колонки й типи підберуться самі, а імена в колонках з людьми ми запропонуємо зіставити з картками." },
          { q: "Скільки таблиць можна створити?", a: "Скільки потрібно. Таблиці групуються по служіннях і проєктах, тож навіть десятки обліків не перетворюються на хаос." },
        ],
        mock: {
          kind: "table",
          title: "Різдвяні подарунки дітям",
          subtitle: "Дитяче містечко · 64 дитини · ₴19 200",
          columns: ["Дитина", "Вік", "Подарунок", "Купує"],
          rows: [
            { cells: ["Соломія К.", "6", "Фарби", "Олена К."], badge: { label: "Куплено", tone: "green" } },
            { cells: ["Тимофій Р.", "9", "Конструктор", "Наталя Р."], badge: { label: "Куплено", tone: "green" } },
            { cells: ["Злата М.", "4", "Книжка", "Марія І."], badge: { label: "У процесі", tone: "amber" } },
            { cells: ["Марко П.", "11", "М'яч", "Василь П."], badge: { label: "Очікує", tone: "neutral" } },
            { cells: ["Єва Ш.", "7", "Пазл", "Ірина Ш."], badge: { label: "Куплено", tone: "green" } },
          ],
        },
      },
      en: {
        seoTitle: "Tables — My Church module",
        seoDescription: "Flexible tables for any church record instead of Excel: your own columns, links to people and events, filters, formulas and shared editing, no file versions.",
        title: "Any record you need, without Excel",
        lead: "The Tables module is for everything that doesn't have a module of its own: Christmas gifts for kids, a key register, a cleaning rota, a trip budget. The columns are yours; the people, groups and events come from the database, not retyped.",
        highlights: [
          "Column types: text, number, date, list, file, person",
          "A \"Person\" column pulls the profile from the database",
          "Filters, sorting, grouping, formulas",
          "Shared editing with no \"final_v2.xlsx\"",
        ],
        features: [
          { icon: "Table2", title: "Your own columns", text: "Text, number, date, checkbox, list, file, link — and link columns to people, groups, events or other tables." },
          { icon: "Users", title: "Linked to the database", text: "Type a name into the \"Owner\" column — the system fills in the person's profile with their phone. Number changed — it changes everywhere." },
          { icon: "Calculator", title: "Formulas and totals", text: "Sum, average, count, \"days until\" — in columns and in the totals row. The trip budget adds itself up." },
          { icon: "LayoutGrid", title: "Several views", text: "The same table as a list, a board, a calendar or grouped by status. Everyone looks at it the way that suits them." },
          { icon: "FileSpreadsheet", title: "Excel import and export", text: "Bring an existing spreadsheet over in a minute, and export a report for the board to Excel or CSV whenever you need." },
          { icon: "ShieldCheck", title: "Table-level permissions", text: "The pastor and accountant see the budget, the whole team sees the rota, and only the owners can edit." },
        ],
        steps: [
          { title: "Create or import", text: "An empty table, a template — rota, inventory, budget — or your own Excel file." },
          { title: "Link it to the database", text: "Fill people, group and event columns from suggestions — no retyping names." },
          { title: "Work together", text: "Several people edit at once, changes save themselves, and the history shows who changed what." },
        ],
        audience: [
          { role: "pastor", text: "Sees every church record in one place, not in a dozen files held by different people." },
          { role: "leader", text: "Runs the rota, trip lists or a group collection without a separate Excel file." },
          { role: "accountant", text: "Keeps ministry and project budgets in tables linked to expenses in Accounting." },
          { role: "volunteer", text: "Opens the rota or shopping list on a phone and ticks off their part." },
        ],
        faq: [
          { q: "Why is this better than Google Sheets?", a: "A \"Person\" column is a profile from the database, not text. You see the phone, group and status, and when someone changes their number it updates in every table. Access rights live in the system, not in a single file." },
          { q: "Are there formulas?", a: "Yes: arithmetic, column totals, dates (\"days until the event\"), conditional values. There are no complex macros — that's what the Accounting and Analytics modules are for." },
          { q: "Can I import an existing Excel file?", a: "Upload the file — columns and types are detected automatically, and we'll offer to match names in people columns to profiles." },
          { q: "How many tables can we create?", a: "As many as you need. Tables are grouped by ministry and project, so even dozens of records don't turn into chaos." },
        ],
        mock: {
          kind: "table",
          title: "Christmas gifts for kids",
          subtitle: "Kids Town · 64 children · ₴19,200",
          columns: ["Child", "Age", "Gift", "Buyer"],
          rows: [
            { cells: ["Solomiia K.", "6", "Paints", "Olena K."], badge: { label: "Bought", tone: "green" } },
            { cells: ["Tymofii R.", "9", "Building set", "Natalia R."], badge: { label: "Bought", tone: "green" } },
            { cells: ["Zlata M.", "4", "Book", "Maria I."], badge: { label: "In progress", tone: "amber" } },
            { cells: ["Marko P.", "11", "Football", "Vasyl P."], badge: { label: "Pending", tone: "neutral" } },
            { cells: ["Yeva S.", "7", "Puzzle", "Iryna S."], badge: { label: "Bought", tone: "green" } },
          ],
        },
      },
    },
  },
  {
    id: "projects",
    group: "team",
    related: ["events", "ministries", "tables", "requests"],
    copy: {
      ua: {
        seoTitle: "Проєкти — модуль «Моя Церква»",
        seoDescription: "Задачі, дошки й дедлайни для команд і подій церкви замість Trello: підготовка події по кроках, відповідальні з бази, нагадування в Telegram і видимий прогрес.",
        title: "Кожна задача має відповідального й дедлайн",
        lead: "Модуль «Проєкти» замінює Trello і списки в чатах. Підготовка конференції, табір, ремонт зали, новий курс — задачі на дошці, відповідальні з бази, дедлайни з нагадуваннями й прогрес, який пастор бачить без нарад.",
        highlights: [
          "Дошки, списки та календар задач",
          "Відповідальний — людина з бази, з нагадуванням у Telegram",
          "Шаблони: конференція, табір, Різдво",
          "Прогрес проєкту видно на дашборді",
        ],
        features: [
          { icon: "Kanban", title: "Дошки й статуси", text: "«Зробити → У роботі → Готово» або свої етапи: перетягуйте картки, бачте вузькі місця, не питайте «як там справи»." },
          { icon: "UserCheck", title: "Відповідальні з бази", text: "Призначаєте задачу — людина отримує повідомлення в Telegram і бачить її у своєму списку. Змінили відповідального — він теж дізнається сам." },
          { icon: "CalendarCheck", title: "Дедлайни й нагадування", text: "За три дні, за день, у день — нагадування йдуть самі, а прострочені задачі підсвічуються на дошці й у дайджесті керівнику." },
          { icon: "Copy", title: "Шаблони проєктів", text: "Провели конференцію один раз — збережіть як шаблон. Наступного року всі 80 задач із термінами створяться за секунду відносно нової дати." },
          { icon: "Milestone", title: "Етапи й підзадачі", text: "Великі задачі діляться на кроки, етапи — на тижні. Чек-лист усередині картки, коментарі та файли — теж." },
          { icon: "Gauge", title: "Прогрес без нарад", text: "Скільки готово, що прострочено, хто перевантажений — на одному екрані для керівника проєкту та пастора." },
        ],
        steps: [
          { title: "Створіть проєкт", text: "З шаблону або з нуля: назва, дата, команда — і дошка готова." },
          { title: "Розподіліть задачі", text: "Кожна картка — з відповідальним і дедлайном. Людина одразу бачить її в телефоні." },
          { title: "Ведіть дошку", text: "Команда пересуває картки, коментує й прикріплює файли; нагадування йдуть самі." },
          { title: "Збережіть як шаблон", text: "Наступна подія стартує з готового плану, а не з порожнього аркуша." },
        ],
        audience: [
          { role: "pastor", text: "Бачить стан усіх проєктів церкви — від Різдва до ремонту — без окремих нарад і звітів." },
          { role: "leader", text: "Веде підготовку події зі своєю командою: дошка, дедлайни, хто що зробив." },
          { role: "volunteer", text: "Бачить лише свої задачі з термінами й відмічає виконання з телефона." },
          { role: "hr", text: "Розуміє навантаження команди: у кого забагато задач, хто вільний для нового проєкту." },
        ],
        faq: [
          { q: "Чим це краще за Trello?", a: "Відповідальні — реальні люди з бази церкви з їхніми ролями й контактами, нагадування йдуть у Telegram-бот церкви, а проєкт прив'язаний до події в календарі. Не треба запрошувати кожного в окремий сервіс." },
          { q: "Чи бачать волонтери всі проєкти?", a: "Ні. Служитель бачить свої задачі й дошки проєктів, де він у команді. Керівник проєкту — весь проєкт, пастор — усе." },
          { q: "Чи можна зв'язати задачі з подією або служінням?", a: "Так. Проєкт прив'язується до події з календаря, а дедлайни рахуються відносно її дати — перенесли подію, зсунулись і терміни." },
          { q: "Що, як у задачі немає чіткого відповідального?", a: "Задачу можна віддати команді служіння — її побачать усі учасники, і перший, хто візьме, стане відповідальним." },
        ],
        mock: {
          kind: "board",
          title: "Молодіжна конференція",
          subtitle: "12 жовтня · 48 задач · 71% готово",
          columns: [
            {
              title: "Зробити",
              cards: [
                { title: "Замовити банери", sub: "Ірина Шевчук · до 3 жов", tag: { label: "Реклама", tone: "violet" } },
                { title: "Волонтери на вхід", sub: "Василь Панченко · до 8 жов", tag: { label: "Команда", tone: "brand" } },
              ],
            },
            {
              title: "У роботі",
              cards: [
                { title: "Реєстраційна форма", sub: "Марія Іщенко · до 1 жов", tag: { label: "Реєстрація", tone: "amber" } },
                { title: "Програма й таймінг", sub: "Андрій Мельник · до 5 жов", tag: { label: "Програма", tone: "brand" } },
                { title: "Звук і світло", sub: "Дмитро Лис · до 10 жов", tag: { label: "Техніка", tone: "neutral" } },
              ],
            },
            {
              title: "Готово",
              cards: [
                { title: "Зала заброньована", sub: "Наталя Рудь", tag: { label: "Приміщення", tone: "green" } },
                { title: "Бюджет затверджено", sub: "Олена Ковальчук", tag: { label: "Фінанси", tone: "green" } },
              ],
            },
          ],
        },
        pipeline: {
          title: "Шлях задачі в проєкті",
          text: "Приклад: задача «Замовити банери» в проєкті молодіжної конференції.",
          stages: [
            { title: "Створена", tone: "neutral", text: "Керівник проєкту додає картку на дошку: назва, опис, макет у вкладенні.", auto: "Підставляє дедлайн із шаблону — відлік іде від дати конференції." },
            { title: "Призначена", tone: "brand", text: "Відповідальною стає Ірина з команди реклами.", auto: "Надсилає їй картку в Telegram і додає задачу в її особистий список." },
            { title: "У роботі", tone: "amber", text: "Ірина пише коментарі, прикріплює фінальний макет і відмічає підзадачі.", auto: "Нагадує за три дні й ще раз за день до терміну." },
            { title: "Прострочена", tone: "red", text: "Термін минув, банерів із друку ще немає.", auto: "Піднімає картку вгору дошки й додає її в дайджест керівнику проєкту." },
            { title: "Готово", tone: "green", text: "Банери привезли, Ірина закриває картку.", auto: "Оновлює прогрес проєкту й лишає задачу в шаблоні на наступний рік." },
          ],
        },
      },
      en: {
        seoTitle: "Projects — My Church module",
        seoDescription: "Tasks, boards and deadlines for church teams instead of Trello: step-by-step event prep, owners from the database, Telegram reminders and visible progress.",
        title: "Every task has an owner and a deadline",
        lead: "The Projects module replaces Trello and to-do lists in chats. Conference prep, a camp, a hall renovation, a new course — tasks on a board, owners from the database, deadlines with reminders and progress the pastor sees without a meeting.",
        highlights: [
          "Boards, lists and a task calendar",
          "The owner is a person from the database, reminded in Telegram",
          "Templates: conference, camp, Christmas",
          "Project progress on the dashboard",
        ],
        features: [
          { icon: "Kanban", title: "Boards and statuses", text: "\"To do → In progress → Done\" or your own stages: drag cards, spot bottlenecks, stop asking \"how's it going\"." },
          { icon: "UserCheck", title: "Owners from the database", text: "Assign a task — the person gets a Telegram message and sees it in their list. Change the owner — they find out on their own too." },
          { icon: "CalendarCheck", title: "Deadlines and reminders", text: "Three days before, a day before, on the day — reminders go out on their own, and overdue tasks are highlighted on the board and in the lead's digest." },
          { icon: "Copy", title: "Project templates", text: "Run a conference once — save it as a template. Next year all 80 tasks with their deadlines are created in a second, relative to the new date." },
          { icon: "Milestone", title: "Stages and subtasks", text: "Big tasks split into steps, stages into weeks. A checklist inside the card, comments and files too." },
          { icon: "Gauge", title: "Progress without meetings", text: "How much is done, what's overdue, who's overloaded — on one screen for the project lead and the pastor." },
        ],
        steps: [
          { title: "Create a project", text: "From a template or from scratch: name, date, team — and the board is ready." },
          { title: "Hand out the tasks", text: "Every card has an owner and a deadline. The person sees it on their phone straight away." },
          { title: "Run the board", text: "The team moves cards, comments and attaches files; reminders go out on their own." },
          { title: "Save as a template", text: "The next event starts from a ready plan, not a blank page." },
        ],
        audience: [
          { role: "pastor", text: "Sees the state of every church project — from Christmas to the renovation — without extra meetings or reports." },
          { role: "leader", text: "Runs event preparation with their team: the board, deadlines, who did what." },
          { role: "volunteer", text: "Sees only their own tasks with deadlines and marks them done from a phone." },
          { role: "hr", text: "Understands the team's workload: who has too many tasks, who has capacity for a new project." },
        ],
        faq: [
          { q: "Why is this better than Trello?", a: "Owners are real people from the church database with their roles and contacts, reminders go through the church's Telegram bot, and the project is tied to an event in the calendar. Nobody has to be invited to yet another service." },
          { q: "Do volunteers see every project?", a: "No. A volunteer sees their own tasks and the boards of projects they're part of. The project lead sees the whole project, the pastor sees everything." },
          { q: "Can tasks be linked to an event or ministry?", a: "Yes. A project attaches to a calendar event and deadlines are counted from its date — move the event and the deadlines shift with it." },
          { q: "What if a task has no obvious owner?", a: "Assign it to a ministry team — every member sees it, and the first to pick it up becomes the owner." },
        ],
        mock: {
          kind: "board",
          title: "Youth conference",
          subtitle: "12 October · 48 tasks · 71% done",
          columns: [
            {
              title: "To do",
              cards: [
                { title: "Order banners", sub: "Iryna Shevchuk · by 3 Oct", tag: { label: "Promo", tone: "violet" } },
                { title: "Door volunteers", sub: "Vasyl Panchenko · by 8 Oct", tag: { label: "Team", tone: "brand" } },
              ],
            },
            {
              title: "In progress",
              cards: [
                { title: "Sign-up form", sub: "Maria Ishchenko · by 1 Oct", tag: { label: "Sign-up", tone: "amber" } },
                { title: "Programme and timing", sub: "Andrii Melnyk · by 5 Oct", tag: { label: "Programme", tone: "brand" } },
                { title: "Sound and lights", sub: "Dmytro Lys · by 10 Oct", tag: { label: "Tech", tone: "neutral" } },
              ],
            },
            {
              title: "Done",
              cards: [
                { title: "Hall booked", sub: "Natalia Rud", tag: { label: "Venue", tone: "green" } },
                { title: "Budget approved", sub: "Olena Kovalchuk", tag: { label: "Finance", tone: "green" } },
              ],
            },
          ],
        },
        pipeline: {
          title: "A task's path through a project",
          text: "Example: the \"Order banners\" task in the youth conference project.",
          stages: [
            { title: "Created", tone: "neutral", text: "The project lead adds a card to the board: title, description, artwork attached.", auto: "Fills in the deadline from the template — counted back from the conference date." },
            { title: "Assigned", tone: "brand", text: "Iryna from the promo team becomes the owner.", auto: "Sends her the card in Telegram and adds the task to her personal list." },
            { title: "In progress", tone: "amber", text: "Iryna writes comments, attaches the final artwork and ticks off subtasks.", auto: "Reminds her three days before and again the day before the deadline." },
            { title: "Overdue", tone: "red", text: "The deadline has passed and the banners aren't back from the printer.", auto: "Lifts the card to the top of the board and adds it to the project lead's digest." },
            { title: "Done", tone: "green", text: "The banners arrive and Iryna closes the card.", auto: "Updates the project progress and keeps the task in the template for next year." },
          ],
        },
      },
    },
  },
];
